-- ============================================================================
-- Ezkey Migration V2: Add Multi-Tenant Security Support
-- ============================================================================
-- Description: Adds multi-tenant isolation and administrative security features
--              without modifying existing tables from V1.
-- 
-- Context: This migration introduces tenant-based isolation and admin hierarchy
--          while preserving all existing functionality from V1.
--
-- Author: Ezkey contributors
-- Date: 2025-10-13
-- ============================================================================

-- ============================================================================
-- STEP 1: Create Tenant Table
-- ============================================================================

-- Tenant table for multi-tenant isolation
CREATE TABLE ezkey_tenant (
    tenant_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tenant_name VARCHAR(100) NOT NULL UNIQUE,
    tenant_description TEXT,
    created_by_admin_id INT, -- Will be added after ezkey_admin creation
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL
);

-- Add table-level comment
COMMENT ON TABLE ezkey_tenant IS
'Multi-tenant isolation table. Each tenant represents a distinct organization or customer using Ezkey. Provides data isolation and administrative boundaries.';

-- Add column-level comments
COMMENT ON COLUMN ezkey_tenant.tenant_id IS 'Primary key - unique identifier for the tenant, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_tenant.tenant_name IS 'Unique tenant name used for identification and display purposes';
COMMENT ON COLUMN ezkey_tenant.tenant_description IS 'Optional description providing context about the tenant organization or purpose';
COMMENT ON COLUMN ezkey_tenant.created_by_admin_id IS 'Foreign key to admin who created this tenant - will be populated after admin table creation';
COMMENT ON COLUMN ezkey_tenant.created_at IS 'Audit timestamp with timezone recording when tenant was created - immutable value for compliance tracking';
COMMENT ON COLUMN ezkey_tenant.active IS 'Operational control flag - when FALSE, disables tenant operations while preserving data';

-- ============================================================================
-- STEP 2: Create Admin Table
-- ============================================================================

-- Administrative users table with multi-tenant support
CREATE TABLE ezkey_admin (
    admin_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    admin_type VARCHAR(20) NOT NULL CHECK (admin_type IN ('GLOBAL_ADMIN', 'TENANT_ADMIN', 'INTEGRATION_ADMIN')),
    tenant_id INT REFERENCES ezkey_tenant(tenant_id),
    integration_id INT REFERENCES ezkey_integration(integration_id),
    mfa_enabled BOOLEAN DEFAULT TRUE NOT NULL,
    mfa_required BOOLEAN DEFAULT TRUE NOT NULL,
    mfa_enrollment_id INT REFERENCES ezkey_enrollment(enrollment_id),
    password_change_required BOOLEAN DEFAULT FALSE NOT NULL,
    created_by_admin_id INT REFERENCES ezkey_admin(admin_id),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_login_at TIMESTAMPTZ,
    last_password_change TIMESTAMPTZ,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    
    -- Admin hierarchy constraints
    CONSTRAINT check_admin_hierarchy CHECK (
        (admin_type = 'GLOBAL_ADMIN' AND tenant_id IS NULL AND integration_id IS NULL) OR
        (admin_type = 'TENANT_ADMIN' AND tenant_id IS NOT NULL AND integration_id IS NULL) OR
        (admin_type = 'INTEGRATION_ADMIN' AND tenant_id IS NOT NULL AND integration_id IS NOT NULL)
    )
);

-- Add table-level comment
COMMENT ON TABLE ezkey_admin IS
'Administrative users with multi-tenant support and hierarchical access control. Supports password-based authentication with MFA integration.';

-- Add column-level comments
COMMENT ON COLUMN ezkey_admin.admin_id IS 'Primary key - unique identifier for the admin user, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_admin.username IS 'Unique username for admin authentication and identification';
COMMENT ON COLUMN ezkey_admin.password_hash IS 'BCrypt-hashed password for admin authentication - will be removed in V3 passwordless migration';
COMMENT ON COLUMN ezkey_admin.admin_type IS 'Administrator type: GLOBAL_ADMIN (system-wide), TENANT_ADMIN (tenant-scoped), or INTEGRATION_ADMIN (integration-scoped)';
COMMENT ON COLUMN ezkey_admin.tenant_id IS 'Foreign key to tenant - determines administrative scope for TENANT_ADMIN and INTEGRATION_ADMIN types';
COMMENT ON COLUMN ezkey_admin.integration_id IS 'Foreign key to integration - determines administrative scope for INTEGRATION_ADMIN type only';
COMMENT ON COLUMN ezkey_admin.mfa_enabled IS 'Flag indicating if MFA is enabled for this admin - will be removed in V3 passwordless migration';
COMMENT ON COLUMN ezkey_admin.mfa_required IS 'Flag indicating if MFA is required for this admin - will be removed in V3 passwordless migration';
COMMENT ON COLUMN ezkey_admin.mfa_enrollment_id IS 'Foreign key to enrollment for MFA authentication - will be repurposed in V3 for passwordless auth';
COMMENT ON COLUMN ezkey_admin.password_change_required IS 'Flag indicating if admin must change password on next login - will be removed in V3 passwordless migration';
COMMENT ON COLUMN ezkey_admin.created_by_admin_id IS 'Foreign key to admin who created this admin user - supports audit trail';
COMMENT ON COLUMN ezkey_admin.created_at IS 'Audit timestamp with timezone recording when admin was created - immutable value for compliance tracking';
COMMENT ON COLUMN ezkey_admin.last_login_at IS 'Timestamp with timezone of last successful login - used for security monitoring and session management';
COMMENT ON COLUMN ezkey_admin.last_password_change IS 'Timestamp with timezone of last password change - will be removed in V3 passwordless migration';
COMMENT ON COLUMN ezkey_admin.active IS 'Operational control flag - when FALSE, disables admin access while preserving data';

-- ============================================================================
-- STEP 3: Create Admin Tokens Table
-- ============================================================================

-- Bearer tokens for admin API authentication
CREATE TABLE ezkey_admin_tokens (
    token_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    bearer_token VARCHAR(255) NOT NULL UNIQUE,
    admin_id INT NOT NULL REFERENCES ezkey_admin(admin_id),
    admin_type VARCHAR(20) NOT NULL,
    tenant_id INT REFERENCES ezkey_tenant(tenant_id),
    integration_id INT REFERENCES ezkey_integration(integration_id),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    last_used_at TIMESTAMPTZ,
    ip_address VARCHAR(45),
    user_agent TEXT,
    active BOOLEAN DEFAULT TRUE NOT NULL
);

-- Add table-level comment
COMMENT ON TABLE ezkey_admin_tokens IS
'Bearer tokens for admin API authentication. Provides session management and access control for administrative operations.';

-- Add column-level comments
COMMENT ON COLUMN ezkey_admin_tokens.token_id IS 'Primary key - unique identifier for the token, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_admin_tokens.bearer_token IS 'Unique bearer token string used for API authentication - cryptographically secure random value';
COMMENT ON COLUMN ezkey_admin_tokens.admin_id IS 'Foreign key to admin user who owns this token';
COMMENT ON COLUMN ezkey_admin_tokens.admin_type IS 'Admin type at time of token creation - used for authorization decisions';
COMMENT ON COLUMN ezkey_admin_tokens.tenant_id IS 'Tenant scope at time of token creation - used for multi-tenant authorization';
COMMENT ON COLUMN ezkey_admin_tokens.integration_id IS 'Integration scope at time of token creation - used for integration-specific authorization';
COMMENT ON COLUMN ezkey_admin_tokens.created_at IS 'Audit timestamp with timezone recording when token was created';
COMMENT ON COLUMN ezkey_admin_tokens.expires_at IS 'Token expiration timestamp with timezone - tokens automatically become invalid after this time';
COMMENT ON COLUMN ezkey_admin_tokens.last_used_at IS 'Timestamp with timezone of last token usage - used for security monitoring and session management';
COMMENT ON COLUMN ezkey_admin_tokens.ip_address IS 'IP address from which token was created - used for security monitoring';
COMMENT ON COLUMN ezkey_admin_tokens.user_agent IS 'User agent string from token creation - used for security monitoring';
COMMENT ON COLUMN ezkey_admin_tokens.active IS 'Operational control flag - when FALSE, disables token usage while preserving audit data';

-- ============================================================================
-- STEP 4: Create Admin Temp Tokens Table
-- ============================================================================

-- Temporary tokens for MFA authentication flow (will be removed in V3)
CREATE TABLE ezkey_admin_temp_tokens (
    temp_token_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    temp_token VARCHAR(255) NOT NULL UNIQUE,
    admin_id INT NOT NULL REFERENCES ezkey_admin(admin_id),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    mfa_required BOOLEAN DEFAULT TRUE NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL
);

-- Add table-level comment
COMMENT ON TABLE ezkey_admin_temp_tokens IS
'Temporary tokens for MFA authentication flow. Used during password-based authentication before MFA verification. Will be removed in V3 passwordless migration.';

-- Add column-level comments
COMMENT ON COLUMN ezkey_admin_temp_tokens.temp_token_id IS 'Primary key - unique identifier for the temporary token, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_admin_temp_tokens.temp_token IS 'Unique temporary token string used during MFA authentication flow';
COMMENT ON COLUMN ezkey_admin_temp_tokens.admin_id IS 'Foreign key to admin user for whom this temporary token was created';
COMMENT ON COLUMN ezkey_admin_temp_tokens.created_at IS 'Audit timestamp with timezone recording when temporary token was created';
COMMENT ON COLUMN ezkey_admin_temp_tokens.expires_at IS 'Temporary token expiration timestamp with timezone - short-lived for security';
COMMENT ON COLUMN ezkey_admin_temp_tokens.mfa_required IS 'Flag indicating if MFA verification is required before token can be used';
COMMENT ON COLUMN ezkey_admin_temp_tokens.active IS 'Operational control flag - when FALSE, disables temporary token usage';

-- ============================================================================
-- STEP 5: Extend Existing Tables with Tenant Support
-- ============================================================================

-- Add tenant isolation to existing integration table
ALTER TABLE ezkey_integration ADD COLUMN tenant_id INT REFERENCES ezkey_tenant(tenant_id);
ALTER TABLE ezkey_integration ADD COLUMN is_system_integration BOOLEAN DEFAULT FALSE;
ALTER TABLE ezkey_integration ADD COLUMN created_by_admin_id INT REFERENCES ezkey_admin(admin_id);

-- Add column comments for new integration columns
COMMENT ON COLUMN ezkey_integration.tenant_id IS 'Foreign key to tenant - provides multi-tenant isolation for integrations';
COMMENT ON COLUMN ezkey_integration.is_system_integration IS 'Flag indicating if this is a system-level integration (e.g., admin MFA) - not tenant-specific';
COMMENT ON COLUMN ezkey_integration.created_by_admin_id IS 'Foreign key to admin who created this integration - supports audit trail';

-- ============================================================================
-- STEP 6: Create Performance Indexes
-- ============================================================================

-- Indexes for admin token performance
CREATE INDEX idx_admin_tokens_active ON ezkey_admin_tokens(bearer_token, active) WHERE active = TRUE;
CREATE INDEX idx_admin_tokens_expired ON ezkey_admin_tokens(expires_at) WHERE active = TRUE;

-- Indexes for admin temp token performance
CREATE INDEX idx_admin_temp_tokens_expired ON ezkey_admin_temp_tokens(expires_at) WHERE active = TRUE;

-- Indexes for admin table performance
CREATE INDEX idx_admin_username ON ezkey_admin(username) WHERE active = TRUE;
CREATE INDEX idx_admin_type ON ezkey_admin(admin_type) WHERE active = TRUE;

-- Indexes for tenant table performance
CREATE INDEX idx_tenant_name ON ezkey_tenant(tenant_name) WHERE active = TRUE;

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- Multi-tenant security infrastructure added successfully.
-- V3 migration will transform admin authentication to passwordless-only.
-- ============================================================================
