-- Migration V6: Create audit log table for security and compliance tracking
-- This migration creates comprehensive audit logging infrastructure for SOC2 compliance
-- and security monitoring of all critical operations in the Ezkey system

-- Audit log table: tracks all security-relevant events across admin-api and auth-api
-- Designed for comprehensive audit trail supporting SOC2 certification requirements
-- Includes IP address, user agent, request/response details for forensic analysis
CREATE TABLE ezkey_audit_log (
    audit_log_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    
    -- Event Classification
    event_type VARCHAR(50) NOT NULL,  -- Event category: AUTH, ENROLLMENT, INTEGRATION, ADMIN_AUTH, etc.
    event_action VARCHAR(100) NOT NULL,  -- Specific action: LOGIN, CREATE, BIND, VERIFY, APPROVE, DENY, etc.
    event_status VARCHAR(20) NOT NULL CHECK (event_status IN ('SUCCESS', 'FAILURE', 'ERROR')),  -- Outcome of the event
    
    -- API Identification
    api_name VARCHAR(50) NOT NULL CHECK (api_name IN ('ADMIN_API', 'AUTH_API')),  -- Which API generated this event
    endpoint_path VARCHAR(255),  -- Full endpoint path (e.g., /api/v1/auth-attempts)
    http_method VARCHAR(10),  -- HTTP method: GET, POST, PUT, DELETE
    
    -- Network and Client Information
    ip_address VARCHAR(45),  -- IPv4 or IPv6 address of the client
    user_agent TEXT,  -- Browser/client user agent string for device identification
    
    -- Entity References
    admin_id INT,  -- Reference to ezkey_admin if admin action
    integration_id INT,  -- Reference to ezkey_integration if integration-related
    enrollment_id INT,  -- Reference to ezkey_enrollment if enrollment-related
    auth_attempt_id INT,  -- Reference to ezkey_auth_attempt if auth-related
    tenant_id INT,  -- Reference to ezkey_tenant for multi-tenancy tracking
    
    -- Event Details
    event_details TEXT,  -- JSON or text with additional context about the event
    error_message TEXT,  -- Error details if event_status is FAILURE or ERROR
    
    -- Timestamps
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,  -- When the event occurred
    
    -- Foreign key constraints (nullable to allow auditing even if entities are deleted)
    CONSTRAINT fk_audit_admin FOREIGN KEY (admin_id) REFERENCES ezkey_admin(admin_id) ON DELETE SET NULL,
    CONSTRAINT fk_audit_integration FOREIGN KEY (integration_id) REFERENCES ezkey_integration(integration_id) ON DELETE SET NULL,
    CONSTRAINT fk_audit_enrollment FOREIGN KEY (enrollment_id) REFERENCES ezkey_enrollment(enrollment_id) ON DELETE SET NULL,
    CONSTRAINT fk_audit_auth_attempt FOREIGN KEY (auth_attempt_id) REFERENCES ezkey_auth_attempt(auth_attempt_id) ON DELETE SET NULL,
    CONSTRAINT fk_audit_tenant FOREIGN KEY (tenant_id) REFERENCES ezkey_tenant(tenant_id) ON DELETE SET NULL
);

-- Add table-level comment
COMMENT ON TABLE ezkey_audit_log IS 'Comprehensive audit log for all security-relevant events across Ezkey APIs. Tracks authentication, enrollment, and administrative actions with full context for SOC2 compliance and security forensics. Retention policy managed by scheduled cleanup jobs.';

-- Add column-level comments
COMMENT ON COLUMN ezkey_audit_log.audit_log_id IS 'Primary key - unique identifier for this audit entry, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_audit_log.event_type IS 'Event category for classification: AUTH (authentication), ENROLLMENT (device enrollment), INTEGRATION (integration management), ADMIN_AUTH (admin authentication), etc.';
COMMENT ON COLUMN ezkey_audit_log.event_action IS 'Specific action performed: LOGIN, LOGOUT, CREATE, BIND, VERIFY, APPROVE, DENY, PASSWORD_CHANGE, etc.';
COMMENT ON COLUMN ezkey_audit_log.event_status IS 'Outcome of the event: SUCCESS (completed successfully), FAILURE (operation failed), ERROR (system error occurred)';
COMMENT ON COLUMN ezkey_audit_log.api_name IS 'API that generated this audit event: ADMIN_API (organization-facing) or AUTH_API (mobile device-facing)';
COMMENT ON COLUMN ezkey_audit_log.endpoint_path IS 'Full REST endpoint path that was accessed (e.g., /api/v1/auth-attempts/pending)';
COMMENT ON COLUMN ezkey_audit_log.http_method IS 'HTTP method used: GET, POST, PUT, DELETE, PATCH';
COMMENT ON COLUMN ezkey_audit_log.ip_address IS 'Client IP address (IPv4 or IPv6) extracted from request headers (X-Forwarded-For, X-Real-IP, or remote address)';
COMMENT ON COLUMN ezkey_audit_log.user_agent IS 'HTTP User-Agent header for client device identification and browser tracking';
COMMENT ON COLUMN ezkey_audit_log.admin_id IS 'Foreign key to ezkey_admin if action performed by administrator (nullable, SET NULL on delete to preserve audit trail)';
COMMENT ON COLUMN ezkey_audit_log.integration_id IS 'Foreign key to ezkey_integration if event relates to specific integration (nullable, SET NULL on delete)';
COMMENT ON COLUMN ezkey_audit_log.enrollment_id IS 'Foreign key to ezkey_enrollment if event relates to specific device enrollment (nullable, SET NULL on delete)';
COMMENT ON COLUMN ezkey_audit_log.auth_attempt_id IS 'Foreign key to ezkey_auth_attempt if event relates to authentication attempt (nullable, SET NULL on delete)';
COMMENT ON COLUMN ezkey_audit_log.tenant_id IS 'Foreign key to ezkey_tenant for multi-tenant audit tracking (nullable, SET NULL on delete)';
COMMENT ON COLUMN ezkey_audit_log.event_details IS 'Additional event context in JSON or text format - may include request parameters, changed values, etc. (sensitive data should be redacted)';
COMMENT ON COLUMN ezkey_audit_log.error_message IS 'Error details if event_status is FAILURE or ERROR - helps with troubleshooting and security analysis';
COMMENT ON COLUMN ezkey_audit_log.created_at IS 'Timestamp when the event occurred - immutable audit timestamp for compliance and forensic analysis';

-- Performance indexes for common audit queries
CREATE INDEX idx_audit_log_created_at ON ezkey_audit_log(created_at DESC);  -- Time-based queries and retention cleanup
CREATE INDEX idx_audit_log_event_type ON ezkey_audit_log(event_type, created_at DESC);  -- Filter by event category
CREATE INDEX idx_audit_log_admin ON ezkey_audit_log(admin_id, created_at DESC) WHERE admin_id IS NOT NULL;  -- Admin activity tracking
CREATE INDEX idx_audit_log_enrollment ON ezkey_audit_log(enrollment_id, created_at DESC) WHERE enrollment_id IS NOT NULL;  -- Enrollment lifecycle tracking
CREATE INDEX idx_audit_log_auth_attempt ON ezkey_audit_log(auth_attempt_id, created_at DESC) WHERE auth_attempt_id IS NOT NULL;  -- Authentication attempt tracking
CREATE INDEX idx_audit_log_ip_address ON ezkey_audit_log(ip_address, created_at DESC) WHERE ip_address IS NOT NULL;  -- IP-based security analysis
CREATE INDEX idx_audit_log_status ON ezkey_audit_log(event_status, created_at DESC);  -- Filter by success/failure
CREATE INDEX idx_audit_log_api_endpoint ON ezkey_audit_log(api_name, endpoint_path, created_at DESC);  -- API endpoint usage analysis
