-- Logo management table: provides a curated list of logos for integrations
-- Logos can be stored as URLs or as base64-encoded image data
-- This table allows centralized management of integration logos
CREATE TABLE ezkey_logo (
    logo_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    logo_name VARCHAR(100) NOT NULL UNIQUE,  -- Unique identifier/name for the logo (e.g., 'acme-corp', 'bank-logo')
    logo_url VARCHAR(500),  -- External URL to the logo image (optional if logo_data is provided)
    logo_data TEXT,  -- Base64-encoded logo image data (optional if logo_url is provided)
    logo_content_type VARCHAR(50),  -- MIME type for the logo (e.g., 'image/png', 'image/jpeg', 'image/svg+xml')
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,  -- Audit timestamp for logo creation
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,  -- Audit timestamp for last logo update
    CONSTRAINT logo_source_check CHECK (logo_url IS NOT NULL OR logo_data IS NOT NULL)  -- At least one source must be provided
);

-- Add table-level comment
COMMENT ON TABLE ezkey_logo IS 'Logo management table providing a curated list of logos for integrations. Logos can be stored as external URLs or as base64-encoded image data. This centralized approach allows better control and validation of integration branding.';

-- Add column-level comments
COMMENT ON COLUMN ezkey_logo.logo_id IS 'Primary key - unique identifier for the logo, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_logo.logo_name IS 'Unique identifier/name for the logo - used to reference the logo from integrations (e.g., acme-corp, bank-logo)';
COMMENT ON COLUMN ezkey_logo.logo_url IS 'External URL to the logo image - optional if logo_data is provided';
COMMENT ON COLUMN ezkey_logo.logo_data IS 'Base64-encoded logo image data - optional if logo_url is provided, allows self-hosted logos without external dependencies';
COMMENT ON COLUMN ezkey_logo.logo_content_type IS 'MIME type for the logo (e.g., image/png, image/jpeg, image/svg+xml) - required for proper rendering';
COMMENT ON COLUMN ezkey_logo.created_at IS 'Audit timestamp recording when logo was created';
COMMENT ON COLUMN ezkey_logo.updated_at IS 'Audit timestamp recording when logo was last updated - useful for cache invalidation';

-- Add index for faster logo lookups by name
CREATE INDEX idx_logo_name ON ezkey_logo(logo_name);

-- Alter integration table to add foreign key to logo table
ALTER TABLE ezkey_integration ADD COLUMN logo_id INT REFERENCES ezkey_logo(logo_id) ON DELETE SET NULL;

-- Add comment for new column
COMMENT ON COLUMN ezkey_integration.logo_id IS 'Foreign key to ezkey_logo table - references the logo to be displayed for this integration (optional)';

-- Data migration: For existing integrations with logo URLs, we keep the integration_logo column for backward compatibility
-- The integration_logo column will be deprecated in favor of logo_id but kept for now to avoid breaking changes
COMMENT ON COLUMN ezkey_integration.integration_logo IS 'DEPRECATED: Legacy logo URL field - use logo_id reference to ezkey_logo table instead. This column is kept for backward compatibility and will be removed in a future version.';
