/*
 * Ezkey - Open Source MFA/Passkey Alternative
 *
 * Copyright (c) 2025 Ezkey contributors
 * Licensed under the MIT License. See LICENSE file in the project root for full license information.
 *
 * Entity: ReencryptionBatch
 * Description: JPA entity representing a batch re-encryption operation.
 */

package org.ezkey.security.domain.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.OffsetDateTime;

/**
 * JPA entity representing a batch re-encryption operation.
 *
 * <p>This entity tracks the progress of re-encrypting data from an old encryption key to a new key.
 * It enables fault-tolerant batch processing with resumability and progress monitoring.
 *
 * <p><b>Batch Lifecycle:</b>
 *
 * <ul>
 *   <li><b>PENDING:</b> Created but not started
 *   <li><b>IN_PROGRESS:</b> Actively processing records
 *   <li><b>COMPLETED:</b> Finished successfully
 *   <li><b>FAILED:</b> Error occurred (may be retried)
 *   <li><b>PAUSED:</b> Manually paused by admin
 * </ul>
 *
 * <p><b>Database Table:</b> ezkey_reencryption_batch
 *
 * <p><b>Project:</b> Ezkey - Open Source MFA/Passkey Alternative
 *
 * <p><b>License:</b> MIT
 *
 * @author Ezkey contributors
 * @since 2025
 */
@Entity
@Table(name = "ezkey_reencryption_batch")
public class ReencryptionBatch {

  /**
   * Primary key identifier for this batch.
   *
   * <p>Auto-generated by database sequence.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "batch_id")
  private Integer batchId;

  /**
   * Database table name containing encrypted data to be re-encrypted.
   *
   * <p>Example: ezkey_enrollment
   */
  @Column(name = "target_table", nullable = false, length = 100)
  private String targetTable;

  /**
   * Column name within target_table containing encrypted data.
   *
   * <p>Example: integration_private_key
   */
  @Column(name = "target_column", nullable = false, length = 100)
  private String targetColumn;

  /**
   * Foreign key reference to the old encryption key (source).
   *
   * <p>This is the key currently used in encrypted data that needs to be re-encrypted.
   */
  @ManyToOne
  @JoinColumn(name = "old_key_id", nullable = false)
  private EncryptionKey oldKey;

  /**
   * Foreign key reference to the new encryption key (target).
   *
   * <p>This is the key that will be used after re-encryption (typically the PRIMARY key).
   */
  @ManyToOne
  @JoinColumn(name = "new_key_id", nullable = false)
  private EncryptionKey newKey;

  /**
   * Total number of records that need to be re-encrypted.
   *
   * <p>Primarily set from a count at batch creation time. Under concurrent traffic, additional rows
   * may still be written with the old key while a batch runs; {@link #updateProgress(int, int,
   * int)} may increase this field so it never falls below the sum of done, failed, and skipped
   * counters, satisfying database invariants.
   */
  @Column(name = "records_total", nullable = false)
  private Integer recordsTotal;

  /**
   * Number of records successfully re-encrypted.
   *
   * <p>Incremented as batch progresses.
   */
  @Column(name = "records_done", nullable = false)
  private Integer recordsDone = 0;

  /**
   * Number of records that failed re-encryption.
   *
   * <p>May include decryption errors, invalid format, or other failures.
   */
  @Column(name = "records_failed", nullable = false)
  private Integer recordsFailed = 0;

  /**
   * Number of records already encrypted with target key.
   *
   * <p>Optimization: skip records that are already encrypted with the new key.
   */
  @Column(name = "records_skipped", nullable = false)
  private Integer recordsSkipped = 0;

  /** Batch status indicating current state. */
  @Enumerated(EnumType.STRING)
  @Column(name = "status", nullable = false, length = 20)
  private BatchStatus status;

  /**
   * Progress percentage (0.00-100.00).
   *
   * <p>Calculated as (records_done / records_total) * 100.
   */
  @Column(name = "progress_pct", nullable = false, precision = 5, scale = 2)
  private BigDecimal progressPct = BigDecimal.ZERO;

  /**
   * Timestamp when batch processing started.
   *
   * <p>Set when status changes to IN_PROGRESS.
   */
  @Column(name = "started_at")
  private OffsetDateTime startedAt;

  /**
   * Timestamp when batch processing completed.
   *
   * <p>Set when status changes to COMPLETED or FAILED.
   */
  @Column(name = "completed_at")
  private OffsetDateTime completedAt;

  /**
   * Timestamp of the last batch of records processed.
   *
   * <p>Updated periodically during processing for monitoring.
   */
  @Column(name = "last_batch_at")
  private OffsetDateTime lastBatchAt;

  /**
   * Resume point: last successfully processed record ID.
   *
   * <p>Enables fault tolerance - if service crashes, resume from this ID.
   */
  @Column(name = "last_record_id")
  private Long lastRecordId;

  /**
   * Error message if batch failed.
   *
   * <p>Contains summary of failure reason for troubleshooting.
   */
  @Column(name = "error_message", columnDefinition = "TEXT")
  private String errorMessage;

  /**
   * Count of individual record errors encountered during processing.
   *
   * <p>May be less than records_failed if errors were retried.
   */
  @Column(name = "error_count", nullable = false)
  private Integer errorCount = 0;

  /**
   * Number of times this batch has been retried after failure.
   *
   * <p>Incremented on each retry attempt.
   */
  @Column(name = "retry_count", nullable = false)
  private Integer retryCount = 0;

  /**
   * Maximum number of retry attempts allowed before marking batch as FAILED.
   *
   * <p>Default: 3
   */
  @Column(name = "max_retries", nullable = false)
  private Integer maxRetries = 3;

  /**
   * Identifier of who/what created this batch.
   *
   * <p>Values: SYSTEM (scheduled job), or admin username (manual trigger).
   */
  @Column(name = "created_by", nullable = false, length = 100)
  private String createdBy = "SYSTEM";

  /**
   * Timestamp when this record was created.
   *
   * <p>Automatically set by database DEFAULT CURRENT_TIMESTAMP.
   */
  @Column(name = "created_at", nullable = false)
  private OffsetDateTime createdAt;

  /**
   * Timestamp when this record was last updated.
   *
   * <p>Automatically updated by database DEFAULT CURRENT_TIMESTAMP.
   */
  @Column(name = "updated_at", nullable = false)
  private OffsetDateTime updatedAt;

  /** Default constructor for JPA. */
  public ReencryptionBatch() {
    this.createdAt = OffsetDateTime.now();
    this.updatedAt = OffsetDateTime.now();
  }

  /**
   * Constructor for creating a new re-encryption batch.
   *
   * @param targetTable the target table name
   * @param targetColumn the target column name
   * @param oldKey the old encryption key (source)
   * @param newKey the new encryption key (target)
   * @param recordsTotal total records to process
   * @param createdBy who created the batch
   */
  public ReencryptionBatch(
      String targetTable,
      String targetColumn,
      EncryptionKey oldKey,
      EncryptionKey newKey,
      Integer recordsTotal,
      String createdBy) {
    this.targetTable = targetTable;
    this.targetColumn = targetColumn;
    this.oldKey = oldKey;
    this.newKey = newKey;
    this.recordsTotal = recordsTotal;
    this.createdBy = createdBy;
    this.status = BatchStatus.PENDING;
    this.recordsDone = 0;
    this.recordsFailed = 0;
    this.recordsSkipped = 0;
    this.progressPct = BigDecimal.ZERO;
    this.errorCount = 0;
    this.retryCount = 0;
    this.maxRetries = 3;
    this.createdAt = OffsetDateTime.now();
    this.updatedAt = OffsetDateTime.now();
  }

  /**
   * Update progress and recalculate percentage.
   *
   * <p>If actual work ({@code done + failed + skipped}) exceeds the initial total (e.g. new rows
   * encrypted with the old key during the run), {@code records_total} is raised so the batch row
   * satisfies {@code chk_reencryption_batch_records} and {@code chk_reencryption_batch_progress}.
   *
   * @param done number of records done
   * @param failed number of records failed
   * @param skipped number of records skipped
   */
  public void updateProgress(int done, int failed, int skipped) {
    this.recordsDone = done;
    this.recordsFailed = failed;
    this.recordsSkipped = skipped;
    int processed = done + failed + skipped;
    int previousTotal = recordsTotal != null ? recordsTotal : 0;
    this.recordsTotal = Math.max(previousTotal, processed);
    if (recordsTotal > 0) {
      double pct = ((double) recordsDone / recordsTotal) * 100.0;
      this.progressPct = BigDecimal.valueOf(pct).setScale(2, java.math.RoundingMode.HALF_UP);
    }
    this.updatedAt = OffsetDateTime.now();
  }

  // Getters and setters

  public Integer getBatchId() {
    return batchId;
  }

  public void setBatchId(Integer batchId) {
    this.batchId = batchId;
  }

  public String getTargetTable() {
    return targetTable;
  }

  public void setTargetTable(String targetTable) {
    this.targetTable = targetTable;
  }

  public String getTargetColumn() {
    return targetColumn;
  }

  public void setTargetColumn(String targetColumn) {
    this.targetColumn = targetColumn;
  }

  public EncryptionKey getOldKey() {
    return oldKey;
  }

  public void setOldKey(EncryptionKey oldKey) {
    this.oldKey = oldKey;
  }

  public EncryptionKey getNewKey() {
    return newKey;
  }

  public void setNewKey(EncryptionKey newKey) {
    this.newKey = newKey;
  }

  public Integer getRecordsTotal() {
    return recordsTotal;
  }

  public void setRecordsTotal(Integer recordsTotal) {
    this.recordsTotal = recordsTotal;
  }

  public Integer getRecordsDone() {
    return recordsDone;
  }

  public void setRecordsDone(Integer recordsDone) {
    this.recordsDone = recordsDone;
  }

  public Integer getRecordsFailed() {
    return recordsFailed;
  }

  public void setRecordsFailed(Integer recordsFailed) {
    this.recordsFailed = recordsFailed;
  }

  public Integer getRecordsSkipped() {
    return recordsSkipped;
  }

  public void setRecordsSkipped(Integer recordsSkipped) {
    this.recordsSkipped = recordsSkipped;
  }

  public BatchStatus getStatus() {
    return status;
  }

  public void setStatus(BatchStatus status) {
    this.status = status;
    this.updatedAt = OffsetDateTime.now();
  }

  public BigDecimal getProgressPct() {
    return progressPct;
  }

  public void setProgressPct(BigDecimal progressPct) {
    this.progressPct = progressPct;
  }

  public OffsetDateTime getStartedAt() {
    return startedAt;
  }

  public void setStartedAt(OffsetDateTime startedAt) {
    this.startedAt = startedAt;
  }

  public OffsetDateTime getCompletedAt() {
    return completedAt;
  }

  public void setCompletedAt(OffsetDateTime completedAt) {
    this.completedAt = completedAt;
  }

  public OffsetDateTime getLastBatchAt() {
    return lastBatchAt;
  }

  public void setLastBatchAt(OffsetDateTime lastBatchAt) {
    this.lastBatchAt = lastBatchAt;
  }

  public Long getLastRecordId() {
    return lastRecordId;
  }

  public void setLastRecordId(Long lastRecordId) {
    this.lastRecordId = lastRecordId;
    this.updatedAt = OffsetDateTime.now();
  }

  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }

  public Integer getErrorCount() {
    return errorCount;
  }

  public void setErrorCount(Integer errorCount) {
    this.errorCount = errorCount;
  }

  public Integer getRetryCount() {
    return retryCount;
  }

  public void setRetryCount(Integer retryCount) {
    this.retryCount = retryCount;
  }

  public Integer getMaxRetries() {
    return maxRetries;
  }

  public void setMaxRetries(Integer maxRetries) {
    this.maxRetries = maxRetries;
  }

  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  /**
   * Enumeration of batch statuses.
   *
   * <p>Defines the lifecycle states of re-encryption batches.
   */
  public enum BatchStatus {
    /** Created but not started. */
    PENDING,

    /** Actively processing records. */
    IN_PROGRESS,

    /** Finished successfully. */
    COMPLETED,

    /** Error occurred (may be retried). */
    FAILED,

    /** Manually paused by admin. */
    PAUSED
  }
}
