# Ezkey Auth API - Default Configuration
spring.application.name=ezkey-sim-api
server.port=8081

# Logging Configuration
logging.level.org.ezkey=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.springframework.data.jpa.repository=DEBUG
logging.level.org.springframework.boot.autoconfigure.domain=DEBUG

# Development Tools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true 

server.tomcat.threads.max=2
server.tomcat.threads.min-spare=2

# Flyway Migration
spring.flyway.enabled=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
