#!/usr/bin/env bash
# Fail if Android Studio / Gradle regenerate a daemon JVM toolchain pin that
# would reintroduce Foojay auto-download of a non-17 JDK (incident #677).
#
# Usage (from ezkey_mobile/):
#   ./scripts/assert-no-gradle-daemon-jvm.sh
#   ./scripts/assert-no-gradle-daemon-jvm.sh --root /path/to/ezkey_mobile
#   ./scripts/assert-no-gradle-daemon-jvm.sh --self-test
#
# Project posture: JDK 17 only in CI/local standard path. Do not commit
# android/gradle/gradle-daemon-jvm.properties. Keep
# org.gradle.java.installations.auto-download=false in gradle.properties.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SELF_TEST=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root)
      ROOT="$(cd "$2" && pwd)"
      shift 2
      ;;
    --self-test)
      SELF_TEST=true
      shift
      ;;
    -h|--help)
      sed -n '2,14p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 2
      ;;
  esac
done

_fail_daemon_jvm() {
  local daemon_file="$1"
  cat <<EOF >&2
ezkey_mobile: forbidden Gradle daemon JVM criteria file is present:

  ${daemon_file}

This file is generated by Gradle/Android Studio (\`updateDaemonJvm\`) and often
pins JetBrains JDK 21 via Foojay download URLs. Those URLs have returned HTTP 400
and break CI/local builds. Ezkey Mobile standardizes on JDK 17 (no Foojay pin).

Remove it and keep auto-download disabled:

  rm -f android/gradle/gradle-daemon-jvm.properties
  # Confirm in android/gradle.properties:
  #   org.gradle.java.installations.auto-download=false

Then re-run the build with scripts/resolve-android-jdk.sh (or yarn android:install:debug:clean).
Do not re-commit gradle-daemon-jvm.properties. Migrating the project to JDK 21 is a
separate decision — do not solve local Studio prompts by regenerating this file.
EOF
  return 1
}

_check_root() {
  local root="$1"
  local daemon_file="${root}/android/gradle/gradle-daemon-jvm.properties"
  local gradle_props="${root}/android/gradle.properties"

  if [[ -e "$daemon_file" ]]; then
    _fail_daemon_jvm "$daemon_file"
    return 1
  fi

  if [[ -f "$gradle_props" ]]; then
    if grep -Eq '^[[:space:]]*org\.gradle\.java\.installations\.auto-download[[:space:]]*=[[:space:]]*true[[:space:]]*$' \
      "$gradle_props"; then
      cat <<EOF >&2
ezkey_mobile: org.gradle.java.installations.auto-download must stay false.

  File: ${gradle_props}

Foojay/toolchain auto-download is disabled so builds use CI setup-java 17 or
scripts/resolve-android-jdk.sh — never a downloaded JDK 21 daemon pin.
Set:

  org.gradle.java.installations.auto-download=false
EOF
      return 1
    fi
  fi

  echo "[daemon-jvm-guard] OK: no gradle-daemon-jvm.properties; auto-download not enabled (${root})"
  return 0
}

if [[ "$SELF_TEST" == true ]]; then
  TMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/ezkey-daemon-jvm-selftest.XXXXXX")"
  cleanup() { rm -rf "$TMP_ROOT"; }
  trap cleanup EXIT

  mkdir -p "${TMP_ROOT}/android/gradle"
  cat >"${TMP_ROOT}/android/gradle.properties" <<'EOF'
org.gradle.java.installations.auto-download=false
EOF

  if ! _check_root "$TMP_ROOT"; then
    echo "[daemon-jvm-guard] self-test failed: clean fixture should pass" >&2
    exit 1
  fi

  cat >"${TMP_ROOT}/android/gradle/gradle-daemon-jvm.properties" <<'EOF'
#This file is generated by updateDaemonJvm
toolchainVendor=JETBRAINS
toolchainVersion=21
EOF

  if _check_root "$TMP_ROOT"; then
    echo "[daemon-jvm-guard] self-test failed: expected failure when daemon JVM file is present" >&2
    exit 1
  fi

  echo "[daemon-jvm-guard] self-test OK: guard fails when gradle-daemon-jvm.properties is present"
  exit 0
fi

_check_root "$ROOT"
