Args = --verbose \
       --no-fallback \
       -H:+ReportExceptionStackTraces \
       -H:+AddAllCharsets \
       --enable-all-security-services \
       -H:IncludeResourceBundles=org.hibernate.validator.ValidationMessages \
       -H:+StaticExecutableWithDynamicLibC \
       -H:+RemoveSaturatedTypeFlows \
       --allow-incomplete-classpath \
       --report-unsupported-elements-at-runtime
