/*
 * Ezkey - Open Source MFA/Passkey Alternative
 *
 * Copyright (c) 2025 Ezkey contributors
 * Licensed under the MIT License. See LICENSE file in the project root for full license information.
 *
 * Configuration: QrCodeProperties
 * Description: Configuration properties for QR code generation, including the public auth-api URL.
 */

package org.ezkey.admin.config;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

/**
 * Configuration properties for QR code generation.
 *
 * <p>
 * These properties control the content included in QR codes generated by the
 * admin API. The
 * primary setting is the public auth-api base URL, which allows mobile
 * applications to dynamically
 * connect to the correct Ezkey auth-api instance when scanning enrollment QR
 * codes.
 *
 * <p>
 * <b>Configuration Example:</b>
 *
 * <pre>
 * ezkey.qr.auth-base-url=https://ezkey.acme.com:8080
 * </pre>
 *
 * <p>
 * <b>Self-Hosted Note:</b> Since Ezkey is designed to be self-hosted, this URL
 * must be the
 * <b>public-facing</b> URL of the auth-api, accessible from the mobile device.
 * In Docker
 * deployments, this is NOT the internal Docker network URL (e.g.,
 * {@code http://auth-api:8080}),
 * but the external URL reachable from outside the Docker network.
 *
 * <p>
 * <b>Backward Compatibility:</b> If not configured, QR codes will omit the
 * {@code authUrl}
 * field. The mobile application will fall back to its configured default base
 * URL.
 *
 * @since 2025
 */
@Component
@ConfigurationProperties(prefix = "ezkey.qr")
public class QrCodeProperties {

  /**
   * Public base URL of the auth-api for inclusion in QR codes.
   *
   * <p>
   * This URL is embedded in QR code payloads so the mobile application knows
   * which Ezkey
   * auth-api instance to connect to. Must be a valid HTTP or HTTPS URL accessible
   * from mobile
   * devices.
   *
   * <p>
   * <b>Examples:</b>
   *
   * <ul>
   * <li>{@code https://ezkey.acme.com:8080} — production with TLS
   * <li>{@code http://192.168.1.100:8080} — local network development
   * <li>{@code https://ezkey.example.com} — behind reverse proxy
   * </ul>
   *
   * <p>
   * <b>Default:</b> null (QR codes will not include auth URL)
   */
  private String authBaseUrl;

  /**
   * Returns the public auth-api base URL for QR code payloads.
   *
   * @return the auth-api base URL, or null if not configured
   */
  public String getAuthBaseUrl() {
    return authBaseUrl;
  }

  /**
   * Sets the public auth-api base URL for QR code payloads.
   *
   * @param authBaseUrl the auth-api base URL (must be a valid HTTP/HTTPS URL)
   */
  public void setAuthBaseUrl(String authBaseUrl) {
    this.authBaseUrl = authBaseUrl;
  }
}
