/*
 * Ezkey - Open Source MFA/Passkey Alternative
 *
 * Copyright (c) 2025 Ezkey contributors
 * Licensed under the MIT License. See LICENSE file in the project root for full license information.
 *
 * Entity: EzkeyEnrollment
 * Description: JPA entity representing enrollment data in the Ezkey system.
 */

package org.ezkey.enrollment.domain.entity;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity representing enrollment data in the Ezkey system.
 * <p>
 * This entity represents the enrollment of a user device with a specific integration,
 * containing all necessary cryptographic keys and enrollment status information.
 * It is used to track the enrollment process and manage device authentication.
 * </p>
 *
 * <p>
 * <b>Project:</b> Ezkey - Open Source MFA/Passkey Alternative
 * </p>
 * <p>
 * <b>License:</b> MIT
 * </p>
 * <p>
 * <b>Usage:</b> Enrollment data persistence
 * </p>
 *
 * @author Ezkey contributors
 * @since 2025
 */
@Entity
@Table(name = "ezkey_enrollment")
public class Enrollment {

    /**
     * Primary key identifier for the enrollment.
     * Auto-generated by the database.
     */
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) @Column(name = "enrollment_id")
    private Integer enrollmentId;

    /**
     * Foreign key reference to the integration.
     * Links this enrollment to a specific integration.
     */
    @Column(name = "integration_id",nullable = false)
    private Integer integrationId;

    /**
     * Human-readable name for the enrollment.
     * Used for display purposes in user interfaces.
     */
    @Column(name = "enrollment_name",nullable = false)
    private String enrollmentName;

    /**
     * Flag indicating if the enrollment has been read by the device.
     * Used to track enrollment status.
     */
    @Column(name = "enrollment_read")
    private Boolean enrollmentRead;

    /**
     * Flag indicating if the enrollment is verified.
     * Used to track enrollment verification status.
     */
    @Column(name = "enrollment_verified")
    private Boolean enrollmentVerified;

    /**
     * Flag indicating if the enrollment is valid.
     * Used to track enrollment verification status.
     */
    @Column(name = "enrollment_valid")
    private Boolean enrollmentValid;

    /**
     * Flag indicating if the enrollment is currently active.
     * Used to enable/disable enrollment.
     */
    @Column(name = "enrollment_active")
    private Boolean enrollmentActive;

    /**
     * Challenge value for enrollment verification.
     * Used in the enrollment challenge-response process.
     */
    @Column(name = "enrollment_challenge")
    private Integer enrollmentChallenge;

    /**
     * Email challenge value for enrollment verification.
     * Used in the enrollment email challenge-response process when email validation is enabled.
     */
    @Column(name = "enrollment_challenge_email")
    private Integer enrollmentChallengeEmail;

    /**
     * Email address for enrollment verification.
     * Used for sending email challenges when email validation is enabled.
     */
    @Column(name = "enrollment_email")
    private String enrollmentEmail;

    /**
     * Unique enrollment proof token for identification.
     * Used for enrollment lookup and verification.
     */
    @Column(name = "enrollment_proof_token",unique = true)
    private String enrollmentProofToken;

    /**
     * Flag indicating if authentication attempts require challenge.
     * Used to configure authentication behavior.
     */
    @Column(name = "auth_attempt_challenge_required")
    private Boolean authAttemptChallengeRequired;

    /**
     * Private key for integration communication.
     * Used for signing messages to the integration.
     */
    @Column(name = "integration_private_key",columnDefinition = "TEXT")
    private String integrationPrivateKey;

    /**
     * Public key for integration communication.
     * Used for verifying messages from the integration.
     */
    @Column(name = "integration_public_key",columnDefinition = "TEXT")
    private String integrationPublicKey;

    /**
     * Public key for the device for auth attempts.
     * Used for device authentication verification.
     */
    @Column(name = "device_public_key",columnDefinition = "TEXT")
    private String devicePublicKey;

    /**
     * Timestamp when the enrollment was created.
     * Used for audit trails and sorting purposes.
     */
    @Column(name = "created_at",nullable = false)
    private LocalDateTime createdAt;

    // Default constructor
    public Enrollment(){
    }

    // Constructor with required fields
    public Enrollment(Integer integrationId,String enrollmentName,String deviceProofToken){
        this.integrationId = integrationId;
        this.enrollmentName = enrollmentName;
        this.setEnrollmentProofToken(deviceProofToken);
        this.createdAt = LocalDateTime.now();
        this.enrollmentRead = false;
        this.enrollmentValid = false;
        this.enrollmentActive = true;
        // Don't set authAttemptChallengeRequired here - let it be set explicitly by the caller
    }

    // Getters and Setters
    public Integer getEnrollmentId() {
        return enrollmentId;
    }

    public void setEnrollmentId(Integer enrollmentId) {
        this.enrollmentId = enrollmentId;
    }

    public Integer getIntegrationId() {
        return integrationId;
    }

    public void setIntegrationId(Integer integrationId) {
        this.integrationId = integrationId;
    }

    public String getEnrollmentName() {
        return enrollmentName;
    }

    public void setEnrollmentName(String enrollmentName) {
        this.enrollmentName = enrollmentName;
    }

    public Boolean getEnrollmentRead() {
        return enrollmentRead;
    }

    public void setEnrollmentRead(Boolean enrollmentRead) {
        this.enrollmentRead = enrollmentRead;
    }

    public Boolean getEnrollmentVerified() {
        return enrollmentVerified;
    }

    public void setEnrollmentVerified(Boolean enrollmentVerified) {
        this.enrollmentVerified = enrollmentVerified;
    }

    public Boolean getEnrollmentValid() {
        return enrollmentValid;
    }

    public void setEnrollmentValid(Boolean enrollmentValid) {
        this.enrollmentValid = enrollmentValid;
    }

    public Boolean getEnrollmentActive() {
        return enrollmentActive;
    }

    public void setEnrollmentActive(Boolean enrollmentActive) {
        this.enrollmentActive = enrollmentActive;
    }

    public Integer getEnrollmentChallenge() {
        return enrollmentChallenge;
    }

    public void setEnrollmentChallenge(Integer enrollmentChallenge) {
        this.enrollmentChallenge = enrollmentChallenge;
    }

    public Integer getEnrollmentChallengeEmail() {
        return enrollmentChallengeEmail;
    }

    public void setEnrollmentChallengeEmail(Integer enrollmentChallengeEmail) {
        this.enrollmentChallengeEmail = enrollmentChallengeEmail;
    }

    public String getEnrollmentEmail() {
        return enrollmentEmail;
    }

    public void setEnrollmentEmail(String enrollmentEmail) {
        this.enrollmentEmail = enrollmentEmail;
    }

    public String getEnrollmentProofToken() {
        return enrollmentProofToken;
    }

    public void setEnrollmentProofToken(String enrollmentProofToken) {
        this.enrollmentProofToken = enrollmentProofToken;
    }

    public Boolean getAuthAttemptChallengeRequired() {
        return authAttemptChallengeRequired;
    }

    public void setAuthAttemptChallengeRequired(Boolean authAttemptChallengeRequired) {
        this.authAttemptChallengeRequired = authAttemptChallengeRequired;
    }

    public String getIntegrationPrivateKey() {
        return integrationPrivateKey;
    }

    public void setIntegrationPrivateKey(String integrationPrivateKey) {
        this.integrationPrivateKey = integrationPrivateKey;
    }

    public String getIntegrationPublicKey() {
        return integrationPublicKey;
    }

    public void setIntegrationPublicKey(String integrationPublicKey) {
        this.integrationPublicKey = integrationPublicKey;
    }

    public String getDevicePublicKey() {
        return devicePublicKey;
    }

    public void setDevicePublicKey(String devicePublicKey) {
        this.devicePublicKey = devicePublicKey;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

}