/*
 * Ezkey - Open Source MFA/Passkey Alternative
 *
 * Copyright (c) 2025 Ezkey contributors
 * Licensed under the MIT License. See LICENSE file in the project root for full license information.
 *
 * Entity: EzkeyEnrollment
 * Description: JPA entity representing enrollment data in the Ezkey system.
 */

package org.ezkey.enrollment.domain.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.Transient;
import java.time.OffsetDateTime;
import org.ezkey.enrollment.domain.EnrollmentStatus;
import org.ezkey.security.EncryptionService;
import org.slf4j.LoggerFactory;

/**
 * JPA entity representing enrollment data in the Ezkey system.
 *
 * <p>This entity represents the enrollment of a user device with a specific integration, containing
 * all necessary cryptographic keys and enrollment status information. It is used to track the
 * enrollment process and manage device authentication.
 *
 * <p><b>Project:</b> Ezkey - Open Source MFA/Passkey Alternative
 *
 * <p><b>License:</b> MIT
 *
 * <p><b>Usage:</b> Enrollment data persistence
 *
 * @author Ezkey contributors
 * @since 2025
 */
@Entity
@EntityListeners(org.ezkey.security.EncryptionEntityListener.class)
@Table(name = "ezkey_enrollment")
public class Enrollment {

  /** Primary key identifier for the enrollment. Auto-generated by the database. */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "enrollment_id")
  private Integer enrollmentId;

  /** Foreign key reference to the integration. Links this enrollment to a specific integration. */
  @Column(name = "integration_id", nullable = false)
  private Integer integrationId;

  /** Human-readable name for the enrollment. Used for display purposes in user interfaces. */
  @Column(name = "enrollment_name", nullable = false)
  private String enrollmentName;

  /**
   * Enrollment lifecycle status tracking. Indicates the current state of the enrollment process.
   */
  @Enumerated(EnumType.STRING)
  @Column(name = "enrollment_status")
  private EnrollmentStatus status;

  /**
   * Flag indicating if the enrollment is currently active. Used to enable/disable enrollment for
   * authentication operations.
   */
  @Column(name = "enrollment_active")
  private Boolean active;

  /**
   * Challenge value for enrollment verification. Used in the enrollment challenge-response process.
   */
  @Column(name = "enrollment_challenge")
  private Integer enrollmentChallenge;

  /**
   * Unique enrollment proof token for identification. Used for enrollment lookup and verification.
   */
  @Column(name = "enrollment_proof_token", unique = true)
  private String enrollmentProofToken;

  /**
   * Flag indicating if authentication attempts require challenge. Used to configure authentication
   * behavior.
   */
  @Column(name = "auth_attempt_challenge_required")
  private Boolean authAttemptChallengeRequired;

  /**
   * Encrypted private key for integration communication (persisted in database).
   * 
   * <p>This field stores the encrypted private key in the database. The value is automatically
   * encrypted before persistence and decrypted when needed via the transient field.
   */
  @Column(name = "integration_private_key", columnDefinition = "TEXT")
  private String encryptedIntegrationPrivateKey;

  /**
   * Decrypted private key for integration communication (transient, not persisted).
   * 
   * <p>This transient field holds the decrypted private key in memory. It is populated
   * automatically when {@link #getIntegrationPrivateKey()} is called. This separation
   * prevents Hibernate dirty checking from triggering re-encryption cycles.
   */
  @Transient
  private String integrationPrivateKey;

  /** Public key for integration communication. Used for verifying messages from the integration. */
  @Column(name = "integration_public_key", columnDefinition = "TEXT")
  private String integrationPublicKey;

  /** Public key for the device for auth attempts. Used for device authentication verification. */
  @Column(name = "device_public_key", columnDefinition = "TEXT")
  private String devicePublicKey;

  /** Timestamp when the enrollment was created. Used for audit trails and sorting purposes. */
  @Column(name = "created_at", nullable = false)
  private OffsetDateTime createdAt;

  // Default constructor
  public Enrollment() {}

  // Constructor with required fields
  public Enrollment(Integer integrationId, String enrollmentName, String deviceProofToken) {
    this.integrationId = integrationId;
    this.enrollmentName = enrollmentName;
    this.setEnrollmentProofToken(deviceProofToken);
    this.createdAt = OffsetDateTime.now();
    this.status = EnrollmentStatus.CREATED;
    this.active = false;
    // Don't set authAttemptChallengeRequired here - let it be set explicitly by the caller
  }

  // Getters and Setters
  public Integer getEnrollmentId() {
    return enrollmentId;
  }

  public void setEnrollmentId(Integer enrollmentId) {
    this.enrollmentId = enrollmentId;
  }

  public Integer getIntegrationId() {
    return integrationId;
  }

  public void setIntegrationId(Integer integrationId) {
    this.integrationId = integrationId;
  }

  public String getEnrollmentName() {
    return enrollmentName;
  }

  public void setEnrollmentName(String enrollmentName) {
    this.enrollmentName = enrollmentName;
  }

  public EnrollmentStatus getStatus() {
    return status;
  }

  public void setStatus(EnrollmentStatus status) {
    this.status = status;
  }

  public Boolean getActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Integer getEnrollmentChallenge() {
    return enrollmentChallenge;
  }

  public void setEnrollmentChallenge(Integer enrollmentChallenge) {
    this.enrollmentChallenge = enrollmentChallenge;
  }

  public String getEnrollmentProofToken() {
    return enrollmentProofToken;
  }

  public void setEnrollmentProofToken(String enrollmentProofToken) {
    this.enrollmentProofToken = enrollmentProofToken;
  }

  public Boolean getAuthAttemptChallengeRequired() {
    return authAttemptChallengeRequired;
  }

  public void setAuthAttemptChallengeRequired(Boolean authAttemptChallengeRequired) {
    this.authAttemptChallengeRequired = authAttemptChallengeRequired;
  }

  /**
   * Gets the integration private key, decrypting it if necessary.
   * 
   * <p>This method automatically decrypts the encrypted value from the database
   * on first access and caches the decrypted value in the transient field to avoid
   * repeated decryption operations.
   * 
   * <p>If encryption is not available or the value is not encrypted, returns
   * the value as-is (backward compatibility with plaintext data).
   * 
   * @return the decrypted integration private key, or plaintext if encryption unavailable
   */
  public String getIntegrationPrivateKey() {
    // If transient field is already populated, return it
    if (integrationPrivateKey != null) {
      return integrationPrivateKey;
    }
    
    // If encrypted field is null, return null
    if (encryptedIntegrationPrivateKey == null) {
      return null;
    }
    
    // Decrypt on first access
    EncryptionService service = getEncryptionService();
    if (service != null && service.isEncryptionAvailable()) {
      if (service.isEncrypted(encryptedIntegrationPrivateKey)) {
        try {
          String decrypted = service.decrypt(encryptedIntegrationPrivateKey);
          // Cache in transient field to avoid repeated decryption
          integrationPrivateKey = decrypted;
          return decrypted;
        } catch (Exception e) {
          LoggerFactory.getLogger(Enrollment.class).warn(
              "Failed to decrypt integration private key for enrollment {}. Returning as-is.",
              enrollmentId,
              e
          );
          // Return encrypted value if decryption fails (backward compatibility)
          return encryptedIntegrationPrivateKey;
        }
      }
    }
    
    // Not encrypted or encryption unavailable - return as-is (backward compatibility)
    integrationPrivateKey = encryptedIntegrationPrivateKey;
    return integrationPrivateKey;
  }

  /**
   * Sets the integration private key in plaintext.
   * 
   * <p>This method stores the plaintext value in the transient field. The value
   * will be automatically encrypted before persistence by {@link EncryptionEntityListener}.
   * 
   * @param integrationPrivateKey the plaintext integration private key to set
   */
  public void setIntegrationPrivateKey(String integrationPrivateKey) {
    this.integrationPrivateKey = integrationPrivateKey;
  }
  
  /**
   * Gets the encryption service for decrypting private keys.
   * 
   * <p>Uses a static access pattern similar to {@link EncryptionEntityListener}
   * since JPA entities cannot use dependency injection directly.
   * 
   * @return the encryption service, or null if not available
   */
  private static EncryptionService getEncryptionService() {
    // Access via EncryptionEntityListener's static field
    // This is a simple pattern to avoid complex injection in entities
    try {
      java.lang.reflect.Field field = 
          Class.forName("org.ezkey.security.EncryptionEntityListener")
              .getDeclaredField("encryptionService");
      field.setAccessible(true);
      return (EncryptionService) field.get(null);
    } catch (Exception e) {
      // If reflection fails, return null (encryption unavailable)
      return null;
    }
  }

  public String getIntegrationPublicKey() {
    return integrationPublicKey;
  }

  public void setIntegrationPublicKey(String integrationPublicKey) {
    this.integrationPublicKey = integrationPublicKey;
  }

  public String getDevicePublicKey() {
    return devicePublicKey;
  }

  public void setDevicePublicKey(String devicePublicKey) {
    this.devicePublicKey = devicePublicKey;
  }

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }
}
