/*
 * Ezkey - Open Source Cryptographic MFA Platform
 *
 * Copyright (c) 2025 Ezkey contributors
 * Licensed under the MIT License. See LICENSE file in the project root for full license information.
 *
 * Entity: EzkeyEnrollment
 * Description: JPA entity representing enrollment data in the Ezkey system.
 */

package org.ezkey.enrollment.domain.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import jakarta.persistence.Version;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import org.ezkey.enrollment.domain.DevicePrivateKeyStorageTier;
import org.ezkey.enrollment.domain.EnrollmentStatus;
import org.ezkey.security.AtRestEncryptionAccess;
import org.ezkey.security.EncryptionOperations;
import org.ezkey.security.EncryptionOperationsHolder;
import org.ezkey.security.Reencryptable;
import org.ezkey.security.SensitiveDataHasher;

/**
 * JPA entity representing enrollment data in the Ezkey system.
 *
 * <p>This entity represents the enrollment of a user device with a specific integration, containing
 * all necessary cryptographic keys and enrollment status information. It is used to track the
 * enrollment process and manage device authentication.
 *
 * <p><b>Project:</b> Ezkey - Open Source Cryptographic MFA Platform
 *
 * <p><b>License:</b> MIT
 *
 * <p><b>Usage:</b> Enrollment data persistence
 *
 * @author Ezkey contributors
 * @since 2025
 */
@Entity
@EntityListeners(org.ezkey.security.EncryptionEntityListener.class)
@Table(name = "ezkey_enrollment")
public class Enrollment implements Reencryptable {

  /** Primary key identifier for the enrollment. Auto-generated by the database. */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "enrollment_id")
  private Integer enrollmentId;

  /**
   * Optimistic locking version for concurrent update protection.
   *
   * <p>Used by JPA to detect concurrent modifications. When a PATCH request includes a stale
   * version, the update fails and the API returns 409 Conflict. Client must re-fetch and retry.
   */
  @Version
  @Column(name = "version", nullable = false)
  private Long version = 0L;

  /** Foreign key reference to the integration. Links this enrollment to a specific integration. */
  @Column(name = "integration_id", nullable = false)
  private Integer integrationId;

  /** Human-readable name for the enrollment. Used for display purposes in user interfaces. */
  @Column(name = "enrollment_name", nullable = false)
  private String enrollmentName;

  /**
   * Enrollment lifecycle status tracking. Indicates the current state of the enrollment process.
   */
  @Enumerated(EnumType.STRING)
  @Column(name = "enrollment_status", nullable = false)
  private EnrollmentStatus status;

  /**
   * Flag indicating if the enrollment is currently active. Used to enable/disable enrollment for
   * authentication operations.
   */
  @Column(name = "enrollment_active", nullable = false)
  private Boolean active;

  /**
   * Challenge value for enrollment verification. Used in the enrollment challenge-response process.
   */
  @Column(name = "enrollment_challenge")
  private Integer enrollmentChallenge;

  /**
   * Encrypted enrollment proof token persisted in the database.
   *
   * <p>The plaintext value is maintained in the transient field {@link #enrollmentProofToken} and
   * encrypted just before persistence by {@code EncryptionEntityListener}. The encrypted value uses
   * the "ENC:" prefix provided by {@link org.ezkey.security.EncryptionService}.
   */
  @Column(name = "enrollment_proof_token", columnDefinition = "TEXT", nullable = false)
  private String encryptedEnrollmentProofToken;

  /**
   * Encryption key id used to encrypt {@link #encryptedEnrollmentProofToken}, parsed from its
   * {@code ENC:{keyId}:} prefix.
   *
   * <p>Populated by {@code EncryptionEntityListener} on initial encrypt and by {@code
   * ReencryptionRecordCipher} on re-encrypt. {@code null} when the value is stored as plaintext
   * (encryption disabled). Enables indexed re-encryption discovery (I-2026-0029), replacing a
   * {@code LIKE 'ENC:{keyId}:%'} scan on the ciphertext column.
   */
  @Column(name = "enrollment_proof_token_encryption_key_id")
  private Long enrollmentProofTokenEncryptionKeyId;

  /** SHA-256 hash of the enrollment proof token for secure lookup and uniqueness validation. */
  @Column(name = "enrollment_proof_token_hash", length = 128, unique = true)
  private String enrollmentProofTokenHash;

  /** Transient plaintext representation of the enrollment proof token. */
  @Transient private String enrollmentProofToken;

  /**
   * Flag indicating if authentication attempts require challenge. Used to configure authentication
   * behavior.
   */
  @Column(name = "auth_attempt_challenge_required", nullable = false)
  private Boolean authAttemptChallengeRequired;

  /**
   * Encrypted EC P-256 private key for integration communication (persisted in database).
   *
   * <p>This field stores the encrypted EC P-256 private key (PKCS#8 format, Base64 encoded) in the
   * database. The value is automatically encrypted before persistence and decrypted when needed via
   * the transient field.
   */
  @Column(name = "integration_private_key", columnDefinition = "TEXT", nullable = false)
  private String encryptedIntegrationPrivateKey;

  /**
   * Encryption key id used to encrypt {@link #encryptedIntegrationPrivateKey}, parsed from its
   * {@code ENC:{keyId}:} prefix.
   *
   * <p>Populated by {@code EncryptionEntityListener} on initial encrypt and by {@code
   * ReencryptionRecordCipher} on re-encrypt. {@code null} when the value is stored as plaintext
   * (encryption disabled). Enables indexed re-encryption discovery (I-2026-0029), replacing a
   * {@code LIKE 'ENC:{keyId}:%'} scan on the ciphertext column.
   */
  @Column(name = "integration_private_key_encryption_key_id")
  private Long integrationPrivateKeyEncryptionKeyId;

  /**
   * Decrypted EC P-256 private key for integration communication (transient, not persisted).
   *
   * <p>This transient field holds the decrypted EC P-256 private key (PKCS#8 format, Base64
   * encoded) in memory. It is populated automatically when {@link #getIntegrationPrivateKey()} is
   * called. This separation prevents Hibernate dirty checking from triggering re-encryption cycles.
   */
  @Transient private String integrationPrivateKey;

  /**
   * EC P-256 public key for integration communication (Base64 encoded, X.509 format). Used for
   * verifying messages from the integration.
   */
  @Column(name = "integration_public_key", columnDefinition = "TEXT", nullable = false)
  private String integrationPublicKey;

  /**
   * EC P-256 public key for the device for auth attempts (Base64 encoded, X.509 format). Used for
   * device authentication verification.
   */
  @Column(name = "device_public_key", columnDefinition = "TEXT")
  private String devicePublicKey;

  /**
   * SHA-256 hash of device public key for uniqueness validation.
   *
   * <p>This hash is used to validate device public key uniqueness independently of encryption
   * format. The hash is computed from the plaintext device public key and stored as a hexadecimal
   * string (64 characters).
   *
   * <p>This field has a unique constraint (excluding NULL values) to ensure each device public key
   * can only be used once for a verified enrollment.
   */
  @Column(name = "device_public_key_hash", length = 64)
  private String devicePublicKeyHash;

  /** Timestamp when the enrollment was created. Used for audit trails and sorting purposes. */
  @Column(name = "created_at", nullable = false)
  private OffsetDateTime createdAt;

  /**
   * Optional expiration for pending enrollment (CREATED/BOUND). When set, bind/verify must complete
   * before this time; after that the enrollment is treated as expired (status EXPIRED). Null means
   * no expiration (current behavior). Set at creation when policy is enabled (e.g. created_at + 30
   * days).
   */
  @Column(name = "expires_at")
  private OffsetDateTime expiresAt;

  /**
   * When the enrollment transitioned to VERIFIED status. Set once when device completes binding.
   * Used for audit trail and lifecycle metrics (tamper-evident monitoring).
   */
  @Column(name = "verified_at")
  private OffsetDateTime verifiedAt;

  /**
   * Admin who created this enrollment (identifiable operator identity). Populated when created via Admin API;
   * null when created via API key.
   */
  @Column(name = "created_by_admin_id")
  private Integer createdByAdminId;

  /**
   * When this enrollment was last used for successful authentication. Updated on each accepted auth
   * attempt. Used for operational hygiene and stale enrollment detection.
   */
  @Column(name = "last_used_at")
  private OffsetDateTime lastUsedAt;

  /**
   * When this enrollment was deactivated by an administrator (reversible). Null if never
   * deactivated. Combined with {@link #deactivatedByAdminId} for rapid access removal audit trail.
   */
  @Column(name = "deactivated_at")
  private OffsetDateTime deactivatedAt;

  /**
   * ID of the administrator who deactivated this enrollment. Null if never deactivated. Used for
   * rapid access removal audit trail (who performed the access removal).
   */
  @Column(name = "deactivated_by_admin_id")
  private Integer deactivatedByAdminId;

  /**
   * When this enrollment was permanently revoked by an administrator. Null if never revoked. Once
   * set, the enrollment cannot be reactivated. Combined with {@link #revokedByAdminId} for rapid
   * access removal on the operator-visible audit trail.
   */
  @Column(name = "revoked_at")
  private OffsetDateTime revokedAt;

  /**
   * ID of the administrator who permanently revoked this enrollment. Null if never revoked. Used
   * for rapid access removal audit trail (who performed the irrevocable access removal).
   */
  @Column(name = "revoked_by_admin_id")
  private Integer revokedByAdminId;

  /**
   * Optional contact for the end-user (device owner). Used for incident response, revocation
   * notices, support. Provided by integrating app at creation.
   */
  @Column(name = "contact_email", length = 255)
  private String contactEmail;

  /**
   * Optional phone number for the end-user (device owner).
   *
   * <p>Stored in canonical E.164 format for operational contact and future communication
   * integrations. Not treated as a verified possession factor in the current security model.
   */
  @Column(name = "contact_phone_number", length = 20)
  private String contactPhoneNumber;

  /**
   * Optional reference to integrating app user (username, user_id). Unique per integration for
   * lookup. Enables future auth attempt creation by userIdentifier.
   */
  @Column(name = "user_identifier", length = 255)
  private String userIdentifier;

  /**
   * Client-reported storage tier for the device private key (set when enrollment reaches VERIFIED).
   */
  @Enumerated(EnumType.STRING)
  @Column(name = "device_private_key_storage_tier", length = 32)
  private DevicePrivateKeyStorageTier devicePrivateKeyStorageTier;

  // Default constructor
  public Enrollment() {
    // Initialize to match database NOT NULL DEFAULT constraints
    this.status = EnrollmentStatus.CREATED;
    this.active = false;
    this.authAttemptChallengeRequired = false;
  }

  // Constructor with required fields
  public Enrollment(Integer integrationId, String enrollmentName, String deviceProofToken) {
    this.integrationId = integrationId;
    this.enrollmentName = enrollmentName;
    this.setEnrollmentProofToken(deviceProofToken);
    this.createdAt = OffsetDateTime.now();
    this.status = EnrollmentStatus.CREATED;
    this.active = false;
    // Don't set authAttemptChallengeRequired here - let it be set explicitly by the caller
  }

  // Getters and Setters
  public Integer getEnrollmentId() {
    return enrollmentId;
  }

  public void setEnrollmentId(Integer enrollmentId) {
    this.enrollmentId = enrollmentId;
  }

  public Integer getIntegrationId() {
    return integrationId;
  }

  public void setIntegrationId(Integer integrationId) {
    this.integrationId = integrationId;
  }

  public String getEnrollmentName() {
    return enrollmentName;
  }

  public void setEnrollmentName(String enrollmentName) {
    this.enrollmentName = enrollmentName;
  }

  public EnrollmentStatus getStatus() {
    return status;
  }

  public void setStatus(EnrollmentStatus status) {
    this.status = status;
  }

  public Boolean getActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Integer getEnrollmentChallenge() {
    return enrollmentChallenge;
  }

  public void setEnrollmentChallenge(Integer enrollmentChallenge) {
    this.enrollmentChallenge = enrollmentChallenge;
  }

  /**
   * Gets the enrollment proof token, decrypting it if necessary.
   *
   * <p>When {@code ezkey.encryption.required=true}, plaintext-at-rest or decrypt failures fail
   * closed via {@link AtRestEncryptionAccess} (same policy as {@code ApiKey#getSecretKeyHash}).
   *
   * @return the plaintext enrollment proof token
   * @throws IllegalStateException when encryption is required but the value is not encrypted or
   *     cannot be decrypted
   */
  public String getEnrollmentProofToken() {
    if (enrollmentProofToken != null) {
      return enrollmentProofToken;
    }

    if (encryptedEnrollmentProofToken == null) {
      return null;
    }

    enrollmentProofToken =
        AtRestEncryptionAccess.resolveEncryptedField(
            getEncryptionOperations(),
            encryptedEnrollmentProofToken,
            "enrollment proof token (enrollmentId=" + enrollmentId + ")");
    return enrollmentProofToken;
  }

  public void setEnrollmentProofToken(String enrollmentProofToken) {
    this.enrollmentProofToken = enrollmentProofToken;
    this.enrollmentProofTokenHash = SensitiveDataHasher.sha256Hex(enrollmentProofToken);
    this.encryptedEnrollmentProofToken = enrollmentProofToken;
  }

  public Boolean getAuthAttemptChallengeRequired() {
    return authAttemptChallengeRequired;
  }

  public void setAuthAttemptChallengeRequired(Boolean authAttemptChallengeRequired) {
    this.authAttemptChallengeRequired = authAttemptChallengeRequired;
  }

  /**
   * Gets the integration private key, decrypting it if necessary.
   *
   * <p>Decrypts on first access and caches plaintext in the transient field. When {@code
   * ezkey.encryption.required=true}, plaintext-at-rest or decrypt failures fail closed via {@link
   * AtRestEncryptionAccess} (same policy as {@code ApiKey#getSecretKeyHash}).
   *
   * @return the decrypted integration private key, or plaintext when encryption is not required
   * @throws IllegalStateException when encryption is required but the value is not encrypted or
   *     cannot be decrypted
   */
  public String getIntegrationPrivateKey() {
    if (integrationPrivateKey != null) {
      return integrationPrivateKey;
    }

    if (encryptedIntegrationPrivateKey == null) {
      return null;
    }

    integrationPrivateKey =
        AtRestEncryptionAccess.resolveEncryptedField(
            getEncryptionOperations(),
            encryptedIntegrationPrivateKey,
            "integration private key (enrollmentId=" + enrollmentId + ")");
    return integrationPrivateKey;
  }

  /**
   * Sets the integration private key in plaintext.
   *
   * <p>This method stores the plaintext in both the transient field and the persisted field. The
   * {@link EncryptionEntityListener} will overwrite the persisted field with an encrypted value
   * before persistence when encryption is available. Storing plaintext in the persisted field
   * ensures the column is never null when the listener runs in contexts where the transient field
   * is not visible (e.g. merge flow, or {@code @PrePersist} when reflection does not see the
   * transient — the listener then falls back to the mapped column, same as enrollment proof token).
   * This matches the pattern used by {@link #setEnrollmentProofToken(String)}.
   *
   * @param integrationPrivateKey the plaintext integration private key to set
   */
  public void setIntegrationPrivateKey(String integrationPrivateKey) {
    this.integrationPrivateKey = integrationPrivateKey;
    this.encryptedIntegrationPrivateKey = integrationPrivateKey;
  }

  /**
   * Gets the encryption operations for decrypting private keys.
   *
   * <p>JPA entities cannot use dependency injection directly, so runtime encryption access goes
   * through a lightweight holder populated by the entity listener.
   *
   * @return the encryption operations, or null if not available
   */
  private static EncryptionOperations getEncryptionOperations() {
    return EncryptionOperationsHolder.get();
  }

  public String getIntegrationPublicKey() {
    return integrationPublicKey;
  }

  public void setIntegrationPublicKey(String integrationPublicKey) {
    this.integrationPublicKey = integrationPublicKey;
  }

  public String getDevicePublicKey() {
    return devicePublicKey;
  }

  public void setDevicePublicKey(String devicePublicKey) {
    this.devicePublicKey = devicePublicKey;
  }

  /**
   * Gets the SHA-256 hash of the device public key.
   *
   * @return the device public key hash (64 hex characters), or null if not set
   */
  public String getDevicePublicKeyHash() {
    return devicePublicKeyHash;
  }

  /**
   * Sets the SHA-256 hash of the device public key.
   *
   * <p>This method is typically called automatically when setting the device public key. The hash
   * should be computed from the plaintext device public key before encryption.
   *
   * @param devicePublicKeyHash the SHA-256 hash as hexadecimal string (64 characters)
   */
  public void setDevicePublicKeyHash(String devicePublicKeyHash) {
    this.devicePublicKeyHash = devicePublicKeyHash;
  }

  public String getEnrollmentProofTokenHash() {
    return enrollmentProofTokenHash;
  }

  public void setEnrollmentProofTokenHash(String enrollmentProofTokenHash) {
    this.enrollmentProofTokenHash = enrollmentProofTokenHash;
  }

  /**
   * Gets the encryption key id used to encrypt {@link #encryptedIntegrationPrivateKey}
   * (I-2026-0029).
   *
   * <p>No corresponding business setter: only {@code EncryptionEntityListener} and {@code
   * ReencryptionRecordCipher} write this field, via {@link #setEncryptionKeyId(String, Long)}.
   *
   * @return the encryption key id, or null when the value is stored as plaintext
   */
  public Long getIntegrationPrivateKeyEncryptionKeyId() {
    return integrationPrivateKeyEncryptionKeyId;
  }

  /**
   * Gets the encryption key id used to encrypt {@link #encryptedEnrollmentProofToken}
   * (I-2026-0029).
   *
   * <p>No corresponding business setter: only {@code EncryptionEntityListener} and {@code
   * ReencryptionRecordCipher} write this field, via {@link #setEncryptionKeyId(String, Long)}.
   *
   * @return the encryption key id, or null when the value is stored as plaintext
   */
  public Long getEnrollmentProofTokenEncryptionKeyId() {
    return enrollmentProofTokenEncryptionKeyId;
  }

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  /**
   * Gets the optional expiration timestamp for pending enrollment.
   *
   * @return expires_at or null if no expiration
   */
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }

  /**
   * Sets the optional expiration timestamp for pending enrollment.
   *
   * @param expiresAt the expiration timestamp, or null for no expiration
   */
  public void setExpiresAt(OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }

  /**
   * Returns true if this enrollment has an expiration set and it is in the past (now &gt;
   * expires_at). Used by bind/verify and the cleanup job. Null expires_at means never expired.
   *
   * @param now the current time (typically OffsetDateTime.now())
   * @return true if expired
   */
  public boolean isExpired(OffsetDateTime now) {
    return expiresAt != null && !now.isBefore(expiresAt);
  }

  public OffsetDateTime getVerifiedAt() {
    return verifiedAt;
  }

  public void setVerifiedAt(OffsetDateTime verifiedAt) {
    this.verifiedAt = verifiedAt;
  }

  public Integer getCreatedByAdminId() {
    return createdByAdminId;
  }

  public void setCreatedByAdminId(Integer createdByAdminId) {
    this.createdByAdminId = createdByAdminId;
  }

  public OffsetDateTime getLastUsedAt() {
    return lastUsedAt;
  }

  public void setLastUsedAt(OffsetDateTime lastUsedAt) {
    this.lastUsedAt = lastUsedAt;
  }

  public String getContactEmail() {
    return contactEmail;
  }

  public void setContactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
  }

  public String getContactPhoneNumber() {
    return contactPhoneNumber;
  }

  public void setContactPhoneNumber(String contactPhoneNumber) {
    this.contactPhoneNumber = contactPhoneNumber;
  }

  public String getUserIdentifier() {
    return userIdentifier;
  }

  public void setUserIdentifier(String userIdentifier) {
    this.userIdentifier = userIdentifier;
  }

  public DevicePrivateKeyStorageTier getDevicePrivateKeyStorageTier() {
    return devicePrivateKeyStorageTier;
  }

  public void setDevicePrivateKeyStorageTier(
      DevicePrivateKeyStorageTier devicePrivateKeyStorageTier) {
    this.devicePrivateKeyStorageTier = devicePrivateKeyStorageTier;
  }

  public OffsetDateTime getDeactivatedAt() {
    return deactivatedAt;
  }

  public void setDeactivatedAt(OffsetDateTime deactivatedAt) {
    this.deactivatedAt = deactivatedAt;
  }

  public Integer getDeactivatedByAdminId() {
    return deactivatedByAdminId;
  }

  public void setDeactivatedByAdminId(Integer deactivatedByAdminId) {
    this.deactivatedByAdminId = deactivatedByAdminId;
  }

  public OffsetDateTime getRevokedAt() {
    return revokedAt;
  }

  public void setRevokedAt(OffsetDateTime revokedAt) {
    this.revokedAt = revokedAt;
  }

  public Integer getRevokedByAdminId() {
    return revokedByAdminId;
  }

  public void setRevokedByAdminId(Integer revokedByAdminId) {
    this.revokedByAdminId = revokedByAdminId;
  }

  /**
   * Gets the optimistic lock version.
   *
   * @return the version
   */
  public Long getVersion() {
    return version;
  }

  /**
   * Sets the optimistic lock version (used by JPA; do not set manually).
   *
   * @param version the version
   */
  public void setVersion(Long version) {
    this.version = version;
  }

  // ===== Reencryptable Interface Implementation =====

  @Override
  public Map<String, String> getEncryptedFields() {
    Map<String, String> fields = new HashMap<>();
    if (encryptedIntegrationPrivateKey != null) {
      fields.put("integration_private_key", encryptedIntegrationPrivateKey);
    }
    if (encryptedEnrollmentProofToken != null) {
      fields.put("enrollment_proof_token", encryptedEnrollmentProofToken);
    }
    return fields;
  }

  @Override
  public void setEncryptedField(String columnName, String encryptedValue) {
    switch (columnName) {
      case "integration_private_key":
        this.encryptedIntegrationPrivateKey = encryptedValue;
        this.integrationPrivateKey = null; // Clear transient to force re-decryption
        break;
      case "enrollment_proof_token":
        this.encryptedEnrollmentProofToken = encryptedValue;
        this.enrollmentProofToken = null; // Clear transient to force re-decryption
        break;
      default:
        throw new IllegalArgumentException("Unknown encrypted field: " + columnName);
    }
  }

  @Override
  public void setEncryptionKeyId(String columnName, Long keyId) {
    switch (columnName) {
      case "integration_private_key":
        this.integrationPrivateKeyEncryptionKeyId = keyId;
        break;
      case "enrollment_proof_token":
        this.enrollmentProofTokenEncryptionKeyId = keyId;
        break;
      default:
        throw new IllegalArgumentException("Unknown encrypted field: " + columnName);
    }
  }

  @Override
  public Long getEntityId() {
    return enrollmentId != null ? Long.valueOf(enrollmentId) : null;
  }

  @Override
  public String getTableName() {
    return "ezkey_enrollment";
  }
}
