Args = --no-fallback \
       -H:+ReportExceptionStackTraces \
       -H:+AddAllCharsets \
       --enable-all-security-services \
       -H:IncludeResourceBundles=org.hibernate.validator.ValidationMessages \
       -H:+StaticExecutableWithDynamicLibC \
       -H:+RemoveSaturatedTypeFlows \
       --allow-incomplete-classpath \
       --report-unsupported-elements-at-runtime \
       -H:+AllowDeprecatedBuilderClassesOnImageClasspath \
       -H:+UnlockExperimentalVMOptions \
       -H:FallbackThreshold=0 \
       -H:+PrintAnalysisCallTree \
       --initialize-at-build-time=org.jboss.logging,org.hibernate.internal.HEMLogging,org.hibernate.internal.CoreLogging,org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl \
       --initialize-at-run-time=org.hibernate.sql.ast.tree.SqlAstTreeLogger