package org.ezkey.demo.device.service;

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import org.bouncycastle.asn1.ASN1Integer;
import org.bouncycastle.asn1.ASN1Sequence;
import org.bouncycastle.crypto.params.ECPublicKeyParameters;
import org.bouncycastle.crypto.signers.ECDSASigner;
import org.bouncycastle.crypto.util.PublicKeyFactory;
import org.ezkey.demo.device.service.DeviceCryptoService.ECP256DeviceKeyPair;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * Test to verify signature compatibility between DeviceCryptoService and SignatureService.
 *
 * <p>This test verifies that signatures generated by DeviceCryptoService can be validated by
 * SignatureService (ezkey-core), ensuring compatibility between the demo device and backend.
 *
 * @since 2025
 */
public class SignatureCompatibilityTest {

  private DeviceCryptoService deviceCryptoService;

  private ECP256DeviceKeyPair testKeyPair;

  @BeforeEach
  void setUp() {
    deviceCryptoService = new DeviceCryptoService();
    testKeyPair = deviceCryptoService.generateDeviceKeyPair();
  }

  /**
   * Simulates the SignatureService.validateSignature method from ezkey-core.
   *
   * <p>This method replicates the EC P-256 signature validation logic from SignatureService to
   * verify compatibility.
   */
  private boolean simulateCoreValidation(
      String data, String signatureBase64, String base64PublicKey) {
    try {
      byte[] keyBytes = Base64.getDecoder().decode(base64PublicKey);
      ECPublicKeyParameters publicKeyParams =
          (ECPublicKeyParameters) PublicKeyFactory.createKey(keyBytes);

      byte[] signatureBytes = Base64.getDecoder().decode(signatureBase64);
      BigInteger[] signature = decodeDERSignature(signatureBytes);
      if (signature == null) {
        return false;
      }

      ECDSASigner verifier = new ECDSASigner();
      verifier.init(false, publicKeyParams);

      byte[] dataBytes = data.getBytes(StandardCharsets.UTF_8);
      // Hash the data with SHA-256 before verification (ECDSA requires hashed input)
      java.security.MessageDigest digest = java.security.MessageDigest.getInstance("SHA-256");
      byte[] hash = digest.digest(dataBytes);

      return verifier.verifySignature(hash, signature[0], signature[1]);
    } catch (Exception e) {
      return false;
    }
  }

  /**
   * Decodes an ASN.1 DER encoded ECDSA signature to (r, s) components.
   *
   * @param derSignature ASN.1 DER encoded signature bytes
   * @return array containing [r, s] components, or null if decoding fails
   */
  private BigInteger[] decodeDERSignature(byte[] derSignature) {
    try {
      ASN1Sequence seq = ASN1Sequence.getInstance(derSignature);
      if (seq.size() != 2) {
        return null;
      }
      BigInteger r = ASN1Integer.getInstance(seq.getObjectAt(0)).getValue();
      BigInteger s = ASN1Integer.getInstance(seq.getObjectAt(1)).getValue();
      return new BigInteger[] {r, s};
    } catch (Exception e) {
      return null;
    }
  }

  @Test
  void testSignatureCompatibility() {
    // Test data
    String testData = "test-enrollment-proof-token-123";

    // Generate signature with device service
    String deviceSignature =
        deviceCryptoService.signStringToBase64(testData, testKeyPair.base64PrivateKey());

    // Log for debugging
    System.out.println("Test data: " + testData);
    System.out.println("Device signature: " + deviceSignature);
    System.out.println("Public key: " + testKeyPair.base64PublicKey());

    // Verify that the signature can be validated by the simulated core service
    String publicKeyBase64 = testKeyPair.base64PublicKey();
    boolean deviceSignatureValid =
        simulateCoreValidation(testData, deviceSignature, publicKeyBase64);

    System.out.println("Device signature valid: " + deviceSignatureValid);

    // Signature should be valid
    assertTrue(deviceSignatureValid, "Device signature should be validated by core service");
  }

  @Test
  void testCrossValidation() {
    // Test data
    String testData = "enrollment-proof-token-456";

    // Generate signature with device service
    String deviceSignature =
        deviceCryptoService.signStringToBase64(testData, testKeyPair.base64PrivateKey());

    // Validate with simulated core service
    String publicKeyBase64 = testKeyPair.base64PublicKey();
    boolean isValid = simulateCoreValidation(testData, deviceSignature, publicKeyBase64);

    System.out.println("Cross-validation test:");
    System.out.println("Test data: " + testData);
    System.out.println("Device signature: " + deviceSignature);
    System.out.println("Public key: " + publicKeyBase64);
    System.out.println("Validation result: " + isValid);

    assertTrue(isValid, "Device signature should be validated by core service");
  }
}
