/*
 * Ezkey - Open Source MFA/Passkey Alternative
 *
 * Copyright (c) 2025 Ezkey contributors
 * Licensed under the MIT License. See LICENSE file in the project root for full license information.
 *
 * Domain: AuthAttemptPendingResponse
 * Description: Domain response object containing pending authentication attempt data.
 */

package org.ezkey.authattempt.domain;

import java.time.OffsetDateTime;

/**
 * Domain response object containing pending authentication attempt data.
 *
 * <p>This domain object represents the response data returned by the service layer when a mobile
 * device requests pending authentication attempts. It contains the authentication challenge data
 * that must be processed and signed by the mobile device to complete the authentication flow.
 *
 * <p><b>Usage Context:</b> Returned by the AuthAttemptService when mobile devices successfully poll
 * for pending authentication requests. The service layer transforms internal authentication attempt
 * entities into this domain response object for consumption by API layers.
 *
 * <p><b>Authentication Flow:</b> When a pending authentication attempt exists, this response
 * provides the mobile device with the necessary challenge data and proof tokens that must be
 * cryptographically signed to prove user authentication and device ownership.
 *
 * <p><b>Security Model:</b> Contains cryptographically signed proof tokens that ensure
 * authentication challenge integrity. The integration-signed proof token prevents tampering and
 * validates that challenges originate from legitimate authentication requests within the system.
 *
 * <p><b>Challenge Processing:</b> When additional challenge validation is required, the mobile
 * device must provide supplementary authentication factors based on the challenge requirements
 * indicated in this response.
 *
 * <p><b>Project:</b> Ezkey - Open Source MFA/Passkey Alternative
 *
 * <p><b>License:</b> MIT
 *
 * @author Ezkey contributors
 * @since 2025
 * @see org.ezkey.authattempt.service.AuthAttemptService
 * @see org.ezkey.authattempt.domain.AuthAttemptPendingRequest
 * @see org.ezkey.authattempt.domain.entity.AuthAttempt
 */
public class AuthAttemptPendingResponse {

  /**
   * Unique identifier of the authentication attempt.
   *
   * <p>Used by the mobile device to reference this specific authentication attempt when submitting
   * a response. This ID links the challenge response back to the original authentication request
   * and ensures proper tracking throughout the authentication flow.
   */
  private Integer authAttemptId;

  /**
   * Integration proof token for this authentication attempt.
   *
   * <p>Contains the challenge data that needs to be cryptographically signed by the mobile device.
   * This token includes the authentication challenge information and contextual data required for
   * the device to generate a valid authentication response.
   */
  private String authAttemptProofToken;

  /**
   * Cryptographically signed proof token.
   *
   * <p>Provides integrity protection and prevents tampering with the challenge data. This signature
   * is generated by the integration system using its private key and can be verified by the mobile
   * device to ensure the authenticity and integrity of the authentication challenge.
   */
  private String authAttemptProofTokenSignedByIntegration;

  /**
   * Indicates whether additional challenge validation is required.
   *
   * <p>When true, the mobile device must provide additional challenge responses beyond the standard
   * authentication. This may include biometric verification, PIN entry, or other multi-factor
   * authentication requirements as determined by the authentication policy and risk assessment.
   */
  private Boolean authAttemptChallengeRequired;

  /**
   * Timestamp when the authentication attempt was created.
   *
   * <p>Required for foreign key reference to partitioned table. Used in audit logs to maintain
   * referential integrity with the partitioned ezkey_auth_attempt table.
   */
  private OffsetDateTime createdAt;

  /**
   * Optional short title for contextual authentication, displayed as the card header on the mobile
   * device. Null when no context was attached to the authentication attempt.
   */
  private String contextTitle;

  /**
   * Optional descriptive message providing the approver with full business context. Null when no
   * context was attached to the authentication attempt.
   */
  private String contextMessage;

  /**
   * When true, demo simulated MITM altered the pending JSON after signing; used only to enrich Auth
   * API audit logs (not exposed on the mobile JSON DTO).
   */
  private boolean demoMitmTamperApplied;

  /**
   * Operator-facing audit text for the demo MITM row (business narrative, no cryptographic values).
   * Set only when {@link #demoMitmTamperApplied} is true.
   */
  private String demoMitmPendingAuditNarrative;

  /**
   * Gets the unique identifier of the authentication attempt.
   *
   * @return the authentication attempt ID
   */
  public Integer getAuthAttemptId() {
    return authAttemptId;
  }

  /**
   * Sets the unique identifier of the authentication attempt.
   *
   * @param authAttemptId the authentication attempt ID to set
   */
  public void setAuthAttemptId(Integer authAttemptId) {
    this.authAttemptId = authAttemptId;
  }

  /**
   * Gets the integration proof token containing challenge data.
   *
   * @return the authentication attempt proof token
   */
  public String getAuthAttemptProofToken() {
    return authAttemptProofToken;
  }

  /**
   * Sets the integration proof token containing challenge data.
   *
   * @param authAttemptProofToken the authentication attempt proof token to set
   */
  public void setAuthAttemptProofToken(String authAttemptProofToken) {
    this.authAttemptProofToken = authAttemptProofToken;
  }

  /**
   * Gets the cryptographically signed proof token.
   *
   * @return the signed authentication attempt proof token
   */
  public String getAuthAttemptProofTokenSignedByIntegration() {
    return authAttemptProofTokenSignedByIntegration;
  }

  /**
   * Sets the cryptographically signed proof token.
   *
   * @param authAttemptProofTokenSignedByIntegration the signed proof token to set
   */
  public void setAuthAttemptProofTokenSignedByIntegration(
      String authAttemptProofTokenSignedByIntegration) {
    this.authAttemptProofTokenSignedByIntegration = authAttemptProofTokenSignedByIntegration;
  }

  /**
   * Gets the additional challenge requirement flag.
   *
   * @return true if additional challenge validation is required, false otherwise
   */
  public Boolean getAuthAttemptChallengeRequired() {
    return authAttemptChallengeRequired;
  }

  /**
   * Sets the additional challenge requirement flag.
   *
   * @param authAttemptChallengeRequired true if additional challenge validation is required
   */
  public void setAuthAttemptChallengeRequired(Boolean authAttemptChallengeRequired) {
    this.authAttemptChallengeRequired = authAttemptChallengeRequired;
  }

  /**
   * Gets the creation timestamp of the authentication attempt.
   *
   * @return the creation timestamp
   */
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  /**
   * Sets the creation timestamp of the authentication attempt.
   *
   * @param createdAt the creation timestamp to set
   */
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  /**
   * Gets the optional short context title.
   *
   * @return the context title, or null if not provided
   */
  public String getContextTitle() {
    return contextTitle;
  }

  /**
   * Sets the optional short context title.
   *
   * @param contextTitle the context title to set
   */
  public void setContextTitle(String contextTitle) {
    this.contextTitle = contextTitle;
  }

  /**
   * Gets the optional descriptive context message.
   *
   * @return the context message, or null if not provided
   */
  public String getContextMessage() {
    return contextMessage;
  }

  /**
   * Sets the optional descriptive context message.
   *
   * @param contextMessage the context message to set
   */
  public void setContextMessage(String contextMessage) {
    this.contextMessage = contextMessage;
  }

  /**
   * Whether demo MITM tampering was applied to the pending JSON body after signing.
   *
   * @return true when the simulated tamper ran (audit narrative only)
   */
  public boolean isDemoMitmTamperApplied() {
    return demoMitmTamperApplied;
  }

  /**
   * Sets whether demo MITM tampering was applied.
   *
   * @param demoMitmTamperApplied true when tamper ran
   */
  public void setDemoMitmTamperApplied(boolean demoMitmTamperApplied) {
    this.demoMitmTamperApplied = demoMitmTamperApplied;
  }

  /**
   * Audit narrative for the demo MITM scenario (plain language for operators).
   *
   * @return narrative text, or null if not applicable
   */
  public String getDemoMitmPendingAuditNarrative() {
    return demoMitmPendingAuditNarrative;
  }

  /**
   * Sets the audit narrative for the demo MITM scenario.
   *
   * @param demoMitmPendingAuditNarrative operator-facing text for {@code eventDetails}
   */
  public void setDemoMitmPendingAuditNarrative(String demoMitmPendingAuditNarrative) {
    this.demoMitmPendingAuditNarrative = demoMitmPendingAuditNarrative;
  }
}
