-- Core integration table: represents applications/systems protected by Ezkey MFA
-- Each integration corresponds to a distinct service that requires multi-factor authentication
-- Examples: admin portals, e-commerce sites, banking applications, etc.
CREATE TABLE ezkey_integration (
    integration_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    integration_logo VARCHAR(255),  -- URL or path to integration's logo image for display in mobile app and admin interfaces
    integration_active BOOLEAN DEFAULT TRUE NOT NULL,  -- Controls whether integration accepts new enrollments and auth attempts (operational flag)
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL  -- Audit timestamp with timezone for integration creation (immutable)
);

-- Add table-level comment
COMMENT ON TABLE ezkey_integration IS 'Core integration table representing applications or systems protected by Ezkey MFA. Each integration is a distinct service requiring multi-factor authentication (e.g., admin portal, e-commerce site). Integrations can have multiple enrollments and support internationalization via ezkey_integration_i18n.';

-- Add column-level comments
COMMENT ON COLUMN ezkey_integration.integration_id IS 'Primary key - unique identifier for the integration, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_integration.integration_logo IS 'URL or file path to integration logo image displayed in mobile app and admin interfaces - supports branding for user recognition';
COMMENT ON COLUMN ezkey_integration.integration_active IS 'Operational control flag - when FALSE, prevents new enrollments and authentication attempts for this integration while preserving existing data';
COMMENT ON COLUMN ezkey_integration.created_at IS 'Audit timestamp with timezone recording when integration was created - immutable value used for reporting and compliance tracking';

-- Internationalization table: provides multi-language support for integration names and descriptions
-- Allows integrations to display localized content in different languages for global deployment
-- Critical for user experience in mobile app and admin interfaces
CREATE TABLE ezkey_integration_i18n (
    integration_i18n_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    integration_id INT NOT NULL REFERENCES ezkey_integration(integration_id) ON DELETE CASCADE,  -- Parent integration - cascading delete removes all i18n entries
    integration_i18n_lang VARCHAR(8) NOT NULL,  -- Language code following ISO 639-1 standard (e.g., 'en', 'fr', 'en-US')
    integration_i18n_name VARCHAR(255) NOT NULL,  -- Localized integration name displayed to users in mobile app and admin interfaces
    integration_i18n_description VARCHAR(255) NOT NULL,  -- Localized description providing context about the integration's purpose
    CONSTRAINT unique_integration_lang UNIQUE(integration_i18n_id, integration_i18n_lang)  -- Prevents duplicate language entries per integration
);

-- Add table-level comment
COMMENT ON TABLE ezkey_integration_i18n IS 'Internationalization support for integrations providing multi-language names and descriptions. Each integration can have multiple language entries for global deployment. Used by mobile app and admin interfaces to display localized content to users.';

-- Add column-level comments
COMMENT ON COLUMN ezkey_integration_i18n.integration_i18n_id IS 'Primary key - unique identifier for this i18n entry, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_integration_i18n.integration_id IS 'Foreign key to parent integration - CASCADE DELETE ensures cleanup when integration is removed';
COMMENT ON COLUMN ezkey_integration_i18n.integration_i18n_lang IS 'Language code following ISO 639-1 standard (e.g., en, fr, es) or locale format (en-US) - determines which language this entry represents';
COMMENT ON COLUMN ezkey_integration_i18n.integration_i18n_name IS 'Localized integration name displayed to end users in mobile app enrollment and authentication flows';
COMMENT ON COLUMN ezkey_integration_i18n.integration_i18n_description IS 'Localized description explaining the integration purpose - helps users identify which service they are authenticating to';

-- Device enrollment table: represents the binding between an integration, user, and their mobile device
-- Each enrollment establishes a cryptographic relationship using Ed25519 key pairs
-- Contains state tracking for enrollment lifecycle and authentication configuration
-- Security-critical table containing cryptographic keys and proof tokens
-- NOTE: Migration V15 updates comments to reflect Ed25519 instead of RSA-2048
CREATE TABLE ezkey_enrollment (
    enrollment_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    integration_id INT NOT NULL REFERENCES ezkey_integration(integration_id),  -- Parent integration this enrollment belongs to
    enrollment_name VARCHAR(64) NOT NULL,  -- Human-readable name for this enrollment (e.g., "John's iPhone", "Marketing Team Device")
    enrollment_status VARCHAR(20) NOT NULL DEFAULT 'CREATED' CHECK (enrollment_status IN ('CREATED', 'BOUND', 'VERIFIED', 'INVALID', 'REVOKED')),  -- Enrollment lifecycle status tracking
    enrollment_active BOOLEAN NOT NULL DEFAULT FALSE,  -- Operational flag controlling if this enrollment can be used for authentication
    enrollment_challenge INT DEFAULT NULL,  -- Optional numeric challenge for additional security during enrollment binding
    enrollment_proof_token TEXT NOT NULL,  -- Unique cryptographic token proving device received enrollment details (one-time use)
    auth_attempt_challenge_required BOOLEAN NOT NULL DEFAULT FALSE,  -- Configuration flag - if TRUE, authentication attempts require numeric challenge entry
    integration_private_key TEXT NOT NULL,  -- Ed25519 private key seed for integration-side cryptographic operations (32 bytes raw, Base64 encoded, encrypted at rest)
    integration_public_key TEXT NOT NULL,  -- Ed25519 public key for integration-side verification (32 bytes raw, Base64 encoded, safe to expose)
    device_public_key TEXT,  -- Ed25519 public key from mobile device for signature verification (32 bytes raw, Base64 encoded, set during binding)
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL  -- Audit timestamp with timezone for enrollment creation (immutable)
);

-- Add table-level comment
-- NOTE: Migration V15 updates this comment to reflect Ed25519 instead of RSA-2048
COMMENT ON TABLE ezkey_enrollment IS 'Device enrollment table establishing cryptographic binding between integration, user, and mobile device. Contains Ed25519 key pairs and tracks enrollment lifecycle from creation through verification. Each enrollment enables authentication attempts and includes security configuration like challenge requirements.';

-- Add column-level comments
COMMENT ON COLUMN ezkey_enrollment.enrollment_id IS 'Primary key - unique identifier for this enrollment, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_enrollment.integration_id IS 'Foreign key to parent integration - determines which application/service this enrollment provides access to';
COMMENT ON COLUMN ezkey_enrollment.enrollment_name IS 'Human-readable identifier for this enrollment displayed in admin interfaces (e.g., "John iPhone", "Marketing Team Device") - helps operators identify specific enrollments';
COMMENT ON COLUMN ezkey_enrollment.enrollment_status IS 'Enrollment lifecycle status - CREATED (initial), BOUND (device claimed), VERIFIED (cryptographically verified), INVALID (verification failed), REVOKED (permanently revoked by admin) - tracks enrollment progress through complete lifecycle';
COMMENT ON COLUMN ezkey_enrollment.enrollment_active IS 'Operational control flag - FALSE disables authentication attempts for this enrollment while preserving enrollment data - used for security investigations and administrative control';
COMMENT ON COLUMN ezkey_enrollment.enrollment_challenge IS 'Optional numeric challenge (4-6 digits) required during device binding for additional security - displayed in QR code or SMS';
COMMENT ON COLUMN ezkey_enrollment.enrollment_proof_token IS 'One-time cryptographic token proving device successfully received enrollment details - used during binding verification process';
COMMENT ON COLUMN ezkey_enrollment.auth_attempt_challenge_required IS 'Configuration flag - when TRUE, all authentication attempts for this enrollment require user to enter numeric challenge on mobile device';
-- NOTE: Migration V15 updates these comments to reflect Ed25519 instead of RSA-2048
COMMENT ON COLUMN ezkey_enrollment.integration_private_key IS 'Ed25519 private key seed for integration-side cryptographic operations (32 bytes raw, Base64 encoded) - SENSITIVE DATA requiring encryption at rest and secure handling. Used by backend to sign authAttemptProofToken for mutual authentication.';
COMMENT ON COLUMN ezkey_enrollment.integration_public_key IS 'Ed25519 public key for integration-side operations (32 bytes raw, Base64 encoded) - corresponding public key for integration_private_key, safe to expose. Used by mobile app to verify backend signatures (authAttemptProofTokenSignedByIntegration).';
COMMENT ON COLUMN ezkey_enrollment.device_public_key IS 'Ed25519 public key from mobile device (32 bytes raw, Base64 encoded) - used to verify signatures from device during authentication attempts, set during binding process';
COMMENT ON COLUMN ezkey_enrollment.created_at IS 'Audit timestamp with timezone recording when enrollment was created - immutable value used for compliance tracking and enrollment lifecycle monitoring';

-- Authentication attempt table: represents individual MFA authentication requests and their lifecycle
-- Each auth attempt uses one-time proof tokens for replay attack prevention
-- Tracks complete authentication flow from creation through device response
-- Security-critical table with automatic expiration and state tracking
CREATE TABLE ezkey_auth_attempt (
    auth_attempt_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    enrollment_id INT NOT NULL REFERENCES ezkey_enrollment(enrollment_id),  -- Parent enrollment that will handle this authentication request
    auth_attempt_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (auth_attempt_status IN ('PENDING', 'READ', 'INVALID', 'REJECTED', 'ACCEPTED', 'EXPIRED')),  -- Authentication attempt lifecycle status tracking
    auth_attempt_challenge INT,  -- Optional numeric challenge (4-6 digits) that user must enter on mobile device for additional security
    auth_attempt_proof_token TEXT NOT NULL,  -- Unique one-time token for this auth attempt - prevents replay attacks and ensures request authenticity
    device_proof_token TEXT,  -- Token generated by mobile device proving it received the auth_attempt_proof_token (cryptographic proof of possession)
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,  -- Audit timestamp with timezone for auth attempt creation (immutable)
    expires_at TIMESTAMPTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP + INTERVAL '120 seconds')  -- Automatic expiration time with timezone - auth attempts expire after 2 minutes for security
);

-- Add table-level comment
COMMENT ON TABLE ezkey_auth_attempt IS 'Authentication attempt table tracking individual MFA requests from creation through completion. Uses one-time proof tokens to prevent replay attacks and includes automatic expiration for security. Each attempt represents a single authentication event requiring mobile device verification.';

-- Add column-level comments
COMMENT ON COLUMN ezkey_auth_attempt.auth_attempt_id IS 'Primary key - unique identifier for this authentication attempt, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_auth_attempt.enrollment_id IS 'Foreign key to enrollment that will handle this authentication - determines which device/user will receive the auth request';
COMMENT ON COLUMN ezkey_auth_attempt.auth_attempt_status IS 'Authentication attempt lifecycle status - PENDING (created), READ (device claimed), INVALID (crypto validation failed), REJECTED (user denied), ACCEPTED (user approved), EXPIRED (superseded or timeout) - tracks complete authentication flow';
COMMENT ON COLUMN ezkey_auth_attempt.auth_attempt_challenge IS 'Optional numeric challenge (4-6 digits) displayed to user on mobile device for additional security - required when enrollment.auth_attempt_challenge_required is TRUE';
COMMENT ON COLUMN ezkey_auth_attempt.auth_attempt_proof_token IS 'One-time cryptographic token unique to this auth attempt - prevents replay attacks and ensures request authenticity (never reused)';
COMMENT ON COLUMN ezkey_auth_attempt.device_proof_token IS 'Token generated by mobile device proving it received the auth_attempt_proof_token - cryptographic proof that device has access to the legitimate auth attempt';
COMMENT ON COLUMN ezkey_auth_attempt.created_at IS 'Audit timestamp with timezone recording when auth attempt was created - immutable value used for compliance and performance monitoring';
COMMENT ON COLUMN ezkey_auth_attempt.expires_at IS 'Automatic expiration timestamp with timezone (default 120 seconds) - expired attempts are invalid for security and should be cleaned up by maintenance jobs';

-- Index to optimize queries for finding newer authentication attempts by enrollment
CREATE INDEX idx_auth_attempt_enrollment_created ON ezkey_auth_attempt(enrollment_id, created_at DESC);
