-- Core integration table: represents applications/systems protected by Ezkey MFA
-- Each integration corresponds to a distinct service that requires multi-factor authentication
-- Examples: admin portals, e-commerce sites, banking applications, etc.
CREATE TABLE ezkey_integration (
    integration_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    integration_logo VARCHAR(255),  -- URL or path to integration's logo image for display in mobile app and admin interfaces
    integration_lifecycle_status VARCHAR(16) DEFAULT 'ACTIVE' NOT NULL
        CHECK (integration_lifecycle_status IN ('ACTIVE', 'INACTIVE', 'RETIRED')),  -- Explicit lifecycle state for integrations
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL  -- Audit timestamp with timezone for integration creation (immutable)
);

-- Add table-level comment
COMMENT ON TABLE ezkey_integration IS 'Core integration table representing applications or systems protected by Ezkey MFA. Each integration is a distinct service requiring multi-factor authentication (e.g., admin portal, e-commerce site). Integrations can have multiple enrollments. (Historical note: V1 also created ezkey_integration_i18n; V7 flattened name/description onto this table and dropped that child table.)';

-- Add column-level comments
COMMENT ON COLUMN ezkey_integration.integration_id IS 'Primary key - unique identifier for the integration, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_integration.integration_logo IS 'URL or file path to integration logo image displayed in mobile app and admin interfaces - supports branding for user recognition';
COMMENT ON COLUMN ezkey_integration.integration_lifecycle_status IS 'Explicit lifecycle state for the integration: ACTIVE, INACTIVE, or RETIRED. ACTIVE and INACTIVE remain operational states; RETIRED permanently removes the integration from normal operations while preserving historical data.';
COMMENT ON COLUMN ezkey_integration.created_at IS 'Audit timestamp with timezone recording when integration was created - immutable value used for reporting and compliance tracking';

-- Internationalization table: provides multi-language support for integration names and descriptions
-- Allows integrations to display localized content in different languages for global deployment
-- Critical for user experience in mobile app and admin interfaces
CREATE TABLE ezkey_integration_i18n (
    integration_i18n_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    integration_id INT NOT NULL REFERENCES ezkey_integration(integration_id) ON DELETE CASCADE,  -- Parent integration - cascading delete removes all i18n entries
    integration_i18n_lang VARCHAR(8) NOT NULL,  -- Language code following ISO 639-1 standard (e.g., 'en', 'fr', 'en-US')
    integration_i18n_name VARCHAR(255) NOT NULL,  -- Localized integration name displayed to users in mobile app and admin interfaces
    integration_i18n_description VARCHAR(255) NOT NULL,  -- Localized description providing context about the integration's purpose
    CONSTRAINT unique_integration_lang UNIQUE(integration_i18n_id, integration_i18n_lang)  -- Prevents duplicate language entries per integration
);

-- Add table-level comment
COMMENT ON TABLE ezkey_integration_i18n IS 'Internationalization support for integrations providing multi-language names and descriptions. Each integration can have multiple language entries for global deployment. Used by mobile app and admin interfaces to display localized content to users.';

-- Add column-level comments
COMMENT ON COLUMN ezkey_integration_i18n.integration_i18n_id IS 'Primary key - unique identifier for this i18n entry, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_integration_i18n.integration_id IS 'Foreign key to parent integration - CASCADE DELETE ensures cleanup when integration is removed';
COMMENT ON COLUMN ezkey_integration_i18n.integration_i18n_lang IS 'Language code following ISO 639-1 standard (e.g., en, fr, es) or locale format (en-US) - determines which language this entry represents';
COMMENT ON COLUMN ezkey_integration_i18n.integration_i18n_name IS 'Localized integration name displayed to end users in mobile app enrollment and authentication flows';
COMMENT ON COLUMN ezkey_integration_i18n.integration_i18n_description IS 'Localized description explaining the integration purpose - helps users identify which service they are authenticating to';

-- Device enrollment table: represents the binding between an integration, user, and their mobile device
-- Each enrollment establishes a cryptographic relationship using Ed25519 key pairs
-- Contains state tracking for enrollment lifecycle and authentication configuration
-- Security-critical table containing cryptographic keys and proof tokens
-- NOTE: Migration V15 updates comments to reflect Ed25519 instead of RSA-2048
CREATE TABLE ezkey_enrollment (
    enrollment_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    integration_id INT NOT NULL REFERENCES ezkey_integration(integration_id),  -- Parent integration this enrollment belongs to
    enrollment_name VARCHAR(64) NOT NULL,  -- Human-readable name for this enrollment (e.g., "John's iPhone", "Marketing Team Device")
    enrollment_status VARCHAR(20) NOT NULL DEFAULT 'CREATED' CHECK (enrollment_status IN ('CREATED', 'BOUND', 'VERIFIED', 'INVALID', 'REVOKED')),  -- Enrollment lifecycle status tracking
    enrollment_active BOOLEAN NOT NULL DEFAULT FALSE,  -- Operational flag controlling if this enrollment can be used for authentication
    enrollment_challenge INT DEFAULT NULL,  -- Optional numeric challenge for additional security during enrollment binding
    enrollment_proof_token TEXT NOT NULL,  -- Unique cryptographic token proving device received enrollment details (one-time use)
    auth_attempt_challenge_required BOOLEAN NOT NULL DEFAULT FALSE,  -- Configuration flag - if TRUE, authentication attempts require numeric challenge entry
    integration_private_key TEXT NOT NULL,  -- Ed25519 private key seed for integration-side cryptographic operations (32 bytes raw, Base64 encoded, encrypted at rest)
    integration_public_key TEXT NOT NULL,  -- Ed25519 public key for integration-side verification (32 bytes raw, Base64 encoded, safe to expose)
    device_public_key TEXT,  -- Ed25519 public key from mobile device for signature verification (32 bytes raw, Base64 encoded, set during binding)
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL  -- Audit timestamp with timezone for enrollment creation (immutable)
);

-- Add table-level comment
-- NOTE: Migration V15 updates this comment to reflect Ed25519 instead of RSA-2048
COMMENT ON TABLE ezkey_enrollment IS 'Device enrollment table establishing cryptographic binding between integration, user, and mobile device. Contains Ed25519 key pairs and tracks enrollment lifecycle from creation through verification. Each enrollment enables authentication attempts and includes security configuration like challenge requirements.';

-- Add column-level comments
COMMENT ON COLUMN ezkey_enrollment.enrollment_id IS 'Primary key - unique identifier for this enrollment, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_enrollment.integration_id IS 'Foreign key to parent integration - determines which application/service this enrollment provides access to';
COMMENT ON COLUMN ezkey_enrollment.enrollment_name IS 'Human-readable identifier for this enrollment displayed in admin interfaces (e.g., "John iPhone", "Marketing Team Device") - helps operators identify specific enrollments';
COMMENT ON COLUMN ezkey_enrollment.enrollment_status IS 'Enrollment lifecycle status - CREATED (initial), BOUND (device claimed), VERIFIED (cryptographically verified), INVALID (verification failed), REVOKED (permanently revoked by admin) - tracks enrollment progress through complete lifecycle';
COMMENT ON COLUMN ezkey_enrollment.enrollment_active IS 'Operational control flag - FALSE disables authentication attempts for this enrollment while preserving enrollment data - used for security investigations and administrative control';
COMMENT ON COLUMN ezkey_enrollment.enrollment_challenge IS 'Optional numeric challenge (4-6 digits) required during device binding for additional security - displayed in QR code or SMS';
COMMENT ON COLUMN ezkey_enrollment.enrollment_proof_token IS 'One-time cryptographic token proving device successfully received enrollment details - used during binding verification process';
COMMENT ON COLUMN ezkey_enrollment.auth_attempt_challenge_required IS 'Configuration flag - when TRUE, all authentication attempts for this enrollment require user to enter numeric challenge on mobile device';
-- NOTE: Migration V15 updates these comments to reflect Ed25519 instead of RSA-2048
COMMENT ON COLUMN ezkey_enrollment.integration_private_key IS 'Ed25519 private key seed for integration-side cryptographic operations (32 bytes raw, Base64 encoded) - SENSITIVE DATA requiring encryption at rest and secure handling. Used by backend to sign authAttemptProofToken for mutual authentication.';
COMMENT ON COLUMN ezkey_enrollment.integration_public_key IS 'Ed25519 public key for integration-side operations (32 bytes raw, Base64 encoded) - corresponding public key for integration_private_key, safe to expose. Used by mobile app to verify backend signatures (authAttemptProofTokenSignedByIntegration).';
COMMENT ON COLUMN ezkey_enrollment.device_public_key IS 'Ed25519 public key from mobile device (32 bytes raw, Base64 encoded) - used to verify signatures from device during authentication attempts, set during binding process';
COMMENT ON COLUMN ezkey_enrollment.created_at IS 'Audit timestamp with timezone recording when enrollment was created - immutable value used for compliance tracking and enrollment lifecycle monitoring';

-- Authentication attempt table: represents individual MFA authentication requests and their lifecycle
-- Each auth attempt uses one-time proof tokens for replay attack prevention
-- Tracks complete authentication flow from creation through device response
-- Security-critical table with automatic expiration and state tracking
CREATE TABLE ezkey_auth_attempt (
    auth_attempt_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    enrollment_id INT NOT NULL REFERENCES ezkey_enrollment(enrollment_id),  -- Parent enrollment that will handle this authentication request
    auth_attempt_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (auth_attempt_status IN ('PENDING', 'READ', 'INVALID', 'REJECTED', 'ACCEPTED', 'EXPIRED')),  -- Authentication attempt lifecycle status tracking
    auth_attempt_challenge INT,  -- Optional numeric challenge (4-6 digits) that user must enter on mobile device for additional security
    auth_attempt_proof_token TEXT NOT NULL,  -- Unique one-time token for this auth attempt - prevents replay attacks and ensures request authenticity
    device_proof_token TEXT,  -- Token generated by mobile device proving it received the auth_attempt_proof_token (cryptographic proof of possession)
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,  -- Audit timestamp with timezone for auth attempt creation (immutable)
    expires_at TIMESTAMPTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP + INTERVAL '120 seconds')  -- Automatic expiration time with timezone - auth attempts expire after 2 minutes for security
);

-- Add table-level comment
COMMENT ON TABLE ezkey_auth_attempt IS 'Authentication attempt table tracking individual MFA requests from creation through completion. Uses one-time proof tokens to prevent replay attacks and includes automatic expiration for security. Each attempt represents a single authentication event requiring mobile device verification.';

-- Add column-level comments
COMMENT ON COLUMN ezkey_auth_attempt.auth_attempt_id IS 'Primary key - unique identifier for this authentication attempt, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_auth_attempt.enrollment_id IS 'Foreign key to enrollment that will handle this authentication - determines which device/user will receive the auth request';
COMMENT ON COLUMN ezkey_auth_attempt.auth_attempt_status IS 'Authentication attempt lifecycle status - PENDING (created), READ (device claimed), INVALID (crypto validation failed), REJECTED (user denied), ACCEPTED (user approved), EXPIRED (superseded or timeout) - tracks complete authentication flow';
COMMENT ON COLUMN ezkey_auth_attempt.auth_attempt_challenge IS 'Optional numeric challenge (4-6 digits) displayed to user on mobile device for additional security - required when enrollment.auth_attempt_challenge_required is TRUE';
COMMENT ON COLUMN ezkey_auth_attempt.auth_attempt_proof_token IS 'One-time cryptographic token unique to this auth attempt - prevents replay attacks and ensures request authenticity (never reused)';
COMMENT ON COLUMN ezkey_auth_attempt.device_proof_token IS 'Token generated by mobile device proving it received the auth_attempt_proof_token - cryptographic proof that device has access to the legitimate auth attempt';
COMMENT ON COLUMN ezkey_auth_attempt.created_at IS 'Audit timestamp with timezone recording when auth attempt was created - immutable value used for compliance and performance monitoring';
COMMENT ON COLUMN ezkey_auth_attempt.expires_at IS 'Automatic expiration timestamp with timezone (default 120 seconds) - expired attempts are invalid for security and should be cleaned up by maintenance jobs';

-- Index to optimize queries for finding newer authentication attempts by enrollment
CREATE INDEX idx_auth_attempt_enrollment_created ON ezkey_auth_attempt(enrollment_id, created_at DESC);
-- ============================================================================
-- Ezkey Migration V2: Add Multi-Tenant Security Support
-- ============================================================================
-- Description: Adds multi-tenant isolation and administrative security features
--              without modifying existing tables from V1.
-- 
-- Context: This migration introduces tenant-based isolation and admin hierarchy
--          while preserving all existing functionality from V1.
--
-- Author: Ezkey contributors
-- Date: 2025-10-13
-- ============================================================================

-- ============================================================================
-- STEP 1: Create Tenant Table
-- ============================================================================

-- Tenant table for multi-tenant isolation
CREATE TABLE ezkey_tenant (
    tenant_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tenant_name VARCHAR(100) NOT NULL UNIQUE,
    tenant_description TEXT,
    created_by_admin_id INT, -- Will be added after ezkey_admin creation
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL
);

-- Add table-level comment
COMMENT ON TABLE ezkey_tenant IS
'Multi-tenant isolation table. Each tenant represents a distinct organization or customer using Ezkey. Provides data isolation and administrative boundaries.';

-- Add column-level comments
COMMENT ON COLUMN ezkey_tenant.tenant_id IS 'Primary key - unique identifier for the tenant, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_tenant.tenant_name IS 'Unique tenant name used for identification and display purposes';
COMMENT ON COLUMN ezkey_tenant.tenant_description IS 'Optional description providing context about the tenant organization or purpose';
COMMENT ON COLUMN ezkey_tenant.created_by_admin_id IS 'Foreign key to admin who created this tenant - will be populated after admin table creation';
COMMENT ON COLUMN ezkey_tenant.created_at IS 'Audit timestamp with timezone recording when tenant was created - immutable value for compliance tracking';
COMMENT ON COLUMN ezkey_tenant.active IS 'Operational control flag - when FALSE, disables tenant operations while preserving data';

-- ============================================================================
-- STEP 2: Create Admin Table
-- ============================================================================

-- Administrative users table with multi-tenant support
CREATE TABLE ezkey_admin (
    admin_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    admin_type VARCHAR(20) NOT NULL CHECK (admin_type IN ('GLOBAL_ADMIN', 'TENANT_ADMIN', 'INTEGRATION_ADMIN')),
    tenant_id INT REFERENCES ezkey_tenant(tenant_id),
    integration_id INT REFERENCES ezkey_integration(integration_id),
    mfa_enabled BOOLEAN DEFAULT TRUE NOT NULL,
    mfa_required BOOLEAN DEFAULT TRUE NOT NULL,
    enrollment_id INT REFERENCES ezkey_enrollment(enrollment_id),
    password_change_required BOOLEAN DEFAULT FALSE NOT NULL,
    created_by_admin_id INT REFERENCES ezkey_admin(admin_id),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_login_at TIMESTAMPTZ,
    last_password_change TIMESTAMPTZ,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    
    -- Admin hierarchy constraints
    CONSTRAINT check_admin_hierarchy CHECK (
        (admin_type = 'GLOBAL_ADMIN' AND tenant_id IS NULL AND integration_id IS NULL) OR
        (admin_type = 'TENANT_ADMIN' AND tenant_id IS NOT NULL AND integration_id IS NULL) OR
        (admin_type = 'INTEGRATION_ADMIN' AND tenant_id IS NOT NULL AND integration_id IS NOT NULL)
    )
);

-- Add table-level comment
COMMENT ON TABLE ezkey_admin IS
'Administrative users with multi-tenant support and hierarchical access control. Supports password-based authentication with MFA integration.';

-- Add column-level comments
COMMENT ON COLUMN ezkey_admin.admin_id IS 'Primary key - unique identifier for the admin user, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_admin.username IS 'Unique username for admin authentication and identification';
COMMENT ON COLUMN ezkey_admin.password_hash IS 'BCrypt-hashed password for admin authentication - will be removed in V3 passwordless migration';
COMMENT ON COLUMN ezkey_admin.admin_type IS 'Administrator type: GLOBAL_ADMIN (system-wide), TENANT_ADMIN (tenant-scoped), or INTEGRATION_ADMIN (integration-scoped)';
COMMENT ON COLUMN ezkey_admin.tenant_id IS 'Foreign key to tenant - determines administrative scope for TENANT_ADMIN and INTEGRATION_ADMIN types';
COMMENT ON COLUMN ezkey_admin.integration_id IS 'Foreign key to integration - determines administrative scope for INTEGRATION_ADMIN type only';
COMMENT ON COLUMN ezkey_admin.mfa_enabled IS 'Flag indicating if MFA is enabled for this admin - will be removed in V3 passwordless migration';
COMMENT ON COLUMN ezkey_admin.mfa_required IS 'Flag indicating if MFA is required for this admin - will be removed in V3 passwordless migration';
COMMENT ON COLUMN ezkey_admin.enrollment_id IS 'Foreign key to the administrator enrollment - reuses the same Ezkey enrollment identifier as all other flows.';
COMMENT ON COLUMN ezkey_admin.password_change_required IS 'Flag indicating if admin must change password on next login - will be removed in V3 passwordless migration';
COMMENT ON COLUMN ezkey_admin.created_by_admin_id IS 'Foreign key to admin who created this admin user - supports audit trail';
COMMENT ON COLUMN ezkey_admin.created_at IS 'Audit timestamp with timezone recording when admin was created - immutable value for compliance tracking';
COMMENT ON COLUMN ezkey_admin.last_login_at IS 'Timestamp with timezone of last successful login - used for security monitoring and session management';
COMMENT ON COLUMN ezkey_admin.last_password_change IS 'Timestamp with timezone of last password change - will be removed in V3 passwordless migration';
COMMENT ON COLUMN ezkey_admin.active IS 'Operational control flag - when FALSE, disables admin access while preserving data';

-- ============================================================================
-- STEP 3: Create Admin Tokens Table
-- ============================================================================

-- Bearer tokens for admin API authentication
CREATE TABLE ezkey_admin_tokens (
    token_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    bearer_token VARCHAR(255) NOT NULL UNIQUE,
    admin_id INT NOT NULL REFERENCES ezkey_admin(admin_id),
    admin_type VARCHAR(20) NOT NULL,
    tenant_id INT REFERENCES ezkey_tenant(tenant_id),
    integration_id INT REFERENCES ezkey_integration(integration_id),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    last_used_at TIMESTAMPTZ,
    ip_address VARCHAR(45),
    user_agent TEXT,
    active BOOLEAN DEFAULT TRUE NOT NULL
);

-- Add table-level comment
COMMENT ON TABLE ezkey_admin_tokens IS
'Bearer tokens for admin API authentication. Provides session management and access control for administrative operations.';

-- Add column-level comments
COMMENT ON COLUMN ezkey_admin_tokens.token_id IS 'Primary key - unique identifier for the token, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_admin_tokens.bearer_token IS 'Unique bearer token string used for API authentication - cryptographically secure random value';
COMMENT ON COLUMN ezkey_admin_tokens.admin_id IS 'Foreign key to admin user who owns this token';
COMMENT ON COLUMN ezkey_admin_tokens.admin_type IS 'Admin type at time of token creation - used for authorization decisions';
COMMENT ON COLUMN ezkey_admin_tokens.tenant_id IS 'Tenant scope at time of token creation - used for multi-tenant authorization';
COMMENT ON COLUMN ezkey_admin_tokens.integration_id IS 'Integration scope at time of token creation - used for integration-specific authorization';
COMMENT ON COLUMN ezkey_admin_tokens.created_at IS 'Audit timestamp with timezone recording when token was created';
COMMENT ON COLUMN ezkey_admin_tokens.expires_at IS 'Token expiration timestamp with timezone - tokens automatically become invalid after this time';
COMMENT ON COLUMN ezkey_admin_tokens.last_used_at IS 'Timestamp with timezone of last token usage - used for security monitoring and session management';
COMMENT ON COLUMN ezkey_admin_tokens.ip_address IS 'IP address from which token was created - used for security monitoring';
COMMENT ON COLUMN ezkey_admin_tokens.user_agent IS 'User agent string from token creation - used for security monitoring';
COMMENT ON COLUMN ezkey_admin_tokens.active IS 'Operational control flag - when FALSE, disables token usage while preserving audit data';

-- ============================================================================
-- STEP 4: Create Admin Temp Tokens Table
-- ============================================================================

-- Temporary tokens for MFA authentication flow (will be removed in V3)
CREATE TABLE ezkey_admin_temp_tokens (
    temp_token_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    temp_token VARCHAR(255) NOT NULL UNIQUE,
    admin_id INT NOT NULL REFERENCES ezkey_admin(admin_id),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    mfa_required BOOLEAN DEFAULT TRUE NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL
);

-- Add table-level comment
COMMENT ON TABLE ezkey_admin_temp_tokens IS
'Temporary tokens for MFA authentication flow. Used during password-based authentication before MFA verification. Will be removed in V3 passwordless migration.';

-- Add column-level comments
COMMENT ON COLUMN ezkey_admin_temp_tokens.temp_token_id IS 'Primary key - unique identifier for the temporary token, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_admin_temp_tokens.temp_token IS 'Unique temporary token string used during MFA authentication flow';
COMMENT ON COLUMN ezkey_admin_temp_tokens.admin_id IS 'Foreign key to admin user for whom this temporary token was created';
COMMENT ON COLUMN ezkey_admin_temp_tokens.created_at IS 'Audit timestamp with timezone recording when temporary token was created';
COMMENT ON COLUMN ezkey_admin_temp_tokens.expires_at IS 'Temporary token expiration timestamp with timezone - short-lived for security';
COMMENT ON COLUMN ezkey_admin_temp_tokens.mfa_required IS 'Flag indicating if MFA verification is required before token can be used';
COMMENT ON COLUMN ezkey_admin_temp_tokens.active IS 'Operational control flag - when FALSE, disables temporary token usage';

-- ============================================================================
-- STEP 5: Extend Existing Tables with Tenant Support
-- ============================================================================

-- Add tenant isolation to existing integration table
ALTER TABLE ezkey_integration ADD COLUMN tenant_id INT REFERENCES ezkey_tenant(tenant_id);
ALTER TABLE ezkey_integration ADD COLUMN is_system_integration BOOLEAN DEFAULT FALSE;
ALTER TABLE ezkey_integration ADD COLUMN created_by_admin_id INT REFERENCES ezkey_admin(admin_id);

-- Add column comments for new integration columns
COMMENT ON COLUMN ezkey_integration.tenant_id IS 'Foreign key to tenant - provides multi-tenant isolation for integrations';
COMMENT ON COLUMN ezkey_integration.is_system_integration IS 'Flag indicating if this is a system-level integration (e.g., admin MFA) - not tenant-specific';
COMMENT ON COLUMN ezkey_integration.created_by_admin_id IS 'Foreign key to admin who created this integration - supports audit trail';

-- ============================================================================
-- STEP 6: Create Performance Indexes
-- ============================================================================

-- Indexes for admin token performance
CREATE INDEX idx_admin_tokens_active ON ezkey_admin_tokens(bearer_token, active) WHERE active = TRUE;
CREATE INDEX idx_admin_tokens_expired ON ezkey_admin_tokens(expires_at) WHERE active = TRUE;

-- Indexes for admin temp token performance
CREATE INDEX idx_admin_temp_tokens_expired ON ezkey_admin_temp_tokens(expires_at) WHERE active = TRUE;

-- Indexes for admin table performance
CREATE INDEX idx_admin_username ON ezkey_admin(username) WHERE active = TRUE;
CREATE INDEX idx_admin_type ON ezkey_admin(admin_type) WHERE active = TRUE;

-- Indexes for tenant table performance
CREATE INDEX idx_tenant_name ON ezkey_tenant(tenant_name) WHERE active = TRUE;

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- Multi-tenant security infrastructure added successfully.
-- V3 migration will transform admin authentication to passwordless-only.
-- ============================================================================
-- ============================================================================
-- Ezkey Migration V3: Transform to Passwordless Schema + Create Initial Global Admin
-- ============================================================================
-- Description: Transforms ezkey_admin table to passwordless-only schema,
--              then creates the system tenant and initial global administrator.
-- 
-- Context: This migration consolidates V3-V9 from the original plan:
--          - Removes password infrastructure (password_hash, mfa_enabled, etc.)
--          - Adds passwordless infrastructure (challenge_required, recovery_codes)
--          - Drops ezkey_admin_temp_tokens table (no longer needed)
--          - Creates system tenant and initial global admin
--
-- Responsibility Split:
--   - Flyway (this migration): Transform schema, create structural data
--   - Bootstrap service: Create enrollment + recovery codes + crypto keys
-- 
-- IMPORTANT: The username 'admin' is a placeholder. For SOC 2 compliance,
--            the initial global admin must be configured with an identifiable
--            username via application properties (ezkey.admin.initial.username).
--            The bootstrap service will update the admin with the configured username.
-- 
-- Author: Ezkey contributors
-- Date: 2025-10-13
-- ============================================================================

-- ============================================================================
-- STEP 1: Transform ezkey_admin Schema to Passwordless-Only
-- ============================================================================

-- Remove password-based authentication columns
ALTER TABLE ezkey_admin DROP COLUMN IF EXISTS password_hash;
ALTER TABLE ezkey_admin DROP COLUMN IF EXISTS mfa_enabled;
ALTER TABLE ezkey_admin DROP COLUMN IF EXISTS mfa_required;
ALTER TABLE ezkey_admin DROP COLUMN IF EXISTS password_change_required;
ALTER TABLE ezkey_admin DROP COLUMN IF EXISTS last_password_change;

-- Add passwordless authentication columns
ALTER TABLE ezkey_admin ADD COLUMN IF NOT EXISTS challenge_required BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE ezkey_admin ADD COLUMN IF NOT EXISTS recovery_codes TEXT[];

-- Update the check_admin_hierarchy constraint (already exists from V2, but modify it)
ALTER TABLE ezkey_admin DROP CONSTRAINT IF EXISTS check_admin_hierarchy;

-- Drop ezkey_admin_temp_tokens table (no longer needed in passwordless architecture)
DROP TABLE IF EXISTS ezkey_admin_temp_tokens;

-- ============================================================================
-- STEP 2: Create System Tenant
-- ============================================================================

-- System tenant represents the organization hosting this Ezkey instance.
-- Initial description matches the default for ezkey.organization.description (deployment context,
-- not operator role). Bootstrap may sync name/description from configuration on startup.
-- Note: is_system_tenant flag will be added by migration V27
INSERT INTO ezkey_tenant (tenant_name, tenant_description, created_at, active) 
VALUES (
    'Ezkey System', 
    'Ezkey MFA instance for your organization', 
    CURRENT_TIMESTAMP, 
    true
);

COMMENT ON TABLE ezkey_tenant IS
'Multi-tenant isolation. The system tenant (Ezkey System) represents the organization for this Ezkey instance; it hosts global administrators.';

-- ============================================================================
-- STEP 3: Create Initial Global Administrator (Passwordless-Only Schema)
-- ============================================================================

-- Initial global admin is the first global administrator with passwordless authentication
-- Bootstrap service will complete setup by creating enrollment and recovery codes
-- NOTE: Username 'admin' is a placeholder. For SOC 2 compliance, the initial global
--       admin must be configured with an identifiable username via application properties.
--       The bootstrap service will update the admin with the configured username and email.
INSERT INTO ezkey_admin (
    username, 
    admin_type, 
    tenant_id,
    integration_id,
    challenge_required,
    recovery_codes,
    enrollment_id,
    created_at, 
    active
) VALUES (
    'admin',  -- Placeholder - will be updated by bootstrap service with configured username
    'GLOBAL_ADMIN', 
    (SELECT tenant_id FROM ezkey_tenant WHERE tenant_name = 'Ezkey System'),
    NULL,
    false,  -- No challenge by default (convenience over paranoia)
    NULL,   -- Bootstrap will generate 10 recovery codes (32-digit, 106-bit entropy)
    NULL,   -- Bootstrap will create global admin enrollment
    CURRENT_TIMESTAMP, 
    true
);

-- ============================================================================
-- STEP 4: Link Tenant to Admin Creator (Circular Reference Resolution)
-- ============================================================================

-- Update tenant to reference the admin who "created" it (initial global admin)
-- This satisfies the foreign key relationship for audit purposes
-- NOTE: Uses placeholder username 'admin' - will be updated after bootstrap
UPDATE ezkey_tenant 
SET created_by_admin_id = (SELECT admin_id FROM ezkey_admin WHERE username = 'admin')
WHERE tenant_name = 'Ezkey System';

-- ============================================================================
-- STEP 5: Update Admin Hierarchy Constraint
-- ============================================================================

-- Update constraint to allow GLOBAL_ADMIN to optionally have system tenant
-- (The original constraint from V2 didn't allow GLOBAL_ADMIN to have tenant_id)
ALTER TABLE ezkey_admin ADD CONSTRAINT check_admin_hierarchy CHECK (
    (admin_type = 'GLOBAL_ADMIN' AND integration_id IS NULL) OR
    (admin_type = 'TENANT_ADMIN' AND tenant_id IS NOT NULL AND integration_id IS NULL) OR
    (admin_type = 'INTEGRATION_ADMIN' AND tenant_id IS NOT NULL AND integration_id IS NOT NULL)
);

-- ============================================================================
-- STEP 6: Add Indexes for Performance
-- ============================================================================

-- Index for global admin queries (filtered on active status)
CREATE INDEX IF NOT EXISTS idx_admin_global_tenant 
ON ezkey_admin(tenant_id, admin_type) 
WHERE admin_type = 'GLOBAL_ADMIN' AND active = TRUE;

-- ============================================================================
-- STEP 7: Documentation Comments
-- ============================================================================

COMMENT ON TABLE ezkey_admin IS
'Administrative users. Uses passwordless-only authentication via Ezkey enrollment. No passwords stored.';

COMMENT ON COLUMN ezkey_admin.challenge_required IS
'If true, authentication attempts for this admin require 6-digit challenge code verification on device.';

COMMENT ON COLUMN ezkey_admin.recovery_codes IS
'Array of BCrypt-hashed recovery codes (32-digit, 106-bit entropy) for emergency access when device is lost. Single-use codes.';

COMMENT ON COLUMN ezkey_admin.enrollment_id IS
'Links the administrator to its Ezkey enrollment using the standard enrollment identifier. Bootstrap service ensures all active admins have an enrollment.';

COMMENT ON COLUMN ezkey_admin.username IS
'Unique username for admin authentication. Used in passwordless login flow.';

COMMENT ON COLUMN ezkey_admin.admin_type IS
'Administrator type: GLOBAL_ADMIN (system-wide), TENANT_ADMIN (tenant-scoped), or INTEGRATION_ADMIN (integration-scoped).';

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- Initial global admin created with passwordless infrastructure ready.
-- Bootstrap service will complete setup on first application startup:
--   - Update admin with configured username and email (SOC 2 compliance)
--   - Create system integration + global admin enrollment
--   - Generate 10 recovery codes (32-digit each)
--   - Display credentials in logs (one-time opportunity to save)
-- ============================================================================

