-- ============================================================================
-- Ezkey Migration V23: Partition ezkey_auth_attempt by Month
-- ============================================================================
-- Description: Converts ezkey_auth_attempt table to monthly range partitioning
--              for improved query performance and efficient data archival.
-- 
-- Context: High-volume table that will grow rapidly in production. Monthly
--          partitioning enables efficient partition pruning for date-range
--          queries and simplifies data lifecycle management.
--
-- Development Mode: This migration assumes an empty or non-existent table.
--                   No data migration is performed.
--
-- Author: Ezkey contributors
-- Date: 2025-01-XX
-- ============================================================================

-- ============================================================================
-- STEP 1: Drop Existing Table (if exists)
-- ============================================================================

-- Drop existing table and all its dependencies (indexes, constraints)
-- In development mode, this is safe as there's no data to preserve
DROP TABLE IF EXISTS ezkey_auth_attempt CASCADE;

-- ============================================================================
-- STEP 2: Create Partitioned Table Structure
-- ============================================================================

-- Create partitioned table directly with final name
-- Note: Includes columns added by V12 (encryption hash columns)
CREATE TABLE ezkey_auth_attempt (
    auth_attempt_id INT GENERATED ALWAYS AS IDENTITY,
    enrollment_id INT NOT NULL REFERENCES ezkey_enrollment(enrollment_id),
    auth_attempt_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' 
        CHECK (auth_attempt_status IN ('PENDING', 'READ', 'INVALID', 'REJECTED', 'ACCEPTED', 'EXPIRED')),
    auth_attempt_challenge INT,
    auth_attempt_proof_token TEXT NOT NULL,  -- Encrypted proof token (added by V12)
    auth_attempt_proof_token_hash VARCHAR(128),  -- Hash for deterministic lookup (added by V12)
    device_proof_token TEXT,  -- Encrypted device proof token (added by V12)
    device_proof_token_hash VARCHAR(128),  -- Hash for deterministic lookup (added by V12)
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP + INTERVAL '120 seconds'),
    -- Primary key composite required for partitioned tables
    -- PostgreSQL requires UNIQUE constraints to include partition key (created_at)
    PRIMARY KEY (auth_attempt_id, created_at)
) PARTITION BY RANGE (created_at);

-- Add table-level comment
COMMENT ON TABLE ezkey_auth_attempt IS 
'Authentication attempt table partitioned by month. Tracks individual MFA requests from creation through completion. Uses one-time proof tokens to prevent replay attacks and includes automatic expiration for security. Partitioned by created_at for efficient query performance and data lifecycle management.';

-- Add column-level comments
COMMENT ON COLUMN ezkey_auth_attempt.auth_attempt_id IS 
'Primary key - unique identifier for this authentication attempt, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_auth_attempt.enrollment_id IS 
'Foreign key to enrollment that will handle this authentication - determines which device/user will receive the auth request';
COMMENT ON COLUMN ezkey_auth_attempt.auth_attempt_status IS 
'Authentication attempt lifecycle status - PENDING (created), READ (device claimed), INVALID (crypto validation failed), REJECTED (user denied), ACCEPTED (user approved), EXPIRED (superseded or timeout) - tracks complete authentication flow';
COMMENT ON COLUMN ezkey_auth_attempt.auth_attempt_challenge IS 
'Optional numeric challenge (4-6 digits) displayed to user on mobile device for additional security - required when enrollment.auth_attempt_challenge_required is TRUE';
COMMENT ON COLUMN ezkey_auth_attempt.auth_attempt_proof_token IS 
'One-time cryptographic token unique to this auth attempt - prevents replay attacks and ensures request authenticity (never reused). Encrypted at rest (added by V12).';
COMMENT ON COLUMN ezkey_auth_attempt.auth_attempt_proof_token_hash IS 
'SHA-256 hash of auth_attempt_proof_token for deterministic lookups without decryption. Unique constraint ensures one-time token guarantee (added by V12).';
COMMENT ON COLUMN ezkey_auth_attempt.device_proof_token IS 
'Token generated by mobile device proving it received the auth_attempt_proof_token - cryptographic proof that device has access to the legitimate auth attempt. Encrypted at rest (added by V12).';
COMMENT ON COLUMN ezkey_auth_attempt.device_proof_token_hash IS 
'SHA-256 hash of device_proof_token for deterministic lookups without decryption. Unique constraint ensures token uniqueness (added by V12).';
COMMENT ON COLUMN ezkey_auth_attempt.created_at IS 
'Audit timestamp with timezone recording when auth attempt was created - immutable value used for compliance and performance monitoring. Used as partitioning key for monthly partitions.';
COMMENT ON COLUMN ezkey_auth_attempt.expires_at IS 
'Automatic expiration timestamp with timezone (default 120 seconds) - expired attempts are invalid for security and should be cleaned up by maintenance jobs';

-- ============================================================================
-- STEP 3: Create Initial Partitions
-- ============================================================================

-- Create partition for current month
-- Note: Using first day of current month to first day of next month
DO $$
DECLARE
    current_month_start TIMESTAMPTZ;
    next_month_start TIMESTAMPTZ;
    partition_name TEXT;
BEGIN
    -- Calculate current month boundaries (using TIMESTAMPTZ for partition boundaries)
    current_month_start := DATE_TRUNC('month', CURRENT_TIMESTAMP);
    next_month_start := current_month_start + INTERVAL '1 month';
    
    -- Create partition name (e.g., ezkey_auth_attempt_2025_01)
    partition_name := 'ezkey_auth_attempt_' || TO_CHAR(current_month_start, 'YYYY_MM');
    
    -- Create partition for current month
    EXECUTE format(
        'CREATE TABLE %I PARTITION OF ezkey_auth_attempt FOR VALUES FROM (%L) TO (%L)',
        partition_name,
        current_month_start,
        next_month_start
    );
    
    -- Create partition for next month (pre-create for seamless transition)
    partition_name := 'ezkey_auth_attempt_' || TO_CHAR(next_month_start, 'YYYY_MM');
    EXECUTE format(
        'CREATE TABLE %I PARTITION OF ezkey_auth_attempt FOR VALUES FROM (%L) TO (%L)',
        partition_name,
        next_month_start,
        next_month_start + INTERVAL '1 month'
    );
END $$;

-- ============================================================================
-- STEP 4: Create Indexes on Partitioned Table
-- ============================================================================

-- Index for enrollment queries with created_at (supersession queries)
-- This index will be created locally on each partition
CREATE INDEX idx_auth_attempt_enrollment_created 
ON ezkey_auth_attempt(enrollment_id, created_at DESC);

-- Index for expiration cleanup jobs
-- Note: Cannot use CURRENT_TIMESTAMP in partial index predicate (not IMMUTABLE)
-- The index will still be efficient for cleanup queries with WHERE expires_at < NOW()
CREATE INDEX idx_auth_attempt_expires_at 
ON ezkey_auth_attempt(expires_at);

-- Index for status filtering
CREATE INDEX idx_auth_attempt_status 
ON ezkey_auth_attempt(auth_attempt_status);

-- Unique indexes on hash columns (added by V12)
-- Note: PostgreSQL requires UNIQUE constraints on partitioned tables to include partition key
-- Including created_at ensures global uniqueness while satisfying PostgreSQL's requirement
-- Hash collisions across partitions are extremely unlikely (SHA-256)
CREATE UNIQUE INDEX uq_auth_attempt_proof_token_hash 
ON ezkey_auth_attempt(auth_attempt_proof_token_hash, created_at) 
WHERE auth_attempt_proof_token_hash IS NOT NULL;

CREATE UNIQUE INDEX uq_auth_attempt_device_proof_token_hash 
ON ezkey_auth_attempt(device_proof_token_hash, created_at) 
WHERE device_proof_token_hash IS NOT NULL;

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- ezkey_auth_attempt table is now partitioned by month (created_at).
-- 
-- Next Steps:
-- 1. Test partition pruning with queries
-- 2. Set up scheduled job to create future partitions (see PartitionSchedulerService)
-- ============================================================================
