-- ============================================================================
-- Ezkey Migration V24: Partition ezkey_audit_log by Month
-- ============================================================================
-- Description: Converts ezkey_audit_log table to monthly range partitioning
--              for improved query performance, efficient data archival, and
--              SOC2 compliance support.
--
-- Context: High-volume table that will grow rapidly in production. Monthly
--          partitioning enables efficient partition pruning for date-range
--          queries, simplifies compliance reporting, and supports 7-year
--          retention requirements for SOC2.
--
-- Development Mode: This migration assumes an empty or non-existent table.
--                   No data migration is performed.
--
-- Author: Ezkey contributors
-- Date: 2025-01-XX
-- ============================================================================

-- ============================================================================
-- STEP 1: Drop Existing Table (if exists)
-- ============================================================================

-- Drop existing table and all its dependencies (indexes, constraints)
-- In development mode, this is safe as there's no data to preserve
DROP TABLE IF EXISTS ezkey_audit_log CASCADE;

-- ============================================================================
-- STEP 2: Create Partitioned Table Structure
-- ============================================================================

-- Create partitioned table directly with final name
CREATE TABLE ezkey_audit_log (
    audit_log_id BIGINT GENERATED ALWAYS AS IDENTITY,

    -- Event classification
    event_type VARCHAR(50) NOT NULL,
    event_action VARCHAR(100) NOT NULL,
    event_status VARCHAR(20) NOT NULL CHECK (event_status IN ('SUCCESS', 'FAILURE', 'ERROR')),

    -- API identification
    api_name VARCHAR(50) NOT NULL CHECK (api_name IN ('ADMIN_API', 'AUTH_API', 'M2M_API')),

    -- Network information
    ip_address VARCHAR(45),
    user_agent TEXT,

    -- Entity references (nullable for flexibility)
    admin_id INT REFERENCES ezkey_admin(admin_id) ON DELETE SET NULL,
    integration_id INT REFERENCES ezkey_integration(integration_id) ON DELETE SET NULL,
    enrollment_id INT REFERENCES ezkey_enrollment(enrollment_id) ON DELETE SET NULL,
    auth_attempt_id INT,
    auth_attempt_created_at TIMESTAMPTZ,
    tenant_id INT REFERENCES ezkey_tenant(tenant_id) ON DELETE SET NULL,
    -- Foreign key to partitioned table requires composite key reference
    -- PostgreSQL requires FK to partitioned table to reference composite primary key
    FOREIGN KEY (auth_attempt_id, auth_attempt_created_at)
        REFERENCES ezkey_auth_attempt(auth_attempt_id, created_at)
        ON DELETE SET NULL,

    -- Event details and errors
    event_details TEXT,
    error_message TEXT,

    -- Timestamp (partitioning key)
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
) PARTITION BY RANGE (created_at);

-- Add table-level comment
COMMENT ON TABLE ezkey_audit_log IS
'Comprehensive audit logging partitioned by month for security monitoring, forensic analysis, and SOC2 compliance. Tracks all critical operations across admin-api and auth-api with full context including IP addresses, user agents, and entity references. Partitioned by created_at for efficient query performance, compliance reporting, and 7-year retention management.';

-- Add column-level comments (same as original, with partitioning note)
COMMENT ON COLUMN ezkey_audit_log.audit_log_id IS
'Primary key - unique identifier for this audit log entry, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_audit_log.event_type IS
'Type of event being audited (e.g., ADMIN_LOGIN, ENROLLMENT_CREATED, AUTH_ATTEMPT_CREATED)';
COMMENT ON COLUMN ezkey_audit_log.event_action IS
'Specific action taken (e.g., login_attempt, enrollment_deletion, device_binding)';
COMMENT ON COLUMN ezkey_audit_log.event_status IS
'Result status of the event - SUCCESS (completed successfully), FAILURE (failed validation), ERROR (unexpected error)';
COMMENT ON COLUMN ezkey_audit_log.api_name IS
'API where the event originated - ADMIN_API (port 9080), AUTH_API (port 8080), or M2M_API (port 7080)';
COMMENT ON COLUMN ezkey_audit_log.ip_address IS
'Client IP address extracted from request headers (CF-Connecting-IP, X-Forwarded-For, X-Real-IP) - used for security monitoring';
COMMENT ON COLUMN ezkey_audit_log.user_agent IS
'User agent string from HTTP request - helps identify device types and potential security issues';
COMMENT ON COLUMN ezkey_audit_log.admin_id IS
'Foreign key to admin user involved in the event - SET NULL on admin deletion to preserve audit trail';
COMMENT ON COLUMN ezkey_audit_log.integration_id IS
'Foreign key to integration involved in the event - SET NULL on integration deletion to preserve audit trail';
COMMENT ON COLUMN ezkey_audit_log.enrollment_id IS
'Foreign key to enrollment involved in the event - SET NULL on enrollment deletion to preserve audit trail';
COMMENT ON COLUMN ezkey_audit_log.auth_attempt_id IS
'Foreign key (part 1) to authentication attempt involved in the event - part of composite FK to partitioned table';
COMMENT ON COLUMN ezkey_audit_log.auth_attempt_created_at IS
'Foreign key (part 2) to authentication attempt - created_at timestamp from referenced auth_attempt. Required for FK to partitioned table (ezkey_auth_attempt) which uses composite primary key (auth_attempt_id, created_at). SET NULL on auth attempt deletion to preserve audit trail';
COMMENT ON COLUMN ezkey_audit_log.tenant_id IS
'Foreign key to tenant involved in the event - SET NULL on tenant deletion to preserve audit trail';
COMMENT ON COLUMN ezkey_audit_log.event_details IS
'Additional event-specific details in structured format - used for forensic analysis and debugging';
COMMENT ON COLUMN ezkey_audit_log.error_message IS
'Error message for failed or error status events - used for troubleshooting and security analysis';
COMMENT ON COLUMN ezkey_audit_log.created_at IS
'Timestamp with timezone when the event was recorded - immutable value for compliance tracking. Used as partitioning key for monthly partitions.';

-- ============================================================================
-- STEP 3: Create Initial Partitions
-- ============================================================================

-- Create partition for current month
-- Note: Using first day of current month to first day of next month
DO $$
DECLARE
    current_month_start TIMESTAMPTZ;
    next_month_start TIMESTAMPTZ;
    partition_name TEXT;
BEGIN
    -- Calculate current month boundaries (using TIMESTAMPTZ for partition boundaries)
    current_month_start := DATE_TRUNC('month', CURRENT_TIMESTAMP);
    next_month_start := current_month_start + INTERVAL '1 month';

    -- Create partition name (e.g., ezkey_audit_log_2025_01)
    partition_name := 'ezkey_audit_log_' || TO_CHAR(current_month_start, 'YYYY_MM');

    -- Create partition for current month
    EXECUTE format(
        'CREATE TABLE %I PARTITION OF ezkey_audit_log FOR VALUES FROM (%L) TO (%L)',
        partition_name,
        current_month_start,
        next_month_start
    );

    -- Create partition for next month (pre-create for seamless transition)
    partition_name := 'ezkey_audit_log_' || TO_CHAR(next_month_start, 'YYYY_MM');
    EXECUTE format(
        'CREATE TABLE %I PARTITION OF ezkey_audit_log FOR VALUES FROM (%L) TO (%L)',
        partition_name,
        next_month_start,
        next_month_start + INTERVAL '1 month'
    );
END $$;

-- ============================================================================
-- STEP 4: Create Indexes on Partitioned Table
-- ============================================================================

-- Index for event type queries (most common filter)
-- This index will be created locally on each partition
CREATE INDEX idx_audit_log_event_type
ON ezkey_audit_log(event_type);

-- Index for status queries (security monitoring)
CREATE INDEX idx_audit_log_status
ON ezkey_audit_log(event_status);

-- Index for IP address queries (forensic analysis)
CREATE INDEX idx_audit_log_ip_address
ON ezkey_audit_log(ip_address);

-- Index for date range queries (compliance reporting)
CREATE INDEX idx_audit_log_created_at
ON ezkey_audit_log(created_at DESC);

-- Composite index for API + event type queries
CREATE INDEX idx_audit_log_api_event
ON ezkey_audit_log(api_name, event_type);

-- Index for enrollment tracking
CREATE INDEX idx_audit_log_enrollment
ON ezkey_audit_log(enrollment_id)
WHERE enrollment_id IS NOT NULL;

-- Index for admin tracking
CREATE INDEX idx_audit_log_admin
ON ezkey_audit_log(admin_id, created_at DESC)
WHERE admin_id IS NOT NULL;

-- JSONB GIN indexes for encryption operations (added by V19)
-- These indexes enable efficient queries on event_details JSONB field
CREATE INDEX idx_audit_encryption_key_id
ON ezkey_audit_log
USING GIN ((event_details::jsonb))
WHERE event_type IN ('KEY_INTRODUCED', 'KEY_PROMOTED_PRIMARY', 'KEY_DEMOTED', 'KEY_DISABLED');

CREATE INDEX idx_audit_reencryption_batch_id
ON ezkey_audit_log
USING GIN ((event_details::jsonb))
WHERE event_type IN ('REENCRYPTION_STARTED', 'REENCRYPTION_COMPLETED', 'REENCRYPTION_FAILED',
                     'REENCRYPTION_PAUSED', 'REENCRYPTION_RESUMED', 'REENCRYPTION_BATCH_PROGRESS');

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- ezkey_audit_log table is now partitioned by month (created_at).
--
-- Next Steps:
-- 1. Test partition pruning with queries
-- 2. Set up scheduled job to create future partitions (see PartitionSchedulerService)
-- 3. Plan for 7-year retention policy (SOC2 compliance)
-- ============================================================================
