-- ============================================================================
-- Ezkey Migration V6: Create Audit Logging Infrastructure
-- ============================================================================
-- Description: Creates comprehensive audit logging system for security
--              monitoring, forensic analysis, and SOC2 compliance support.
--
-- Context: This migration introduces audit logging capabilities for all
--          critical operations across admin-api and auth-api to support
--          security monitoring and eventual SOC2 certification.
--
-- Author: Ezkey contributors
-- Date: 2025-10-16
-- ============================================================================

-- ============================================================================
-- STEP 1: Create Audit Log Table
-- ============================================================================

-- Audit log table for security monitoring and compliance
CREATE TABLE ezkey_audit_log (
    audit_log_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- Event classification
    event_type VARCHAR(50) NOT NULL,
    event_action VARCHAR(100) NOT NULL,
    event_status VARCHAR(20) NOT NULL CHECK (event_status IN ('SUCCESS', 'FAILURE', 'ERROR')),

    -- API identification
    api_name VARCHAR(50) NOT NULL CHECK (api_name IN ('ADMIN_API', 'AUTH_API', 'INTEGRATION_API')),

    -- Network information
    ip_address VARCHAR(45),
    user_agent TEXT,

    -- Entity references (nullable for flexibility)
    admin_id INT REFERENCES ezkey_admin(admin_id) ON DELETE SET NULL,
    integration_id INT REFERENCES ezkey_integration(integration_id) ON DELETE SET NULL,
    enrollment_id INT REFERENCES ezkey_enrollment(enrollment_id) ON DELETE SET NULL,
    auth_attempt_id INT REFERENCES ezkey_auth_attempt(auth_attempt_id) ON DELETE SET NULL,
    tenant_id INT REFERENCES ezkey_tenant(tenant_id) ON DELETE SET NULL,
    target_admin_id INT REFERENCES ezkey_admin(admin_id) ON DELETE SET NULL,

    -- Event details and errors
    event_details TEXT,
    error_message TEXT,

    -- Timestamp
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ============================================================================
-- STEP 2: Add Table and Column Comments
-- ============================================================================

COMMENT ON TABLE ezkey_audit_log IS
'Comprehensive audit logging for security monitoring, forensic analysis, and SOC2 compliance. Tracks all critical operations across admin-api and auth-api with full context including IP addresses, user agents, and entity references.';

COMMENT ON COLUMN ezkey_audit_log.audit_log_id IS 'Primary key - unique identifier for this audit log entry, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_audit_log.event_type IS 'Type of event being audited (e.g., ADMIN_LOGIN, ENROLLMENT_CREATED, AUTH_ATTEMPT_CREATED)';
COMMENT ON COLUMN ezkey_audit_log.event_action IS 'Specific action taken (e.g., login_attempt, enrollment_deletion, device_binding)';
COMMENT ON COLUMN ezkey_audit_log.event_status IS 'Result status of the event - SUCCESS (completed successfully), FAILURE (failed validation), ERROR (unexpected error)';
COMMENT ON COLUMN ezkey_audit_log.api_name IS 'API where the event originated - ADMIN_API (port 9080), AUTH_API (port 8080), or INTEGRATION_API (port 7080)';
COMMENT ON COLUMN ezkey_audit_log.ip_address IS 'Client IP address extracted from request headers (CF-Connecting-IP, X-Forwarded-For, X-Real-IP) - used for security monitoring';
COMMENT ON COLUMN ezkey_audit_log.user_agent IS 'User agent string from HTTP request - helps identify device types and potential security issues';
COMMENT ON COLUMN ezkey_audit_log.admin_id IS 'Foreign key to admin user involved in the event - SET NULL on admin deletion to preserve audit trail';
COMMENT ON COLUMN ezkey_audit_log.integration_id IS 'Foreign key to integration involved in the event - SET NULL on integration deletion to preserve audit trail';
COMMENT ON COLUMN ezkey_audit_log.enrollment_id IS 'Foreign key to enrollment involved in the event - SET NULL on enrollment deletion to preserve audit trail';
COMMENT ON COLUMN ezkey_audit_log.auth_attempt_id IS 'Foreign key to authentication attempt involved in the event - SET NULL on auth attempt deletion to preserve audit trail';
COMMENT ON COLUMN ezkey_audit_log.tenant_id IS 'Foreign key to tenant involved in the event - SET NULL on tenant deletion to preserve audit trail';
COMMENT ON COLUMN ezkey_audit_log.target_admin_id IS 'Admin ID that is the subject of the event (e.g. created, deactivated, or activated). Used for querying all events affecting a given administrator. NULL for non-admin-lifecycle events. SET NULL on admin deletion to preserve audit trail.';
COMMENT ON COLUMN ezkey_audit_log.event_details IS 'Additional event-specific details in structured format - used for forensic analysis and debugging';
COMMENT ON COLUMN ezkey_audit_log.error_message IS 'Error message for failed or error status events - used for troubleshooting and security analysis';
COMMENT ON COLUMN ezkey_audit_log.created_at IS 'Timestamp with timezone when the event was recorded - immutable value for compliance tracking';

-- ============================================================================
-- STEP 3: Create Performance Indexes
-- ============================================================================

-- Index for event type queries (most common filter)
CREATE INDEX idx_audit_log_event_type ON ezkey_audit_log(event_type);

-- Index for status queries (security monitoring)
CREATE INDEX idx_audit_log_status ON ezkey_audit_log(event_status);

-- Index for IP address queries (forensic analysis)
CREATE INDEX idx_audit_log_ip_address ON ezkey_audit_log(ip_address);

-- Index for date range queries (compliance reporting)
CREATE INDEX idx_audit_log_created_at ON ezkey_audit_log(created_at DESC);

-- Composite index for API + event type queries
CREATE INDEX idx_audit_log_api_event ON ezkey_audit_log(api_name, event_type);

-- Index for enrollment tracking
CREATE INDEX idx_audit_log_enrollment ON ezkey_audit_log(enrollment_id) WHERE enrollment_id IS NOT NULL;

-- Index for admin tracking
CREATE INDEX idx_audit_log_admin ON ezkey_audit_log(admin_id) WHERE admin_id IS NOT NULL;

-- Index for target admin tracking (admin lifecycle events)
CREATE INDEX idx_audit_log_target_admin ON ezkey_audit_log(target_admin_id) WHERE target_admin_id IS NOT NULL;

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- Audit logging infrastructure created successfully.
-- Ready for security monitoring and SOC2 compliance tracking.
-- ============================================================================
-- ============================================================================
-- Ezkey Database Migration - V7
-- API Keys for Machine-to-Machine Authentication
-- ============================================================================
-- Description: Adds API keys table for M2M authentication of integrated
--              applications, enabling server-to-server authentication without
--              login/logout overhead.
--
-- Author: Ezkey contributors
-- Date: 2025
-- License: MIT
-- ============================================================================

-- ============================================================================
-- STEP 1: Create API Keys Table
-- ============================================================================

-- API Keys table for machine-to-machine authentication
-- Stores Duo-style integration keys (public) and secret keys (BCrypt hashed)
CREATE TABLE ezkey_api_key (
    api_key_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    integration_id INT NOT NULL REFERENCES ezkey_integration(integration_id),
    
    -- Duo-style keys
    integration_key VARCHAR(255) NOT NULL UNIQUE, -- ezkey_ikey_xxx (public identifier)
    secret_key_hash VARCHAR(255) NOT NULL,        -- BCrypt hash of ezkey_skey_xxx
    
    -- Metadata
    description VARCHAR(255),                      -- Human-readable description
    created_by_admin_id INT NOT NULL REFERENCES ezkey_admin(admin_id),
    
    -- Security features
    last_used_at TIMESTAMPTZ,                      -- Tracks last usage for audit
    expires_at TIMESTAMPTZ,                        -- Optional expiration for rotation
    ip_whitelist TEXT[],                           -- Optional IP restrictions (CIDR format)
    
    -- Status and audit
    active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    revoked_at TIMESTAMPTZ,
    revoked_by_admin_id INT REFERENCES ezkey_admin(admin_id),
    
    -- Constraints
    CONSTRAINT check_expiration CHECK (expires_at IS NULL OR expires_at > created_at),
    CONSTRAINT check_revoked_consistency CHECK (
        (active = TRUE AND revoked_at IS NULL AND revoked_by_admin_id IS NULL) OR
        (active = FALSE AND revoked_at IS NOT NULL AND revoked_by_admin_id IS NOT NULL)
    )
);

-- ============================================================================
-- STEP 2: Create Indexes for Performance
-- ============================================================================

-- Index for looking up active keys by integration
CREATE INDEX idx_api_key_integration ON ezkey_api_key(integration_id, active);

-- Partial index for fast active key lookup (most common query)
CREATE INDEX idx_api_key_lookup ON ezkey_api_key(integration_key) 
WHERE active = true;

-- Index for admin audit queries
CREATE INDEX idx_api_key_admin ON ezkey_api_key(created_by_admin_id);

-- Index for expiration cleanup job
CREATE INDEX idx_api_key_expiration ON ezkey_api_key(expires_at) 
WHERE active = true AND expires_at IS NOT NULL;

-- ============================================================================
-- STEP 3: Add Table and Column Comments
-- ============================================================================

-- Table-level comment
COMMENT ON TABLE ezkey_api_key IS
'API keys for machine-to-machine (M2M) authentication of integrated applications.
Enables server-to-server authentication without login/logout overhead.
Uses Duo-style dual key system: public integration key + private secret key.';

-- Column comments for clarity
COMMENT ON COLUMN ezkey_api_key.api_key_id IS 
'Primary key identifier for the API key record';

COMMENT ON COLUMN ezkey_api_key.integration_id IS 
'Foreign key to integration - links API key to specific integration';

COMMENT ON COLUMN ezkey_api_key.integration_key IS 
'Public integration key (ezkey_ikey_xxx) - stored in plain text, safe to display in logs and UI';

COMMENT ON COLUMN ezkey_api_key.secret_key_hash IS 
'BCrypt hash of secret key (ezkey_skey_xxx) - plain text secret NEVER stored, shown only once at creation';

COMMENT ON COLUMN ezkey_api_key.description IS 
'Optional human-readable description for key identification (e.g., "Production Server API Key")';

COMMENT ON COLUMN ezkey_api_key.created_by_admin_id IS 
'Foreign key to admin who created this API key - required for audit trail';

COMMENT ON COLUMN ezkey_api_key.last_used_at IS 
'Timestamp of last successful authentication using this key - updated on each use for monitoring';

COMMENT ON COLUMN ezkey_api_key.expires_at IS 
'Optional expiration date for automatic key rotation enforcement - null means no expiration';

COMMENT ON COLUMN ezkey_api_key.ip_whitelist IS 
'Optional array of IP addresses or CIDR ranges allowed to use this key (e.g., ["192.168.1.0/24", "10.0.0.1"])';

COMMENT ON COLUMN ezkey_api_key.active IS 
'Active status flag - inactive keys cannot authenticate but are preserved for audit';

COMMENT ON COLUMN ezkey_api_key.created_at IS 
'Audit timestamp recording when API key was created - immutable for compliance';

COMMENT ON COLUMN ezkey_api_key.revoked_at IS 
'Timestamp when key was revoked - null for active keys, set when explicitly revoked';

COMMENT ON COLUMN ezkey_api_key.revoked_by_admin_id IS 
'Foreign key to admin who revoked this key - required when revoked for audit trail';

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- This migration adds support for API key authentication, enabling integrated
-- applications to authenticate via HTTP Basic Auth without login/logout.
--
-- Security features:
-- - BCrypt hashed secrets (like passwords)
-- - Optional expiration dates
-- - IP whitelist support  
-- - Rate limiting (configured in application)
-- - Comprehensive audit trail
--
-- Next steps after migration:
-- 1. Implement ApiKey entity and repository
-- 2. Create ApiKeyService for generation and validation
-- 3. Add ApiKeyAuthenticationFilter to security chain
-- 4. Create management endpoints in ApiKeyController
-- ============================================================================

-- Ezkey Migration V10: Encryption Phase 1 Scaffold
-- Purpose: Placeholder migration to mark the start of encryption rollout.
-- No schema changes required at this step; application-level encryption will
-- progressively convert existing plaintext values on update operations.

-- No-op block to satisfy Flyway execution on PostgreSQL
DO $$ BEGIN END $$;















-- Ezkey Migration V11: Add Device Public Key Hash for Uniqueness Validation
-- Purpose: Add a separate hash column for device public key to enable uniqueness validation
-- independent of encryption format. This allows validation even if device_public_key is encrypted.

-- Add device_public_key_hash column
ALTER TABLE ezkey_enrollment
ADD COLUMN device_public_key_hash VARCHAR(64);

-- Add comment explaining the hash column
COMMENT ON COLUMN ezkey_enrollment.device_public_key_hash IS 
'SHA-256 hash of device_public_key (hexadecimal, 64 chars). Used for uniqueness validation independent of encryption format. NULL allowed for enrollments without device public key yet.';

-- Create unique index on device_public_key_hash (excluding NULL values)
-- This ensures that each device public key can only be used once for a verified enrollment
CREATE UNIQUE INDEX idx_enrollment_device_public_key_hash_unique 
ON ezkey_enrollment(device_public_key_hash) 
WHERE device_public_key_hash IS NOT NULL;

-- Add index comment
COMMENT ON INDEX idx_enrollment_device_public_key_hash_unique IS 
'Unique index on device public key hash to prevent reuse of device public keys. NULL values are excluded from uniqueness constraint.';

-- Ezkey Migration V12: Encrypt proof tokens and add hash columns for deterministic lookups
-- This migration prepares the database for Tink-encrypted proof tokens by introducing auxiliary
-- SHA-256 hash columns. Hashes enable secure equality checks while the encrypted values are stored
-- with the ENC: prefix. Uniqueness constraints are applied on the hashes to preserve the
-- one-time-token guarantees without exposing the original secrets.

ALTER TABLE ezkey_enrollment
    ADD COLUMN enrollment_proof_token_hash VARCHAR(128);

ALTER TABLE ezkey_enrollment
    ADD CONSTRAINT uq_enrollment_proof_token_hash UNIQUE (enrollment_proof_token_hash);

ALTER TABLE ezkey_auth_attempt
    ADD COLUMN auth_attempt_proof_token_hash VARCHAR(128);

ALTER TABLE ezkey_auth_attempt
    ADD COLUMN device_proof_token_hash VARCHAR(128);

ALTER TABLE ezkey_auth_attempt
    ADD CONSTRAINT uq_auth_attempt_proof_token_hash UNIQUE (auth_attempt_proof_token_hash);

ALTER TABLE ezkey_auth_attempt
    ADD CONSTRAINT uq_auth_attempt_device_proof_token_hash UNIQUE (device_proof_token_hash);

-- ============================================================================
-- Ezkey Migration V13: Add Email Column to ezkey_admin for SOC 2 Compliance
-- ============================================================================
-- Description: Adds email column to ezkey_admin table to support SOC 2 compliance
--              requirements for individual accountability and audit trail.
-- 
-- SOC 2 Requirements:
--   - CC6.1: Logical access controls require individual identification
--   - CC7.2: Audit trail must identify individuals (not generic accounts)
--   - Email is required for GLOBAL_ADMIN type to ensure accountability
--
-- Author: Ezkey contributors
-- Date: 2025-01-XX
-- ============================================================================

-- ============================================================================
-- STEP 1: Add Email Column
-- ============================================================================

-- Add email column to ezkey_admin table
-- Email is required for GLOBAL_ADMIN type (SOC 2 compliance)
-- Optional for other admin types (can be added later if needed)
ALTER TABLE ezkey_admin
    ADD COLUMN email VARCHAR(255);

-- ============================================================================
-- STEP 2: Add Constraints
-- ============================================================================

-- Add unique constraint on email (one email per admin)
ALTER TABLE ezkey_admin
    ADD CONSTRAINT uq_admin_email UNIQUE (email);

-- Add check constraint to ensure email format is valid (basic validation)
-- More comprehensive validation is done at application level
ALTER TABLE ezkey_admin
    ADD CONSTRAINT chk_admin_email_format 
    CHECK (email IS NULL OR email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$');

-- ============================================================================
-- STEP 3: Update Existing Admin (if exists)
-- ============================================================================

-- For existing admin with username 'admin', we cannot set email automatically
-- as it must be identifiable. This will be handled by configuration validation.
-- Migration will leave email as NULL for existing admin, which will cause
-- startup validation to fail if not configured properly.

-- ============================================================================
-- STEP 4: Add Documentation Comments
-- ============================================================================

COMMENT ON COLUMN ezkey_admin.email IS
'Email address for the administrator. Required for GLOBAL_ADMIN type for SOC 2 compliance (CC6.1, CC7.2). '
'Used for audit trail and accountability. Must be unique and valid email format.';

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- Email column added to ezkey_admin table.
-- 
-- IMPORTANT: For existing installations, the initial global admin email
-- must be configured via application properties:
--   ezkey.admin.initial.username=<identifiable-username>
--   ezkey.admin.initial.email=<email-address>
--
-- The system will fail to start if email is not configured for GLOBAL_ADMIN.
-- ============================================================================

-- ============================================================================
-- Ezkey Migration V14: Add First Name and Last Name to ezkey_admin for SOC 2 Compliance
-- ============================================================================
-- Description: Adds first_name and last_name columns to ezkey_admin table to support
--              SOC 2 compliance requirements for individual identification.
-- 
-- SOC 2 Requirements:
--   - CC6.1: Logical access controls require individual identification
--   - CC7.2: Audit trail must identify individuals (not generic accounts)
--   - First name and last name are required for GLOBAL_ADMIN type to ensure
--     proper identification and accountability
--
-- Author: Ezkey contributors
-- Date: 2025-01-XX
-- ============================================================================

-- ============================================================================
-- STEP 1: Add First Name and Last Name Columns
-- ============================================================================

-- Add first_name column to ezkey_admin table
-- Required for GLOBAL_ADMIN type (SOC 2 compliance)
-- Optional for other admin types (can be added later if needed)
ALTER TABLE ezkey_admin
    ADD COLUMN first_name VARCHAR(100);

-- Add last_name column to ezkey_admin table
-- Required for GLOBAL_ADMIN type (SOC 2 compliance)
-- Optional for other admin types (can be added later if needed)
ALTER TABLE ezkey_admin
    ADD COLUMN last_name VARCHAR(100);

-- ============================================================================
-- STEP 2: Add Documentation Comments
-- ============================================================================

COMMENT ON COLUMN ezkey_admin.first_name IS
'First name of the administrator. Required for GLOBAL_ADMIN type for SOC 2 compliance (CC6.1, CC7.2). '
'Used for audit trail and accountability. Must be provided for initial global admin.';

COMMENT ON COLUMN ezkey_admin.last_name IS
'Last name of the administrator. Required for GLOBAL_ADMIN type for SOC 2 compliance (CC6.1, CC7.2). '
'Used for audit trail and accountability. Must be provided for initial global admin.';

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- First name and last name columns added to ezkey_admin table.
-- 
-- IMPORTANT: For existing installations, the initial global admin first name
-- and last name must be configured via application properties:
--   ezkey.admin.initial.username=<identifiable-username>
--   ezkey.admin.initial.email=<email-address>
--   ezkey.admin.initial.first-name=<first-name>
--   ezkey.admin.initial.last-name=<last-name>
--
-- The system will fail to start if first name and last name are not configured
-- for GLOBAL_ADMIN.
-- ============================================================================

-- Migration: Replace RSA-2048 with Ed25519
-- Description: Updates column comments to reflect Ed25519 instead of RSA-2048.
-- Note: Column structure remains unchanged - only comments are updated.
-- The integration_private_key and integration_public_key columns are kept as they are
-- critical for mutual cryptographic authentication (backend signs authAttemptProofToken).

-- Update table comment
COMMENT ON TABLE ezkey_enrollment IS 'Device enrollment table establishing cryptographic binding between integration, user, and mobile device. Contains Ed25519 key pairs and tracks enrollment lifecycle from creation through verification. Each enrollment enables authentication attempts and includes security configuration like challenge requirements.';

-- Update integration_private_key column comment
COMMENT ON COLUMN ezkey_enrollment.integration_private_key IS 'Ed25519 private key seed for integration-side cryptographic operations (32 bytes raw, Base64 encoded) - SENSITIVE DATA requiring encryption at rest and secure handling. Used by backend to sign authAttemptProofToken for mutual authentication.';

-- Update integration_public_key column comment
COMMENT ON COLUMN ezkey_enrollment.integration_public_key IS 'Ed25519 public key for integration-side operations (32 bytes raw, Base64 encoded) - corresponding public key for integration_private_key, safe to expose. Used by mobile app to verify backend signatures (authAttemptProofTokenSignedByIntegration).';

-- Update device_public_key column comment
COMMENT ON COLUMN ezkey_enrollment.device_public_key IS 'Ed25519 public key from mobile device (32 bytes raw, Base64 encoded) - used to verify signatures from device during authentication attempts, set during binding process.';

-- Migration: Replace Ed25519 with EC P-256
-- Description: Updates column comments to reflect EC P-256 instead of Ed25519.
-- This migration aligns the backend with the mobile application's native hardware-backed cryptography.

-- Update table comment
COMMENT ON TABLE ezkey_enrollment IS 'Device enrollment table establishing cryptographic binding between integration, user, and mobile device. Contains EC P-256 key pairs and tracks enrollment lifecycle from creation through verification. Each enrollment enables authentication attempts and includes security configuration like challenge requirements.';

-- Update column comments
COMMENT ON COLUMN ezkey_enrollment.integration_private_key IS 'EC P-256 private key for integration-side cryptographic operations (PKCS#8 format, Base64 encoded) - SENSITIVE DATA requiring encryption at rest and secure handling. Used by backend to sign authAttemptProofToken for mutual authentication.';

COMMENT ON COLUMN ezkey_enrollment.integration_public_key IS 'EC P-256 public key for integration-side operations (X.509 SubjectPublicKeyInfo format, Base64 encoded) - corresponding public key for integration_private_key, safe to expose. Used by mobile app to verify backend signatures (authAttemptProofTokenSignedByIntegration).';

COMMENT ON COLUMN ezkey_enrollment.device_public_key IS 'EC P-256 public key from mobile device (X.509 SubjectPublicKeyInfo format, Base64 encoded) - used to verify signatures from device during authentication attempts, set during binding process.';

