-- ============================================================================
-- Ezkey Migration V23: Partition ezkey_auth_attempt by Month
-- ============================================================================
-- Description: Converts ezkey_auth_attempt table to monthly range partitioning
--              for improved query performance and efficient data archival.
-- 
-- Context: High-volume table that will grow rapidly in production. Monthly
--          partitioning enables efficient partition pruning for date-range
--          queries and simplifies data lifecycle management.
--
-- Development Mode: This migration assumes an empty or non-existent table.
--                   No data migration is performed.
--
-- Author: Ezkey contributors
-- Date: 2025-01-XX
-- ============================================================================

-- ============================================================================
-- STEP 1: Drop Existing Table (if exists)
-- ============================================================================

-- Drop existing table and all its dependencies (indexes, constraints)
-- In development mode, this is safe as there's no data to preserve
DROP TABLE IF EXISTS ezkey_auth_attempt CASCADE;

-- ============================================================================
-- STEP 2: Create Partitioned Table Structure
-- ============================================================================

-- Create partitioned table directly with final name
-- Note: Includes columns added by V12 (encryption hash columns)
CREATE TABLE ezkey_auth_attempt (
    auth_attempt_id INT GENERATED ALWAYS AS IDENTITY,
    enrollment_id INT NOT NULL REFERENCES ezkey_enrollment(enrollment_id),
    auth_attempt_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' 
        CHECK (auth_attempt_status IN ('PENDING', 'READ', 'INVALID', 'REJECTED', 'ACCEPTED', 'EXPIRED')),
    auth_attempt_challenge INT,
    auth_attempt_proof_token TEXT NOT NULL,  -- Encrypted proof token (added by V12)
    auth_attempt_proof_token_hash VARCHAR(128),  -- Hash for deterministic lookup (added by V12)
    device_proof_token_hash VARCHAR(128),  -- Hash-only at claim; no recoverable ciphertext (ADR-0007)
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP + INTERVAL '120 seconds'),
    -- Primary key composite required for partitioned tables
    -- PostgreSQL requires UNIQUE constraints to include partition key (created_at)
    PRIMARY KEY (auth_attempt_id, created_at)
) PARTITION BY RANGE (created_at);

-- Add table-level comment
COMMENT ON TABLE ezkey_auth_attempt IS 
'Authentication attempt table partitioned by month. Tracks individual MFA requests from creation through completion. Uses one-time proof tokens to prevent replay attacks and includes automatic expiration for security. Partitioned by created_at for efficient query performance and data lifecycle management.';

-- Add column-level comments
COMMENT ON COLUMN ezkey_auth_attempt.auth_attempt_id IS 
'Primary key - unique identifier for this authentication attempt, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_auth_attempt.enrollment_id IS 
'Foreign key to enrollment that will handle this authentication - determines which device/user will receive the auth request';
COMMENT ON COLUMN ezkey_auth_attempt.auth_attempt_status IS 
'Authentication attempt lifecycle status - PENDING (created), READ (device claimed), INVALID (crypto validation failed), REJECTED (user denied), ACCEPTED (user approved), EXPIRED (superseded or timeout) - tracks complete authentication flow';
COMMENT ON COLUMN ezkey_auth_attempt.auth_attempt_challenge IS 
'Optional numeric challenge (4-6 digits) displayed to user on mobile device for additional security - required when enrollment.auth_attempt_challenge_required is TRUE';
COMMENT ON COLUMN ezkey_auth_attempt.auth_attempt_proof_token IS 
'One-time cryptographic token unique to this auth attempt - prevents replay attacks and ensures request authenticity (never reused). Encrypted at rest (added by V12).';
COMMENT ON COLUMN ezkey_auth_attempt.auth_attempt_proof_token_hash IS 
'SHA-256 hash of auth_attempt_proof_token for deterministic lookups without decryption. Unique constraint ensures one-time token guarantee (added by V12).';
COMMENT ON COLUMN ezkey_auth_attempt.device_proof_token_hash IS
'SHA-256 hash of the client-generated device proof token at pending claim. Hash-only storage — plaintext is never persisted (ADR-0007). Unique constraint ensures token uniqueness.';
COMMENT ON COLUMN ezkey_auth_attempt.created_at IS
'Audit timestamp with timezone recording when auth attempt was created - immutable value used for compliance and performance monitoring. Used as partitioning key for monthly partitions.';
COMMENT ON COLUMN ezkey_auth_attempt.expires_at IS 
'Automatic expiration timestamp with timezone (default 120 seconds) - expired attempts are invalid for security and should be cleaned up by maintenance jobs';

-- ============================================================================
-- STEP 3: Create Initial Partitions
-- ============================================================================

-- Create partition for current month
-- Note: Using first day of current month to first day of next month
DO $$
DECLARE
    current_month_start TIMESTAMPTZ;
    next_month_start TIMESTAMPTZ;
    partition_name TEXT;
BEGIN
    -- Calculate current month boundaries (using TIMESTAMPTZ for partition boundaries)
    current_month_start := DATE_TRUNC('month', CURRENT_TIMESTAMP);
    next_month_start := current_month_start + INTERVAL '1 month';
    
    -- Create partition name (e.g., ezkey_auth_attempt_2025_01)
    partition_name := 'ezkey_auth_attempt_' || TO_CHAR(current_month_start, 'YYYY_MM');
    
    -- Create partition for current month
    EXECUTE format(
        'CREATE TABLE %I PARTITION OF ezkey_auth_attempt FOR VALUES FROM (%L) TO (%L)',
        partition_name,
        current_month_start,
        next_month_start
    );
    
    -- Create partition for next month (pre-create for seamless transition)
    partition_name := 'ezkey_auth_attempt_' || TO_CHAR(next_month_start, 'YYYY_MM');
    EXECUTE format(
        'CREATE TABLE %I PARTITION OF ezkey_auth_attempt FOR VALUES FROM (%L) TO (%L)',
        partition_name,
        next_month_start,
        next_month_start + INTERVAL '1 month'
    );
END $$;

-- ============================================================================
-- STEP 4: Create Indexes on Partitioned Table
-- ============================================================================

-- Index for enrollment queries with created_at (supersession queries)
-- This index will be created locally on each partition
CREATE INDEX idx_auth_attempt_enrollment_created 
ON ezkey_auth_attempt(enrollment_id, created_at DESC);

-- Index for expiration cleanup jobs
-- Note: Cannot use CURRENT_TIMESTAMP in partial index predicate (not IMMUTABLE)
-- The index will still be efficient for cleanup queries with WHERE expires_at < NOW()
CREATE INDEX idx_auth_attempt_expires_at 
ON ezkey_auth_attempt(expires_at);

-- Index for status filtering
CREATE INDEX idx_auth_attempt_status 
ON ezkey_auth_attempt(auth_attempt_status);

-- Unique indexes on hash columns (added by V12)
-- Note: PostgreSQL requires UNIQUE constraints on partitioned tables to include partition key
-- Including created_at ensures global uniqueness while satisfying PostgreSQL's requirement
-- Hash collisions across partitions are extremely unlikely (SHA-256)
CREATE UNIQUE INDEX uq_auth_attempt_proof_token_hash 
ON ezkey_auth_attempt(auth_attempt_proof_token_hash, created_at) 
WHERE auth_attempt_proof_token_hash IS NOT NULL;

CREATE UNIQUE INDEX uq_auth_attempt_device_proof_token_hash 
ON ezkey_auth_attempt(device_proof_token_hash, created_at) 
WHERE device_proof_token_hash IS NOT NULL;

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- ezkey_auth_attempt table is now partitioned by month (created_at).
-- 
-- Next Steps:
-- 1. Test partition pruning with queries
-- 2. Set up scheduled job to create future partitions (see PartitionSchedulerService)
-- ============================================================================
-- ============================================================================
-- Ezkey Migration V24: Partition ezkey_audit_log by Month and API
-- ============================================================================
-- Description: Converts ezkey_audit_log table to composite partitioning:
--              RANGE (created_at) by month, then LIST (api_name) per month
--              with sub-partitions ADMIN_API, AUTH_API, INTEGRATION_API.
--
-- Context: High-volume table with three distinct event streams (Admin API,
--          Auth API, Integration API). Sub-partitioning by api_name enables partition
--          pruning when filtering by API and natural segregation of traffic.
--
-- Development Mode: This migration assumes an empty or non-existent table.
--                   No data migration is performed.
--
-- Author: Ezkey contributors
-- Date: 2025-01-XX
-- ============================================================================

-- ============================================================================
-- STEP 1: Drop Existing Table (if exists)
-- ============================================================================

-- Drop existing table and all its dependencies (indexes, constraints)
-- In development mode, this is safe as there's no data to preserve
DROP TABLE IF EXISTS ezkey_audit_log CASCADE;
DROP SEQUENCE IF EXISTS ezkey_audit_log_id_seq;

-- ============================================================================
-- STEP 2: Create Partitioned Table Structure
-- ============================================================================

-- Explicit named sequence for audit_log_id (owned by ezkey_migrate). Standalone sequence +
-- DEFAULT nextval (not IDENTITY) so JPA GenerationType.SEQUENCE can pre-allocate the id,
-- compute entry_hmac, and persist with a single INSERT. Equivalent accept-explicit-value
-- semantics to GENERATED BY DEFAULT AS IDENTITY; Hibernate schema validation requires a
-- non-identity sequence visible in the catalog.
CREATE SEQUENCE ezkey_audit_log_id_seq AS BIGINT;

-- Create partitioned table directly with final name
CREATE TABLE ezkey_audit_log (
    audit_log_id BIGINT NOT NULL DEFAULT nextval('ezkey_audit_log_id_seq'),

    -- Event classification
    event_type VARCHAR(50) NOT NULL,
    event_action VARCHAR(100) NOT NULL,
    event_status VARCHAR(20) NOT NULL CHECK (event_status IN ('SUCCESS', 'FAILURE', 'ERROR')),

    -- API identification
    api_name VARCHAR(50) NOT NULL CHECK (api_name IN ('ADMIN_API', 'AUTH_API', 'INTEGRATION_API')),

    -- Network information
    ip_address VARCHAR(45),
    user_agent TEXT,

    -- Entity references (nullable for flexibility)
    admin_id INT REFERENCES ezkey_admin(admin_id) ON DELETE SET NULL,
    integration_id INT REFERENCES ezkey_integration(integration_id) ON DELETE SET NULL,
    enrollment_id INT REFERENCES ezkey_enrollment(enrollment_id) ON DELETE SET NULL,
    auth_attempt_id INT,
    auth_attempt_created_at TIMESTAMPTZ,
    tenant_id INT REFERENCES ezkey_tenant(tenant_id) ON DELETE SET NULL,
    target_admin_id INT REFERENCES ezkey_admin(admin_id) ON DELETE SET NULL,
    -- Foreign key to partitioned table requires composite key reference
    -- PostgreSQL requires FK to partitioned table to reference composite primary key
    FOREIGN KEY (auth_attempt_id, auth_attempt_created_at)
        REFERENCES ezkey_auth_attempt(auth_attempt_id, created_at)
        ON DELETE SET NULL,

    -- Event details and errors
    event_details TEXT,
    error_message TEXT,

    -- Timestamp (partitioning key)
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
) PARTITION BY RANGE (created_at);

ALTER SEQUENCE ezkey_audit_log_id_seq OWNED BY ezkey_audit_log.audit_log_id;

-- Add table-level comment
COMMENT ON TABLE ezkey_audit_log IS
'Comprehensive audit logging with composite partitioning: RANGE (created_at) by month, LIST (api_name) per month (ADMIN_API, AUTH_API, INTEGRATION_API). Enables partition pruning by date and API for security monitoring, forensic analysis, and operator-visible audit.';

-- Add column-level comments (same as original, with partitioning note)
COMMENT ON COLUMN ezkey_audit_log.audit_log_id IS
'Primary key - unique identifier for this audit log entry. Default nextval(ezkey_audit_log_id_seq); application may supply an explicit value (JPA SEQUENCE pre-allocation for single-INSERT HMAC seal).';
COMMENT ON COLUMN ezkey_audit_log.event_type IS
'Type of event being audited (e.g., ADMIN_LOGIN, ENROLLMENT_CREATED, AUTH_ATTEMPT_CREATED)';
COMMENT ON COLUMN ezkey_audit_log.event_action IS
'Specific action taken (e.g., login_attempt, enrollment_deletion, device_binding)';
COMMENT ON COLUMN ezkey_audit_log.event_status IS
'Result status of the event - SUCCESS (completed successfully), FAILURE (failed validation), ERROR (unexpected error)';
COMMENT ON COLUMN ezkey_audit_log.api_name IS
'API where the event originated - ADMIN_API (port 9080), AUTH_API (port 8080), or INTEGRATION_API (port 7080)';
COMMENT ON COLUMN ezkey_audit_log.ip_address IS
'Client IP address extracted from request headers (CF-Connecting-IP, X-Forwarded-For, X-Real-IP) - used for security monitoring';
COMMENT ON COLUMN ezkey_audit_log.user_agent IS
'User agent string from HTTP request - helps identify device types and potential security issues';
COMMENT ON COLUMN ezkey_audit_log.admin_id IS
'Foreign key to admin user involved in the event - SET NULL on admin deletion to preserve audit trail';
COMMENT ON COLUMN ezkey_audit_log.integration_id IS
'Foreign key to integration involved in the event - SET NULL on integration deletion to preserve audit trail';
COMMENT ON COLUMN ezkey_audit_log.enrollment_id IS
'Foreign key to enrollment involved in the event - SET NULL on enrollment deletion to preserve audit trail';
COMMENT ON COLUMN ezkey_audit_log.auth_attempt_id IS
'Foreign key (part 1) to authentication attempt involved in the event - part of composite FK to partitioned table';
COMMENT ON COLUMN ezkey_audit_log.auth_attempt_created_at IS
'Foreign key (part 2) to authentication attempt - created_at timestamp from referenced auth_attempt. Required for FK to partitioned table (ezkey_auth_attempt) which uses composite primary key (auth_attempt_id, created_at). SET NULL on auth attempt deletion to preserve audit trail';
COMMENT ON COLUMN ezkey_audit_log.tenant_id IS
'Foreign key to tenant involved in the event - SET NULL on tenant deletion to preserve audit trail';
COMMENT ON COLUMN ezkey_audit_log.target_admin_id IS
'Admin ID that is the subject of the event (e.g. created, deactivated, or activated). Used for querying all events affecting a given administrator. NULL for non-admin-lifecycle events. SET NULL on admin deletion to preserve audit trail.';
COMMENT ON COLUMN ezkey_audit_log.event_details IS
'Additional event-specific details in structured format - used for forensic analysis and debugging';
COMMENT ON COLUMN ezkey_audit_log.error_message IS
'Error message for failed or error status events - used for troubleshooting and security analysis';
COMMENT ON COLUMN ezkey_audit_log.created_at IS
'Timestamp with timezone when the event was recorded - immutable value for compliance tracking. Used as partitioning key for monthly partitions.';

-- ============================================================================
-- STEP 3: Create Initial Partitions (composite: month + api_name sub-partitions)
-- ============================================================================

-- Helper: create one monthly partition with three LIST (api_name) sub-partitions
DO $$
DECLARE
    current_month_start TIMESTAMPTZ;
    next_month_start TIMESTAMPTZ;
    month_partition_name TEXT;
BEGIN
    current_month_start := DATE_TRUNC('month', CURRENT_TIMESTAMP);
    next_month_start := current_month_start + INTERVAL '1 month';

    -- Current month: create partition partitioned by LIST (api_name)
    month_partition_name := 'ezkey_audit_log_' || TO_CHAR(current_month_start, 'YYYY_MM');
    EXECUTE format(
        'CREATE TABLE %I PARTITION OF ezkey_audit_log FOR VALUES FROM (%L) TO (%L) PARTITION BY LIST (api_name)',
        month_partition_name,
        current_month_start,
        next_month_start
    );
    EXECUTE format('CREATE TABLE %I PARTITION OF %I FOR VALUES IN (''ADMIN_API'')', month_partition_name || '_admin', month_partition_name);
    EXECUTE format('CREATE TABLE %I PARTITION OF %I FOR VALUES IN (''AUTH_API'')', month_partition_name || '_auth', month_partition_name);
    EXECUTE format('CREATE TABLE %I PARTITION OF %I FOR VALUES IN (''INTEGRATION_API'')', month_partition_name || '_integration', month_partition_name);

    -- Next month (pre-create for seamless transition)
    month_partition_name := 'ezkey_audit_log_' || TO_CHAR(next_month_start, 'YYYY_MM');
    EXECUTE format(
        'CREATE TABLE %I PARTITION OF ezkey_audit_log FOR VALUES FROM (%L) TO (%L) PARTITION BY LIST (api_name)',
        month_partition_name,
        next_month_start,
        next_month_start + INTERVAL '1 month'
    );
    EXECUTE format('CREATE TABLE %I PARTITION OF %I FOR VALUES IN (''ADMIN_API'')', month_partition_name || '_admin', month_partition_name);
    EXECUTE format('CREATE TABLE %I PARTITION OF %I FOR VALUES IN (''AUTH_API'')', month_partition_name || '_auth', month_partition_name);
    EXECUTE format('CREATE TABLE %I PARTITION OF %I FOR VALUES IN (''INTEGRATION_API'')', month_partition_name || '_integration', month_partition_name);
END $$;

-- ============================================================================
-- STEP 4: Create Indexes on Partitioned Table
-- ============================================================================

-- Index for event type queries (most common filter)
-- This index will be created locally on each partition
CREATE INDEX idx_audit_log_event_type
ON ezkey_audit_log(event_type);

-- Index for status queries (security monitoring)
CREATE INDEX idx_audit_log_status
ON ezkey_audit_log(event_status);

-- Index for IP address queries (forensic analysis)
CREATE INDEX idx_audit_log_ip_address
ON ezkey_audit_log(ip_address);

-- Index for date range queries (compliance reporting)
CREATE INDEX idx_audit_log_created_at
ON ezkey_audit_log(created_at DESC);

-- Composite index for API + event type queries
CREATE INDEX idx_audit_log_api_event
ON ezkey_audit_log(api_name, event_type);

-- Index for enrollment tracking
CREATE INDEX idx_audit_log_enrollment
ON ezkey_audit_log(enrollment_id)
WHERE enrollment_id IS NOT NULL;

-- Index for admin tracking
CREATE INDEX idx_audit_log_admin
ON ezkey_audit_log(admin_id, created_at DESC)
WHERE admin_id IS NOT NULL;

-- Index for target admin tracking (admin lifecycle events)
CREATE INDEX idx_audit_log_target_admin
ON ezkey_audit_log(target_admin_id)
WHERE target_admin_id IS NOT NULL;

-- JSONB GIN indexes for encryption operations (added by V19)
-- These indexes enable efficient queries on event_details JSONB field
CREATE INDEX idx_audit_encryption_key_id
ON ezkey_audit_log
USING GIN ((event_details::jsonb))
WHERE event_type IN ('KEY_INTRODUCED', 'KEY_PROMOTED_PRIMARY', 'KEY_DEMOTED', 'KEY_DISABLED');

CREATE INDEX idx_audit_reencryption_batch_id
ON ezkey_audit_log
USING GIN ((event_details::jsonb))
WHERE event_type IN ('REENCRYPTION_STARTED', 'REENCRYPTION_COMPLETED', 'REENCRYPTION_FAILED',
                     'REENCRYPTION_PAUSED', 'REENCRYPTION_RESUMED', 'REENCRYPTION_BATCH_PROGRESS');

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- ezkey_audit_log is now composite partitioned: RANGE (created_at) by month,
-- each month partition is LIST (api_name) with sub-partitions _admin, _auth, _integration.
--
-- Next Steps:
-- 1. Partition scheduler creates future months via create_monthly_partition (with sub-partitions)
-- 2. Plan for 7-year retention policy (operator-visible audit)
-- ============================================================================
-- ============================================================================
-- Ezkey Migration V25: Create Partition Management Function with SECURITY DEFINER
-- ============================================================================
-- Description: Creates a PostgreSQL function with SECURITY DEFINER to enable
--              partition creation without granting DDL privileges to application role.
-- 
-- Context: In production, database roles are separated:
--          - EZKEY_owner: DDL privileges (used by Flyway)
--          - EZKEY_app: DML privileges only (used by application)
--          
--          This function allows the application to create partitions safely
--          without requiring CREATE TABLE privilege on the application role.
--
-- Security: Function uses SECURITY DEFINER to execute with owner privileges,
--           while application role only needs EXECUTE privilege.
--
-- Author: Ezkey contributors
-- Date: 2025-01-XX
-- ============================================================================

-- ============================================================================
-- STEP 1: Create Partition Management Function
-- ============================================================================

-- Function to create monthly partitions for partitioned tables.
-- For ezkey_audit_log: creates monthly partition and three LIST (api_name) sub-partitions.
-- For ezkey_auth_attempt: creates a single monthly partition.
-- Uses SECURITY DEFINER to execute with owner privileges.
CREATE OR REPLACE FUNCTION create_monthly_partition(
    p_table_name TEXT,
    p_partition_name TEXT,
    p_start_date TIMESTAMPTZ,
    p_end_date TIMESTAMPTZ
) RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF p_table_name NOT IN ('ezkey_auth_attempt', 'ezkey_audit_log') THEN
        RAISE EXCEPTION 'Invalid table name: %. Only ezkey_auth_attempt and ezkey_audit_log are allowed.', p_table_name;
    END IF;

    IF p_partition_name !~ '^ezkey_(auth_attempt|audit_log)_\d{4}_\d{2}$' THEN
        RAISE EXCEPTION 'Invalid partition name format: %. Expected format: ezkey_<table>_YYYY_MM', p_partition_name;
    END IF;

    -- relkind 'r' = regular table (ezkey_auth_attempt monthly partition), 'p' = partitioned table (ezkey_audit_log monthly parent)
    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = p_partition_name AND relkind IN ('r', 'p')) THEN
        RAISE NOTICE 'Partition % already exists, skipping creation', p_partition_name;
        RETURN false;
    END IF;

    IF p_table_name = 'ezkey_audit_log' THEN
        -- Composite: monthly partition then LIST (api_name) sub-partitions
        EXECUTE format(
            'CREATE TABLE %I PARTITION OF ezkey_audit_log FOR VALUES FROM (%L) TO (%L) PARTITION BY LIST (api_name)',
            p_partition_name,
            p_start_date,
            p_end_date
        );
        EXECUTE format('CREATE TABLE %I PARTITION OF %I FOR VALUES IN (''ADMIN_API'')', p_partition_name || '_admin', p_partition_name);
        EXECUTE format('CREATE TABLE %I PARTITION OF %I FOR VALUES IN (''AUTH_API'')', p_partition_name || '_auth', p_partition_name);
        EXECUTE format('CREATE TABLE %I PARTITION OF %I FOR VALUES IN (''INTEGRATION_API'')', p_partition_name || '_integration', p_partition_name);
        RAISE NOTICE 'Created partition % and sub-partitions _admin, _auth, _integration for table ezkey_audit_log', p_partition_name;
    ELSE
        -- ezkey_auth_attempt: single monthly partition
        EXECUTE format(
            'CREATE TABLE %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)',
            p_partition_name,
            p_table_name,
            p_start_date,
            p_end_date
        );
        RAISE NOTICE 'Created partition: % for table: %', p_partition_name, p_table_name;
    END IF;
    RETURN true;
END;
$$;

-- ============================================================================
-- STEP 2: Set Function Ownership and Permissions
-- ============================================================================

-- Ownership and EXECUTE grants for runtime roles are applied post-migrate by
-- scripts/db/apply-grants.sql (roles: ezkey_migrate owner, ezkey_admin EXECUTE).
-- See docs/DATABASE_ROLE_PERMISSIONS_MATRIX.md.

-- Revoke EXECUTE from public (security best practice)
REVOKE EXECUTE ON FUNCTION create_monthly_partition(TEXT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) FROM PUBLIC;

-- ============================================================================
-- STEP 3: Add Documentation Comments
-- ============================================================================

COMMENT ON FUNCTION create_monthly_partition IS 
'Creates monthly partition for ezkey_auth_attempt (single partition) or ezkey_audit_log (monthly partition plus LIST(api_name) sub-partitions _admin, _auth, _integration). '
'Executes with owner privileges via SECURITY DEFINER. Idempotent - returns BOOLEAN: true if created, false if already existed.';

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- Partition management function created successfully.
-- 
-- Security Notes:
-- - Function uses SECURITY DEFINER to execute with owner privileges
-- - Application role only needs EXECUTE privilege (not CREATE TABLE)
-- - Function validates inputs to prevent SQL injection
-- - Function is idempotent (safe to call multiple times)
--
-- Production Setup:
-- 1. Ensure function is owned by owner role (EZKEY_owner)
-- 2. Grant EXECUTE to application role (EZKEY_app)
-- 3. Revoke EXECUTE from PUBLIC (already done)
--
-- Usage:
-- SELECT create_monthly_partition(
--     'ezkey_auth_attempt',
--     'ezkey_auth_attempt_2025_02',
--     '2025-02-01 00:00:00+00'::TIMESTAMPTZ,
--     '2025-03-01 00:00:00+00'::TIMESTAMPTZ
-- );
-- Returns: true if partition was created, false if it already existed
-- ============================================================================

