-- ============================================================================
-- Ezkey Migration V6: Create Audit Logging Infrastructure
-- ============================================================================
-- Description: Creates comprehensive audit logging system for security
--              monitoring, forensic analysis, and SOC2 compliance support.
--
-- Context: This migration introduces audit logging capabilities for all
--          critical operations across admin-api and auth-api to support
--          security monitoring and eventual SOC2 certification.
--
-- Author: Ezkey contributors
-- Date: 2025-10-16
-- ============================================================================

-- ============================================================================
-- STEP 1: Create Audit Log Table
-- ============================================================================

-- Audit log table for security monitoring and compliance
CREATE TABLE ezkey_audit_log (
    audit_log_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- Event classification
    event_type VARCHAR(50) NOT NULL,
    event_action VARCHAR(100) NOT NULL,
    event_status VARCHAR(20) NOT NULL CHECK (event_status IN ('SUCCESS', 'FAILURE', 'ERROR')),

    -- API identification
    api_name VARCHAR(50) NOT NULL CHECK (api_name IN ('ADMIN_API', 'AUTH_API', 'M2M_API')),

    -- Network information
    ip_address VARCHAR(45),
    user_agent TEXT,

    -- Entity references (nullable for flexibility)
    admin_id INT REFERENCES ezkey_admin(admin_id) ON DELETE SET NULL,
    integration_id INT REFERENCES ezkey_integration(integration_id) ON DELETE SET NULL,
    enrollment_id INT REFERENCES ezkey_enrollment(enrollment_id) ON DELETE SET NULL,
    auth_attempt_id INT REFERENCES ezkey_auth_attempt(auth_attempt_id) ON DELETE SET NULL,
    tenant_id INT REFERENCES ezkey_tenant(tenant_id) ON DELETE SET NULL,
    target_admin_id INT REFERENCES ezkey_admin(admin_id) ON DELETE SET NULL,

    -- Event details and errors
    event_details TEXT,
    error_message TEXT,

    -- Timestamp
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ============================================================================
-- STEP 2: Add Table and Column Comments
-- ============================================================================

COMMENT ON TABLE ezkey_audit_log IS
'Comprehensive audit logging for security monitoring, forensic analysis, and SOC2 compliance. Tracks all critical operations across admin-api and auth-api with full context including IP addresses, user agents, and entity references.';

COMMENT ON COLUMN ezkey_audit_log.audit_log_id IS 'Primary key - unique identifier for this audit log entry, auto-generated by database sequence';
COMMENT ON COLUMN ezkey_audit_log.event_type IS 'Type of event being audited (e.g., ADMIN_LOGIN, ENROLLMENT_CREATED, AUTH_ATTEMPT_CREATED)';
COMMENT ON COLUMN ezkey_audit_log.event_action IS 'Specific action taken (e.g., login_attempt, enrollment_deletion, device_binding)';
COMMENT ON COLUMN ezkey_audit_log.event_status IS 'Result status of the event - SUCCESS (completed successfully), FAILURE (failed validation), ERROR (unexpected error)';
COMMENT ON COLUMN ezkey_audit_log.api_name IS 'API where the event originated - ADMIN_API (port 9080), AUTH_API (port 8080), or M2M_API (port 7080)';
COMMENT ON COLUMN ezkey_audit_log.ip_address IS 'Client IP address extracted from request headers (CF-Connecting-IP, X-Forwarded-For, X-Real-IP) - used for security monitoring';
COMMENT ON COLUMN ezkey_audit_log.user_agent IS 'User agent string from HTTP request - helps identify device types and potential security issues';
COMMENT ON COLUMN ezkey_audit_log.admin_id IS 'Foreign key to admin user involved in the event - SET NULL on admin deletion to preserve audit trail';
COMMENT ON COLUMN ezkey_audit_log.integration_id IS 'Foreign key to integration involved in the event - SET NULL on integration deletion to preserve audit trail';
COMMENT ON COLUMN ezkey_audit_log.enrollment_id IS 'Foreign key to enrollment involved in the event - SET NULL on enrollment deletion to preserve audit trail';
COMMENT ON COLUMN ezkey_audit_log.auth_attempt_id IS 'Foreign key to authentication attempt involved in the event - SET NULL on auth attempt deletion to preserve audit trail';
COMMENT ON COLUMN ezkey_audit_log.tenant_id IS 'Foreign key to tenant involved in the event - SET NULL on tenant deletion to preserve audit trail';
COMMENT ON COLUMN ezkey_audit_log.target_admin_id IS 'Admin ID that is the subject of the event (e.g. created, deactivated, or activated). Used for querying all events affecting a given administrator. NULL for non-admin-lifecycle events. SET NULL on admin deletion to preserve audit trail.';
COMMENT ON COLUMN ezkey_audit_log.event_details IS 'Additional event-specific details in structured format - used for forensic analysis and debugging';
COMMENT ON COLUMN ezkey_audit_log.error_message IS 'Error message for failed or error status events - used for troubleshooting and security analysis';
COMMENT ON COLUMN ezkey_audit_log.created_at IS 'Timestamp with timezone when the event was recorded - immutable value for compliance tracking';

-- ============================================================================
-- STEP 3: Create Performance Indexes
-- ============================================================================

-- Index for event type queries (most common filter)
CREATE INDEX idx_audit_log_event_type ON ezkey_audit_log(event_type);

-- Index for status queries (security monitoring)
CREATE INDEX idx_audit_log_status ON ezkey_audit_log(event_status);

-- Index for IP address queries (forensic analysis)
CREATE INDEX idx_audit_log_ip_address ON ezkey_audit_log(ip_address);

-- Index for date range queries (compliance reporting)
CREATE INDEX idx_audit_log_created_at ON ezkey_audit_log(created_at DESC);

-- Composite index for API + event type queries
CREATE INDEX idx_audit_log_api_event ON ezkey_audit_log(api_name, event_type);

-- Index for enrollment tracking
CREATE INDEX idx_audit_log_enrollment ON ezkey_audit_log(enrollment_id) WHERE enrollment_id IS NOT NULL;

-- Index for admin tracking
CREATE INDEX idx_audit_log_admin ON ezkey_audit_log(admin_id) WHERE admin_id IS NOT NULL;

-- Index for target admin tracking (admin lifecycle events)
CREATE INDEX idx_audit_log_target_admin ON ezkey_audit_log(target_admin_id) WHERE target_admin_id IS NOT NULL;

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- Audit logging infrastructure created successfully.
-- Ready for security monitoring and SOC2 compliance tracking.
-- ============================================================================
