name: ezkey-tenant-ui

services:
  tenant-ui:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ezkey-tenant-ui
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
