# Manual license mappings for dependencies without license metadata
# Format: dependency.groupId.dependency.artifactId=License Name|License URL
#
# This file is used by the License Maven Plugin to fill in missing license information.
# Add entries here when dependencies don't have license information in their POM files.
#
# Example:
# com.example.library=MIT License|https://opensource.org/licenses/MIT
